### ISSUE TITLE
Improve the build process

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#1021]
**Is your feature request related to a problem? Please describe.**

The current image has a couple of rough edges that we might want to smooth. Let's track and discuss here. We might open other, more actionable issues, later.

- Some Docker image tags we depend on are not stable:
    - `hadolint/hadolint:latest-alpine`
    - `python:alpine`
- Some Docker image dependencies are not update by dependabot:
    - `accurics/terrascan`. References: #1019, #1015, https://github.com/accurics/terrascan/issues/398
    - `hadolint/hadolint`. Reference: https://github.com/github/super-linter/network/updates/70487128
    - `DART_VERSION`
    - `GLIBC_VERSION`
- Size: the latest master compressed size of the image is ~1.5GB. Not compressed: ~3.8GB
- Install `ansible-lint` from PyPi, so we can manage updates with Dependabot. Additionally, the version in Alpine package repos is outdated, compared to the one on PyPi.
- Grab binaries from container images where possible, instead of installing. This needs additional investigation. Maybe we can have less dependency conflicts that way.
- Anything else?

**Comment by mikelax** [comment]
I would like to see if anything can be done about the Size of the image specifically, as this contributes to a lot of time in each workflow run, typically 1.5 minutes. I have not yet found a way to cache docker images created with a "uses" step.

Should this maybe be broken out to a separate issue?

**Comment by GaboFDC** [comment]
About image size, is something not so easy to do. i.e, the more linters we want to support, the more binaries and dependencies we need to install.
There was some talk about maintaining specific versions with specific linters, but I thkn that will be a pain to maintain.
The ideal fix would be on the GitHub actions (actions/cache@v2) team, to allow to cache docker images. But is the path is not clear on that side: https://github.com/actions/cache/issues/31

 About some dependencies both the auto-update, and the stable thing, would need a statement from our side, to define a minimum required level in order to allow the linter (having a stable release, having versioned tags, having a maintained docker image to copy the binary from) but that would also mean to drop support on some we already have.

I think we grab binaries from container images whenever we can, but not sure if on the latest additions this has been check, maybe it is worth another look. 

The issue with ansible-lint I think has some conflicts when installing via pip, I don't remember exactly but I remember that been an issue of some sort when I moved the dependencies to the Pipfile.

**Comment by ferrarimarco** [comment]
I'm wondering if we can use the images of other linters directly, instead of embedding everything in our image. A couple of ideas:

1. Docker-in-docker: instead bundling everything in our image, we run containers when available, and bundle the ones that don't have an image in our own.
1. Give up some portability for greater efficiency: we build multiple images, instead of a single, big one, and invoke those images with a script. This requires a compatible shell (likely POSIX or bash).

I've yet to deeply inspect the `Dockerfile` to see if there's something we can do.

**Comment by GaboFDC** [comment]
Did some dig-up and fixed the ansible-lint issue https://github.com/github/super-linter/pull/1037
About the 3 ideas, I like the first one. The second, could you detail a bit more

**Comment by ferrarimarco** [comment]
Basically you run docker inside our container, spinning up other containers as needed. Example: in our Dockerfile, we install editorconfig-checker from `mstruebing/editorconfig-checker`. Instead of doing that, we might just spin an instance of that image. So you'd have a container that's managed by a docker daemon that is containerized as well.

**Comment by mikelax** [comment]
I was typing out a much more complicated response but then I reread @ferrarimarco's comment above and I was basically restating Option 1.
I think this might also lead to a possible future enhancement where optimized versions of super-linter images could be created for common use cases (project types).

**Comment by GaboFDC** [comment]
The problem with option 2 will be that downloading requirements (the other docker image that we spinup) at run time doesn't seem to be the best idea to me.
Option 1 seems more reliable but is a bit more work as we will build and maintain the images for the linters that don't provide it and copy the binary from there.

I'll also like to hear @admiralAwkbar opinions.

**Comment by ferrarimarco** [comment]
> The problem with option 2 will be that downloading requirements (the other docker image that we spinup) at run time doesn't seem to be the best idea to me.

Don't we do the same now? 😃 

> Option 1 seems more reliable but is a bit more work as we will build and maintain the images for the linters that don't provide it and copy the binary from there.

True. I guess we might try to be clever and reduce the number of images maybe?

**Comment by mikelax** [comment]
I was wondering about the number of docker images used. Is the thought process that it helps with keeping images (libraries) up to date via code-scanning? 

As one small example, the library "shellcheck" could be installed via package instead of using a docker image for it.

**Comment by ferrarimarco** [comment]
Yep. We default using a docker images when available because Dependabot keeps them up-to-date, and so that we only pick what we need from the image.

Dependabot doesn't (yet?) support managing dependencies that are installed with an OS package manager, such as APT or APK. Additionally, often OS package repositories don't have the most up-to-date version of the packages that we want to install.

**Comment by nvuillam** [comment]
About image size, you could implement **Super-Linter flavors**

Most projects do no need to be linted with all linters embedded in the image.
To solve that, define docker images containing the list of linters required for projects types: javascript, java, php, python ...

The recipe is the following:
- one sub folder by flavor, containing a Dockerfile and an action.yml
- use a [build matrix in CI](https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/deploy-RELEASE-flavors.yml) to build & deploy all flavors
- When linting with the full image, compare required list of linters with list of linters available in different flavors
- If matching flavor found, suggest the user to use it: it can be done by changing one line in the GHA workflow file ( `uses:` )

It's implemented in python on Mega-Linter, but feel free to make it here too :)
https://nvuillam.github.io/mega-linter/flavors/

**Comment by mikelax** [comment]
I'm wondering if this issue should be broken up to a few smaller issues that we know have specific next steps.  @ferrarimarco mentioned in the original description there are several docker images that are old, not pinned to a version, etc. we could create issues for those. 

That then leaves the open discussion about reducing the image size.

**Comment by mikesoso** [comment]
> **您的功能請求是否與問題有關？請描述。**
> 
> 當前圖像有一些可能需要平滑的粗糙邊緣。讓我們在這裡跟踪和討論。我們稍後可能會提出其他更可行的問題。
> 
> * 我們依賴的某些Docker圖像標籤不穩定：
>   
>   * `hadolint/hadolint:latest-alpine`
>   * `python:alpine`
> * 某些Docker映像依存關係不是由dependabot更新的：
>   
>   * `accurics/terrascan`。參考文獻：[＃1019](https://github.com/github/super-linter/issues/1019)，[＃1015](https://github.com/github/super-linter/pull/1015)，[Accurics / terrascan＃398](https://github.com/accurics/terrascan/issues/398)
>   * `hadolint/hadolint`。參考：[https](https://github.com/github/super-linter/network/updates/70487128) : [//github.com/github/super-linter/network/updates/70487128](https://github.com/github/super-linter/network/updates/70487128)
>   * `DART_VERSION`
>   * `GLIBC_VERSION`
> * 大小：圖片的最新主壓縮大小為〜1.5GB。未壓縮：〜3.8GB
> * `ansible-lint`從PyPi安裝，因此我們可以使用Dependabot管理更新。此外，與PyPi上的版本相比，Alpine軟件包存儲庫中的版本已過時。
> * 盡可能從容器映像中獲取二進製文件，而不要安裝。這需要進一步調查。也許我們可以通過這種方式減少依賴衝突。
> * 還要別的嗎？
