### ISSUE TITLE
Kotlin support 

### ISSUE THREAD

**Issue by LifeIsStrange** [github/super-linter#107]
I believe klint is the most popular kotlin linter and shouldn't be too opinionated:

> ktlint tries to capture (reflect) official code style* from kotlinlang.org and Android Kotlin Style Guide (+ we respect your .editorconfig and support additional ruleset|s).

https://github.com/pinterest/ktlint

If you were to create a super-static-analyser 
It could use https://github.com/detekt/detekt

**Comment by sschuberth** [comment]
Note that *detekt* can [make use of](https://github.com/detekt/detekt#adding-more-rule-sets) *ktlint*, so if only adding support for either one it's probably preferable to add support for *detekt*.
