### ISSUE TITLE
Linter failed on deleted file

### ISSUE THREAD

**Issue by bogaertg** [github/super-linter#1078]
## Describe the bug

When you delete a file in a branch, super linter failed to check this file

## Expected behavior

Nothing to lint because file is deleted

## Steps to Reproduce

USe this repository
1. Create one file in master
2. Create a branch and delete this file
3. Super linter failed with this message 
<img width="740" alt="Capture d’écran 2020-12-14 à 11 10 47" src="https://user-images.githubusercontent.com/30294729/102068793-33cc9d80-3dfd-11eb-823e-aed01dcab12d.png">

## Logs

https://github.com/bogaertg/linter-test/runs/1549412398?check_suite_focus=true

**Comment by GaboFDC** [comment]
Hello, the provided link seems broken. I checked ad the repo doesn't exist or is private.
Could you test a gain and if possible run with `ACTIONS_RUNNER_DEBUG=true`

**Comment by bazzadp** [comment]
I got same thing: https://github.com/HTTPArchive/almanac.httparchive.org/runs/1566294692?check_suite_focus=true

I found reverting from 3.14.3 to 3.14.0 fixed the issue so guess something introduced between those versions?

**Comment by bazzadp** [comment]
Still an issue

**Comment by dec5e** [comment]
This looks like the issue explained in #1167.

**Comment by bazzadp** [comment]
Still an issue

**Comment by bogaertg** [comment]
i change the visibility of the repository

**Comment by GaboFDC** [comment]
Could you trigger a new build to see the run with the latest super linter version?
Also test using the pull_request trigger

**Comment by bogaertg** [comment]
it seems fixed with latest version (3.14)

**Comment by dec5e** [comment]
> Also test using the pull_request trigger

`pull_request` trigger has a different git diff behaviour. I'd say more correct, at least it excludes deleted files. So it for sure will work :slightly_smiling_face: 

I guess if `push` is fixed it's because more error handling was added, rather than fixing git command parameters.

See #1167 for more details.
