### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by GiorgioG** [github/super-linter#108]
Using https://github.com/rust-lang/rust-clippy

**Comment by MCOfficer** [comment]
rust support would still be appreciated.

**Comment by MCOfficer** [comment]
fine, i'll play "keep the feature request open" with you.

**Comment by boarnoah** [comment]
not stale, rust-clippy is an official project as well making it a very good choice.

**Comment by MCOfficer** [comment]
Begone, bot!

**Comment by MCOfficer** [comment]
Keep your forked tongue behind your teeth. I have not passed through fire and death to bandy words with a serving-man till the lightning falls.

(if anyone wants to mark all of these as offtopic, please do. Useless clutter...)

**Comment by GaboFDC** [comment]
Also adding a note, reminding that this is an open source project and as stated in the issue template:

> **Note**
> If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

So if anyone in the community is willing to dedicate it's free/own time to help out, as the rest of the maintainers do, it will really be appreciated :)

**Comment by nvuillam** [comment]
If anyone is willing to make the PR, all the installation and commands to integrate clippy are here -> https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/rust.megalinter-descriptor.yml :)

**Comment by MCOfficer** [comment]
Top'o'the morning to you too, bot.

**Comment by yanganto** [comment]
Clippy is good to help developers writting better code, and do things more than a linter.  For example, it will suggest avoiding using the nesting of blocks.  Currently, the frame of the super-linter linting in one file by one file way and Clippy is not suitable in the way.  Such that `rustfmt` is implemented first.
