### ISSUE TITLE
Advice on mono-repo with distinct sub-projects

### ISSUE THREAD

**Issue by Zodiase** [github/super-linter#1083]
Say I have a repo that has two distinct JavaScript projects. 

Project A is located at `/projA`, while project B is located at `/projA/foobar/projB`.

There are lots of config files for various things (IDE, jest, eslint, etc.) and not all of them supports directory overrides. So project A and B have their own config files at their own directory roots, while config files in project A need to ignore project B's directory. They are also quite different and have very different ESLint rules, for instance.

I'm wondering how the super-linter action could work in a situation like this. Is there a way to specify multiple runs with different parameters for different directories?

**Comment by nvuillam** [comment]
I think you can define 2 linter.yml files

- One with FILTER_REGEX_INCLUDE=(projA) , and its associated configuration
- One with FILTER_REGEX_INCLUDE=(projB), and its associated configuration

**Comment by zkoppert** [comment]
@Zodiase Did that help?
