### ISSUE TITLE
Add PowerShell Support

### ISSUE THREAD

**Issue by kilasuit** [github/super-linter#109]
**Is your feature request related to a problem? Please describe.**
Lack of PowerShell Support

**Describe the solution you'd like**
Add support to include PowerShell's PSScriptAnalzer https://github.com/PowerShell/PSScriptAnalyzer/

**Describe alternatives you've considered**
Running seperate task for this anyway

**Additional context**

**Comment by admiralAwkbar** [comment]
@kilasuit love it... need to find the best way to install PowerShell Core on a Linux image :) without making it just huge lol...
If you have some time to get a PR going would love to take a look and help:) we got a lot of users on PS

**Comment by joeyaiello** [comment]
PM owner for PowerShell here, feel free to reach out in this issue or offline if you have any questions. We have [supported packages](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7) and [Docker containers](https://hub.docker.com/_/microsoft-powershell) across the board, happy to chat if none of it meets your needs.

Similarly, my team supports PSScriptAnalyzer as well, could set up some time with the right devs to chat about how its API gets called from our VS Code extension, for example.

**Comment by michaelsainz** [comment]
Integration of the PSScriptAnalyzer would be ✨ ❤️ 🎉 .

**Comment by JustinGrote** [comment]
I'm working on it at https://github.com/github/super-linter/pull/199

**Comment by zkoppert** [comment]
merged https://github.com/github/super-linter/pull/238
