### ISSUE TITLE
C and CPP support

### ISSUE THREAD

**Issue by patrick-compass** [github/super-linter#1090]
Please support linting of C and CPP files. Embedded programming is still mostly done in C with a little CPP and being able to use your Action on our repos would be awesome.

**Comment by patrick-compass** [comment]
Please triage this issue

**Comment by nvuillam** [comment]
If someone wants to make a PR to embed cpplint in Super-Linter, here is the recipe :) 

-> https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/c.megalinter-descriptor.yml
-> https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/cpp.megalinter-descriptor.yml

cppcheck to come someday :)

**Comment by zkoppert** [comment]
These are definitely desirable languages and we could use some help getting the moving.

**Comment by lumpidu** [comment]
Sorry guys, but why use cpplint if we have clang-tidy ?

The code style supposed by cpplint is very biased (Google style) and complains about things that are not relevant for most projects out there. Yet, it's really difficult to customize it and/or to find customizations that make sense.
There is also no description or template yet [here](https://github.com/github/super-linter/tree/master/TEMPLATES])

In contrast, clang-tidy is used by most IDE's, therefore many have already a customization file that could be used on the CI as well.

**Comment by cooljeanius** [comment]
So, besides cppcheck, another C linter I'd like to see support added for would be splint: https://github.com/splintchecker/splint
Sure, it might be kind of old, and only support C89, but I still find it useful sometimes.
