### ISSUE TITLE
Update wiki with how to add new language

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#1091]
**Is your feature request related to a problem? Please describe.**
The wiki is outdated, specially the https://github.com/github/super-linter/wiki/Adding-new-language-support

**Describe the solution you'd like**
We need to update to help out any newcommenr willing to help with new languages

**Describe alternatives you've considered**
You can extrapolate from it, but is better if we keep it updated.

**Comment by admiralAwkbar** [comment]
@GaboFDC amazing work! You're the people's champ!
