### ISSUE TITLE
Support arguments for Kubeval

### ISSUE THREAD

**Issue by sheeeng** [github/super-linter#1102]
**Is your feature request related to a problem? Please describe.**

As a user, I want super-linter to be able to support arguments for kubeval.

```bash
kubeval --ignore-missing-schemas fixtures/test_crd.yaml
```

See [CRDs](https://www.kubeval.com/#crds)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by ferrarimarco** [comment]
Duplicate #891

**Comment by ferrarimarco** [comment]
Actually, not a duplicate. You can now use `KUBERNETES_KUBEVAL_OPTIONS`. Although, there's #891 that hurts a bit, still.
