### ISSUE TITLE
dockerfilelint scans file with dockerfile anywhere in name

### ISSUE THREAD

**Issue by a16bitsysop** [github/super-linter#1113]
## Describe the bug
If a file is created like .github/workflows/update-dockerfiles.yaml 
hadolint runs on it as if it were a dockerfile causing a failure as it is not a dockerfile

## Expected behavior
hadolint should not run on files that are not called Dockerfile or Dockerfile.Something

## Steps to Reproduce
Listed above

1. Click on '....'
1. Scroll down to '....'
1. See error

**Comment by admiralAwkbar** [comment]
@a16bitsysop  Hey!
This is a good catch!
The code block that does this is:
```bash
elif [[ "${FILE_TYPE}" != "dockerfilelintrc" ]] && [[ "${FILE_TYPE}" != "tap" ]] && [[ "${BASE_FILE}" == *"dockerfile"* ]]; then
      ################################
      # Append the file to the array #
      ################################
      FILE_ARRAY_DOCKERFILE+=("${FILE}")
      FILE_ARRAY_DOCKERFILE_HADOLINT+=("${FILE}")
```
So to allow for users to have `dockerfiles` with updated names the last statement is what makes this not work right for you...
But i can do some additional logic and have this resolved :)
