### ISSUE TITLE
Where am I supposed to put .pylintrc .python-lint etc?

### ISSUE THREAD

**Issue by BoPeng** [github/super-linter#1115]
I have a `.pylintrc` in the home directory of my repository but `super-linter` github action does not honor it. I have tried

1. Add `          PYTHON_PYLINT_CONFIG_FILE: .pylintrc` to `env`
2. Rename a copy of the file to `.github/workflow/.python-lint`

but neither solution works. Where am I supposed to put this file? It appears that I am missing something very obvious but I could not find it from the documentation. Thanks.

Note that locally I can use something like

```
-e PYTHON_PYLINT_CONFIG_FILE=.pylintrc -v $PWD/.pylintrc:/action/lib/.automation/.pylintrc
```
to manually place `.pylintrc` to /action/lib/.automation` but I am not sure how `github` action handles this.
`

**Comment by admiralAwkbar** [comment]
@BoPeng The file shoudl live in the folder path:
- `.github/linters/.python-lint`

That should do it 👍 
Or use the **PYTHON_PYLINT_CONFIG_FILE** env to update it to `.pylintrc`

And then update the file location

Hope this helps!

**Comment by BoPeng** [comment]
Thanks!
