### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by tobiasbueschel** [github/super-linter#115]
Really appreciate the efforts that already went into `super-lint`, it would be great to also add support for Java using perhaps one of the following linters:

- https://github.com/checkstyle/checkstyle
- https://github.com/spotbugs/spotbugs
- https://github.com/pmd/pmd

**Comment by LifeIsStrange** [comment]
Using https://github.com/diffplug/spotless
one could simultaneously and seamlessly supports formatting for Java, Kotlin, scala and SQL :}
I think this is strongly important because Java is more and more used with complementary languages.

**Comment by sirReeall** [comment]
Java linting would be a great addition 👍

**Comment by quackduck** [comment]
Is it known when such language additions will be considered? I'm guessing this is not the priority. What _is_ the priority?

**Comment by zkoppert** [comment]
It looks to me like this is important to many people based on the comments and 👍 here. As far as I am concerned, Java support is ready to work on. We have created some useful information to consider when adding support for new languages like Java on the [wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support).

Anyone who would like to can pick up this work by starting a PR in draft mode and mention this issue. We will be there to help along the way.

**Comment by quackduck** [comment]
I would like to work on this. I'll make a PR when I'm done.

**Comment by quackduck** [comment]
Which linter should I implement? SpotBugs, Spotless, PMD or Checkstyle? Which one?

**Comment by zkoppert** [comment]
Spotless looks like a good one after a quick glance but I'm not a regular Java developer so I would yield to others if they have opinions.

**Comment by zkoppert** [comment]
> I would like to work on this. I'll make a PR when I'm done.

Thank you @quackduck!! ✨ 🎉

**Comment by quackduck** [comment]
I'll work on Spotless, for now, then.

**Comment by LifeIsStrange** [comment]
@quackduck nice to know you're working on it!
Please if possible, make sure to use their "modern" gradle plugin and not the old one.
The modern one should be more optimized ->
https://github.com/diffplug/spotless/issues/600

**Comment by quackduck** [comment]
Sorry for taking so much time to get back to this

I made a [PR](https://github.com/github/super-linter/pull/459) - #459

I'm not sure how I should continue. I've never used Gradle or Docker. If I'm not mistaken, the PR wouldn't work because we haven't given Docker a command to install Spotless, right?

**Comment by LifeIsStrange** [comment]
@quackduck I'm a noob at docker so I cannot really help you :/
Maybe that you could take inspiration from the PR for Kotlin? 
https://github.com/github/super-linter/pull/246
@admiralAwkbar
@Kim1Jun
You might give some hints and be interested as it would allow Kotlin Klint support through spotless which would be a more modern gradle integration and allow things beyond what Ktlint can do and enable better Java interop.

**Comment by quackduck** [comment]
Thanks! I’ll have a look. I don’t know Gradle though. Lemme see what I can learn from #246

**Comment by quackduck** [comment]
#246 just curled a binary for installation. We could do that but we wouldn't get a binary for Spotless.

Anyone who uses Gradle or knows how I can add Spotless feel free to make suggestions (Is it possible to have 2 contributors in a PR? If so, we could do that)

**Comment by sirReeall** [comment]
@quackduck let me have look see

**Comment by sirReeall** [comment]
I should state that I've never used spotless before, but I can help with the docker part.

#246 is a good example of a linter that you can run at the [command line](https://github.com/pinterest/ktlint#installation). That makes the install and running pretty easy inside the docker container. Which is why you see the curl for download and the command to run the linting [here ](https://github.com/github/super-linter/commit/6452f93b3238dc0049582f747468346e7dbbf29d#diff-2b006ea0cfcfac29e33a1b9eef9974c1R2504)is a simple command

Spotless seem to be only available within gradle or maven. Which adds a bit of complexity as you need to have gradle or maven installed inside the container, then you would clone the git repo for spotless, then you would need to have a configuration file with the require settings to run the linter locally. Spotless have a high level document on running locally [here](https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md#integration-testing)

**Comment by sirReeall** [comment]
Just to add doesn't seem like [running Spotless without gradle/ maven](https://github.com/diffplug/spotless/issues/268) would be possible

**Comment by quackduck** [comment]
So what do you think I should do? I have no experience with Gradle, Maven or Docker 😐

Do you need Gradle or Maven to be able to help with the Docker part?

**Comment by sirReeall** [comment]
I had a quick look at [PMD ](https://pmd.github.io/)and [Checkstyle](https://checkstyle.org/cmdline.html), both these have options to run from the command line

**Comment by quackduck** [comment]
Done! I gave you access.

**Comment by admiralAwkbar** [comment]
@quackduck @sirReeall awesome work here. Let me know when it gets closer so i can poke around and see fi i can help :)

**Comment by sirReeall** [comment]
Ended up with checkstyle as it give you Sun Code Conventions and Google Java Style OOTB.

@quackduck Have a look at my commit [here](https://github.com/quackduck/super-linter/commit/91eb58e61aa630fd0f8cbdc294129bf92290c3b6). 

It has some magic in the command to make sure the latest release is pulled into the image.

Tested this on a local image and I can run `java -jar /usr/bin/checksytle.jar` to fire it up.

This will need plumbing into super-linter's code now. Let me know if you need any help with that

**Comment by sirReeall** [comment]
@quackduck how's it going? Did you need any help with this?

**Comment by quackduck** [comment]
What do you mean by plumbing? By the way, have a look at my new commit

**Comment by sirReeall** [comment]
looks good, made one [small adjustment](f9e2e5a) to the LINTER_CMD as you must specify rules that you will use

**Comment by quackduck** [comment]
Is that it then?

**Comment by quackduck** [comment]
Noob question:
How do I add "badges" (that's what they're called right?) to my PR? Like the stuff that says enhancement and all that

**Comment by IAmHughes** [comment]
> How do I add "labels" to my PR? Like the stuff that says enhancement and all that

On an Issue or Pull Request, these are called labels. This is the relevant [documentation](https://docs.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests).

You need to have write access to the repository however, so only maintainers can apply labels to issues and PRs in their repo.

If you try in a personal repository or one you have write access to, you should see the option to on the right side of the screen.

**Comment by quackduck** [comment]
Oh okay. Thanks!
