### ISSUE TITLE
Auto linting option

### ISSUE THREAD

**Issue by jamesgeddes** [github/super-linter#1158]
It would be good to have the option to automatically apply the identified changes so that people don't have to go through them manually. This is already possible with [black](https://github.com/psf/black/actions/runs/17913292/workflow) and I guess everything else would be similar.

I have tried to do this with super-linter but can't seem to get it working. Apologies in advance if I'm PEBKACing.

**Comment by GaboFDC** [comment]
This is actually really big to accomplish.
Super linter would need to pass the flag to each linter, that supports the auto fix.
Then it would need to commit and push those changes into the branch.
That may also cause a cyclic action, where the action pushes changes, it triggers the action again, and it pushes changes again.
I don't what other maintainers think about this, but is nothing trivial.

**Comment by jamesgeddes** [comment]
We are going to give [mega-linter](https://nvuillam.github.io/mega-linter/) a go. Seems pretty good.

**Comment by nvuillam** [comment]
@GaboFDC it's one of the first things I did after the fork to Mega-Linter... about the cyclic change, once you applied fixes from a linter, at the next run the same linter won't make another fix ^^
I never had such issues in all the stuff I had to solve ... :p
What was tricky was to analyze all linters to know which parameters to send (it's not always --fix, or sometime you have to change other arguments, like remove --check for formatters), but if you wanna apply it to Super-Linter, you just have to browse [Mega-Linter descriptor files](https://github.com/nvuillam/mega-linter/tree/master/megalinter/descriptors) :)
