### ISSUE TITLE
Lint for unequal phrasing

### ISSUE THREAD

**Issue by zkoppert** [github/super-linter#116]
**Is your feature request related to a problem? Please describe.**
I'd like to see default linter settings that scan code for problematic words like 'master' that cause harm and silence black voices. request from https://news.ycombinator.com/item?id=23563823#23564249

**Describe the solution you'd like**
Please consider adding https://alexjs.com/

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by wooorm** [comment]
As the maintainer of alex, I would suggest caution in turning it on for everyone. (Changing) language is a delicate problem, and the tool isn’t very delicate

**Comment by Hanse00** [comment]
I like the idea here, but I think we need to make sure we've thought the approach through. It's going to be important we get it right.

**Comment by zkoppert** [comment]
Closing for lack of traction.
