### ISSUE TITLE
Configuring for non-standard filenames?

### ISSUE THREAD

**Issue by fluxsauce** [github/super-linter#117]
Hi there, this is a fantastic project!

We've got a use case where we have a repository that contains a number of JSON files that are named `.properties`. While I understand it's best practice to have semantically meaningful file extensions, it's what we have for now.

Is it possible to configure `jsonlint` (and possibly others) to specify file extensions to validate?

Thanks!

**Comment by fluxsauce** [comment]
That would work!

IMHO it'd be optimal of the custom mapping overrode the defaults rather than merged to avoid unexpected behavior.

**Comment by admiralAwkbar** [comment]
@fluxsauce so if the value is set in the `mapping.yml` let's say for example as above, then I wouldn't look for `.json` but only `.properties` and `.config`?

Interesting idea, I guess if the users wanted to add tags, the could easily add `.json` to the list as well. right?

**Comment by fluxsauce** [comment]
That'd be my opinion, otherwise I could anticipate someone asking for a way to exclude a tag; by overriding it gives optional granular control to the end user through one interface.

Not a deal breaker for me either way :-)

**Comment by zkoppert** [comment]
I think that overriding the defaults is okay and it is consistent with our env config stragey of being explicit about what you want to occur. I would support that direction.

**Comment by zkoppert** [comment]
@fluxsauce Are you still interested in this? Would you be willing to get things started with a PR to implement a mapping file?
