### ISSUE TITLE
Flake8 support

### ISSUE THREAD

**Issue by aniforprez** [github/super-linter#123]
**Is your feature request related to a problem? Please describe.**
I prefer flake8 over pylint and would love flake8 support for Python3 linting

**Describe the solution you'd like**
Flake8 support

**Additional context**
Documentation here: https://flake8.pycqa.org/en/latest/

**Comment by artob** [comment]
Changing the Python linter default from Pylint to Flake8 would indeed be a welcome improvement. Having just set up the Super-Linter to lint several of my Python projects, I am reminded why I haven't been using Pylint: the annoying number of false positives. As it stands, the Super-Linter is pretty useless for Python projects.

From a quantitative analysis of the problem at https://lukeplant.me.uk/blog/posts/pylint-false-positives/

> The Good:Bad ratio here is very low in my book. If Pylint was a co-worker doing code review, I’d be praying for him to leave
>
> To fix the false positives you could silence the entire class of errors (which increasingly makes using Pylint pointless), or add special comments to your code individually. I’m reluctant to do the latter: [...]
>
> With these figures, I feel my previous estimates about the usefulness of Pylint (in the context of a code base where I’m already using flake8) were about right. The false positive rate would have to be massively reduced for me to consider using it.
>
> In addition to the time and visual noise needed to deal with false positives, I would be reluctant to add something like this to a project because of the problem that junior devs may take a more slavish approach to keeping Pylint happy. This could result in them breaking working code because they didn’t understand that Pylint had got it wrong, or doing big code refactors just to enable Pylint to understand the code.

**Comment by aniforprez** [comment]
Yes I agree with @artob. I find pylint to be utterly useless since to have it have any level of usefulness one needs to heavily configure the rules and manually weed out all the false positives as one discovers them over a rather large time frame. Flake8 on the other hand is MUCH more sensible with reasonable defaults that require minimal configuration and babysitting

**Comment by artob** [comment]
The sheer number of [Flake8 actions on the Marketplace](https://github.com/marketplace?type=actions&query=flake8) is also a useful indication of the demand for this, and shows the value that the Super-Linter could bring to the table here by not making us all have to choose from a long list such as:

- https://github.com/marketplace/actions/flake8-action
- https://github.com/marketplace/actions/run-flake8-on-your-pr-with-annotations
- https://github.com/marketplace/actions/github-action-for-flake8
- https://github.com/marketplace/actions/lintly-flake8
- https://github.com/marketplace/actions/flake8-with-annotations
- https://github.com/marketplace/actions/python-flake8
- https://github.com/marketplace/actions/flake8-annotator
- https://github.com/marketplace/actions/flake8-check-action
- https://github.com/marketplace/actions/python-flake8-lint
- https://github.com/marketplace/actions/flake8-with-args
- etc...

At the time of my writing, the aforementioned Flake8 actions have a combined ⭐ 95 stars.

By comparison, the number of [Pylint actions on the Marketplace](https://github.com/marketplace?type=actions&query=pylint) is a third of that, with a combined ⭐ 26 stars.

**Comment by GaboFDC** [comment]
Giving this a go, will be a large change in order to allow pylint and flake, like we do for eslint and standard in JS

**Comment by aniforprez** [comment]
Dope work!
