### ISSUE TITLE
provide github URL to download current default template

### ISSUE THREAD

**Issue by maxheld83** [github/super-linter#1231]
**Is your feature request related to a problem? Please describe.**

It's currently hard to programmatically enable the super-linter by adding the requisite `linter.yaml`.

I either have to
- parse the `README.md`
- ~~copy/paste~~ (that's not programmatic)

**Describe the solution you'd like**

If the currently recommended default `linter.yaml` existed in its own file in some path in the repo, I could just `curl` it or whatever.

**Comment by bajlamut** [comment]
## - - - - - - - []()@****__````
```

```
````__****

**Comment by admiralAwkbar** [comment]
@maxheld83 Nice idea

Adding it now
