### ISSUE TITLE
Consume `.eslintrc` instead of defining `.eslintrc.yml`?

### ISSUE THREAD

**Issue by tihuan** [github/super-linter#124]
**Is your feature request related to a problem? Please describe.**
Really love the super linter! My concern so far is creating a `.github/linters/.eslintrc.yml` when `.eslintrc` already has all of our project's custom rules and configs

**Describe the solution you'd like**
Just wondering if it'd make sense to preserve a single source of truth by allowing super linter to consume `.eslintrc` instead of defining the same custom rules in `.github/linters/.eslintrc.yml`

**Describe alternatives you've considered**
Maybe a build step script to translate `.eslintrc` rules into `.github/linters/.eslintrc.yml` as a temp solution?

Thank you for your consideration!

**Comment by fafnirical** [comment]
`.eslintrc` is deprecated, but if multiple configuration formats were to supported it could be good to support them all: https://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by tihuan** [comment]
@fafnirical Thanks for pointing that out!

Sounds like we could have two requests here?

1. Make Super Linter consume a project's existing lint rule file, so we don't have to duplicate rules in `.github/linters/.eslintrc.yml`, doubling the maintenance cost and losing single source of truth

2. Make Super Linter support all formats specified in https://eslint.org/docs/user-guide/configuring#configuration-file-formats

Does that sound right to you?

Thanks!

**Comment by GaboFDC** [comment]
@tihuan i think is is solved now, can you check?

**Comment by tihuan** [comment]
Hi @GaboFDC !

Thanks so much for pinging! Yes, I see that both requests proposed [here](https://github.com/github/super-linter/issues/124#issuecomment-646241087) are now resolved 🙏 Really appreciate the warp speed development here! 

https://github.com/github/super-linter/commit/70f51ccd8fafdd647fa7846f8197efe0379100e9
https://github.com/github/super-linter/pull/167/files

Closing!
