### ISSUE TITLE
transfer Docker image from admiralawkbar to github

### ISSUE THREAD

**Issue by zkoppert** [github/super-linter#125]
**Describe the bug**
transfer Docker image from admiralawkbar to github

**To Reproduce**
none

**Expected behavior**
github is the more official place so can we post the docker image there?

**Screenshots**
https://github.com/github/super-linter/blob/3569fc0407685cc8a29c815a02898607938c9b02/.github/workflows/deploy-PROD.yml#L48

**Additional context**
Need to get permission and update creds to deploy there.

**Comment by admiralAwkbar** [comment]
@zkoppert I agree it needs to be moved when we get some access to push to GitHub

![](https://media.giphy.com/media/102Kt6jnALRaV2/giphy.gif)

**Comment by zkoppert** [comment]
closed by https://github.com/github/super-linter/pull/137
