### ISSUE TITLE
Consider upgrading to Trivy Github Action for vulnerability scanning

### ISSUE THREAD

**Issue by simar7** [github/super-linter#1265]
Hi 👋🏼 – I'm one of the maintainers of Trivy and Trivy GitHub Action and I have the following suggestion:

**Is your feature request related to a problem? Please describe.**
It looks like today super-linter has a custom script to scan for vulnerabilities with Trivy
https://github.com/github/super-linter/blob/f82e649a2e3aefb29291885d986bd796034ad1d7/.automation/trivy-security-scan.sh

Recently we released a new version of Trivy Github Action which can also scan for vulnerabilities within repos as well: https://github.com/aquasecurity/trivy-action/releases/tag/0.0.9

**Describe the solution you'd like**
Instead of having the above shell script, it is possible to run Trivy Github Action natively with the appropriate commands. 

Here's an example of it: https://github.com/aquasecurity/trivy-action#using-trivy-to-scan-your-git-repo instead of currently doing the following https://github.com/github/super-linter/blob/f82e649a2e3aefb29291885d986bd796034ad1d7/.github/workflows/trivy.yml#L26-L49

**Additional context**
Thanks to @knqyf263 for his input and insight into this.

**Comment by admiralAwkbar** [comment]
@simar7 Hey thanks for the open issue!

I tried to use the GitHub Action, but it seems to always fail and timeout...

Any chance you can open a pr and see if we can get it to work?

thanks!

We would love to use the full action and not a homemade script

**Comment by knqyf263** [comment]
Hi @admiralAwkbar, I've opened https://github.com/github/super-linter/pull/1355.

It works in my fork.
https://github.com/knqyf263/super-linter/runs/2083537101?check_suite_focus=true
