### ISSUE TITLE
SQL Support

### ISSUE THREAD

**Issue by thehesiod** [github/super-linter#128]
we have a lot of SQL in our codebase and would be nice to lint these as well.

not sure which linter would be the best

**Comment by LifeIsStrange** [comment]
In https://github.com/github/super-linter/issues/115
I mentioned https://github.com/diffplug/spotless
which would allow to solve simultaneously Java, Kotlin, Scala, Groovy and SQL support in a unified way.
For SQL it would use https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/sql/DBeaverSQLFormatterStep.java
so from this tool 
https://github.com/dbeaver/dbeaver/wiki/SQL-Formatting

**Comment by jars** [comment]
Also check out: https://github.com/alanmcruickshank/sqlfluff

**Comment by LowlyDBA** [comment]
Bump to prevent stake issue tagging.
