### ISSUE TITLE
Ruby: Switch from RuboCop to StandardRB

### ISSUE THREAD

**Issue by krtschmr** [github/super-linter#1318]
As already suggested in https://github.com/github/super-linter/issues/188, Standard.rb now finally got released in version 1.0 which is a great milestone for the ruby community and thus integrating it should be at least reconsidered.

**Comment by krtschmr** [comment]
lmao github

**Comment by GaboFDC** [comment]
Sorry, we have an automation that is not working properly.

About stadard.rb instead of switch, we could add it as an extra linter.
Any PRs with this improvement are highly welcomed.

**Comment by brandoncc** [comment]
I would love to see this happen!
