### ISSUE TITLE
Link the linters used in the README?

### ISSUE THREAD

**Issue by pronoiac** [github/super-linter#132]
I note the linters used are all linked on [the "disabling linters" page,](https://github.com/github/super-linter/blob/master/docs/disabling-linters.md) and think they should also be linked in the main README. 
While adjusting that table, I'd consider sorting the languages alphabetically, and aligning the columns.

**Comment by zkoppert** [comment]
Yes! This is a good idea.

**Comment by admiralAwkbar** [comment]
@pronoiac great idea! want to open a PR with it?

**Comment by pronoiac** [comment]
@admiralAwkbar Sure thing!
