### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by ribtoks** [github/super-linter#135]
**Is your feature request related to a problem? Please describe.**

`super-linter` does not support C++

**Describe the solution you'd like**

Use `super-linter` to lint C++ code

**Describe alternatives you've considered**

Running `clang-tidy` and `clazy` yourself through custom run steps

**Comment by Resurr3ction** [comment]
Few notes about using clang-tidy (that I fully support):

- One requirement of the clang-tidy is that it needs compilation database (to work out all the includes). Therefore C++ super-linter might require a bit more setting up than for other languages. 
- The code must be actually compilable with Clang. That is often not the case if the given source code targets for example only Windows and use MSVC only.
- Coming up with sensible defualt .clang-tidy will be a challenge but it might also be a requirement for setting C++ super-linter up to have it. The default however would be useful and make it more easy and accessible.

An alternative to clang-tidy might be cppcheck, but that comes with its own parser (not very good one, lack of tempalte support etc.) and much smaller scope of checks than clang-tidy.

**Comment by orbitcowboy** [comment]
Please add support for Cppcheck as well

**Comment by peternewman** [comment]
And cpplint please

**Comment by ribtoks** [comment]
Not stale

**Comment by WSLUser** [comment]
This would help a great deal for MS projects like Windows Terminal. You'd think this would get some kind of feedback from a maintainer.

**Comment by ribtoks** [comment]
Not stale

**Comment by WSLUser** [comment]
Still pending

**Comment by orbitcowboy** [comment]
Not stale

**Comment by diega** [comment]
Not stale

**Comment by zkoppert** [comment]
Hey all, popular issue here anyone able to support development on this?

**Comment by GoetzGoerisch** [comment]
Just for clarification, `cpplint` is already included, but I found not possibility to configure it?

**Comment by laurynas-biveinis** [comment]
@GoetzGoerisch, while super-linter-level configuration indeed seems to be absent at the moment, you can configure cpplint through a `CPPLINT.cfg` file in your source repo.

**Comment by GoetzGoerisch** [comment]
@laurynas-biveinis Thank you for the help. Works for me.

**Comment by zkoppert** [comment]
completed via #1492

**Comment by orbitcowboy** [comment]
> completed via #1492

Did you add Cppcheck support as well?

**Comment by cooljeanius** [comment]
> > completed via #1492
> 
> Did you add Cppcheck support as well?

doesn't look like it, according to the README...
