### ISSUE TITLE
CloudFormation support

### ISSUE THREAD

**Issue by PatMyron** [github/super-linter#136]
[CloudFormation Linter](https://github.com/aws-cloudformation/cfn-python-lint/)

[CloudFormation template recognition logic](https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/ec7ab4af616cf85c18f93918cdeeaa11da2fbe72/server/src/server.ts#L140) if needed

**Comment by guikcd** [comment]
I've started to work on this on my fork [here](https://github.com/guikcd/super-linter/tree/cfn-lint).
Please note that it is WIP :)
