### ISSUE TITLE
Failed to get Diff

### ISSUE THREAD

**Issue by dshevtsov** [github/super-linter#1397]
## Describe the bug

The SuperLinter checks started to fail since yesterday with a message of the following kind:
```
fatal: Invalid symmetric difference expression master...a5b0bbf7126dc130ee823f60f78b4cae6d4f5f4d
2021-03-23 15:32:48 [INFO]   Failed to get Diff with:[git -C /github/workspace diff --name-only master...a5b0bbf7126dc130ee823f60f78b4cae6d4f5f4d --diff-filter=d]
```

Examples from different repositories:
- https://github.com/magento/devdocs/pull/8828/checks?check_run_id=2176584570#step:4:62
- https://github.com/magento/merchdocs/pull/1100/checks?check_run_id=2175097376#step:4:62

## Expected behavior

The check does not fail unexpectedly.

## Steps to Reproduce

Examples from different repositories:
- https://github.com/magento/devdocs/pull/8828/checks?check_run_id=2176584570#step:4:62
- https://github.com/magento/merchdocs/pull/1100/checks?check_run_id=2175097376#step:4:62

## Logs

```
fatal: Invalid symmetric difference expression master...a5b0bbf7126dc130ee823f60f78b4cae6d4f5f4d
2021-03-23 15:32:48 [INFO]   Failed to get Diff with:[git -C /github/workspace diff --name-only master...a5b0bbf7126dc130ee823f60f78b4cae6d4f5f4d --diff-filter=d]
```

## Additional context

The repositories use the latest version 3. I tried with v3.15.3, it fails with the same fatal.

**Comment by karlism** [comment]
We are also experiencing this issue:
https://github.com/lest/prometheus-rpm/pull/366/checks?check_run_id=2177570818

**Comment by KineticTheory** [comment]
We are also seeing this: https://github.com/lanl/Draco/pull/1043/checks?check_run_id=2178877849

**Comment by dshevtsov** [comment]
I resolved the issue by adding `fetch-depth: 0` to the workflow like in the [example](https://github.com/github/super-linter#example-connecting-github-action-workflow).

**Comment by karlism** [comment]
> I resolved the issue by adding `fetch-depth: 0` to the workflow like in the [example](https://github.com/github/super-linter#example-connecting-github-action-workflow).

This has fixed linting issues in our repository too.
