### ISSUE TITLE
Add support to rubocop-rails

### ISSUE THREAD

**Issue by Nittarab** [github/super-linter#1408]
**Is your feature request related to a problem? Please describe.**
I get this error:
```
2021-03-26 23:26:54 [ERROR]   Found errors in [rubocop] linter!
2021-03-26 23:26:54 [ERROR]   Error code: 1. Command output:
------
Inspecting 1 file
W

Offenses:

app/models/school/contact/type.rb:15:3: W: [Correctable] Lint/RedundantCopDisableDirective: Unnecessary disabling of Rails/UniqueValidationWithoutIndex.
  # rubocop:disable  Rails/UniqueValidationWithoutIndex
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```
If I fun rubocop locally I didn't get this error.

In my rubocop file I require 2 rubocop extension:
```
require:
  - rubocop-rails
  - rubocop-performance
```

**Describe the solution you'd like**
Can I add a step to install these gems?

**Comment by GaboFDC** [comment]
rubocop rails and performance are already installed on https://github.com/github/super-linter/blob/master/dependencies/Gemfile
Please check your local linter version, and other possible configs that may be making the local linter pass.

**Comment by Nittarab** [comment]
Thanks, @GaboFDC, you are right. I'm using rubocop-rails to v2.9.x 

https://github.com/rubocop/rubocop-rails/blob/master/CHANGELOG.md#bug-fixes-2
