### ISSUE TITLE
Stylelint support

### ISSUE THREAD

**Issue by antleblanc** [github/super-linter#142]
**Is your feature request related to a problem? Please describe.**
`super-linter` does not support [stylelint](https://stylelint.io/).

**Describe the solution you'd like**
Use `super-linter` to lint styles files.

**Describe alternatives you've considered**
Running `stylelint` yourself through custom run steps.

**Comment by StalkAltan** [comment]
Hi @antleblanc!

I PRed this fix and it has been merged in #185. It only supports the base CSS linting, but someone else could take a look at my PR and easily add SCSS support if they needed it.
