### ISSUE TITLE
Extra Semicolon Error For Javascript Lint

### ISSUE THREAD

**Issue by shubsaini09** [github/super-linter#1427]
Hi,

While trying to explore Github actions with super-linter, I got into a unresolvable issue. Everything seems to be working fine except below error. What is the issue? Could you please help? 

![image](https://user-images.githubusercontent.com/12813253/113509344-ae6b2580-9572-11eb-833a-6b9eb3093a35.png)

Note: If I use my own custom .eslintrc.json file then this error does not come. Below is my file:

```
{
    "env": {
        "commonjs": true,
        "es2021": true,
        "node": true
    },
    "extends": "airbnb",
    "parserOptions": {
        "ecmaVersion": 12
    },
    "rules": {
        "linebreak-style": 0,
        "no-console": 0
    }
}
```
Code: 

```
const crypto = require('crypto');

const mykey = crypto.createCipheriv('aes-128-cbc', '1234512345123451', '1234512345123451');
let mystr = mykey.update('SFDCESBBILLINGFREQUENCY', 'utf8', 'hex');
mystr += mykey.final('hex');

console.log(mystr);

const mykey1 = crypto.createDecipheriv('aes-128-cbc', '1234512345123451', '1234512345123451');
let mystr1 = mykey1.update(mystr, 'hex', 'utf8');
mystr1 += mykey1.final('utf8');

console.log(mystr1);
```

**Comment by zkoppert** [comment]
Semi-colons in javascript are not required and the standardjs linter would prefer that they are removed. It looks like your `.eslintrc.json` file is overriding the default in the linter which complains about them. See more about that at https://standardjs.com/rules.html#semicolons

For any specific questions about that linters functionality you can open an issue at https://github.com/standard/standard/issues .

Hope that helps!
