### ISSUE TITLE
Invoking golangci-lint run on individual files breaks linters in packages.

### ISSUE THREAD

**Issue by RussellRollins** [github/super-linter#143]
**Describe the bug**
When golangci-lint is invoked against a single file, as it is here:

https://github.com/github/super-linter/blob/1e08ff6363cb45c5714b1c30039d896972287173/lib/linter.sh#L1939

This fails to properly lint a package if types are defined in another file.

**To Reproduce**
1. Create two Go files, main.go and foo.go.
2. Define `Foo` in foo.go.
3. Run `golangci-lint run` in that package, it lints fine.
4. Run the super-linter against that package, it fails to lint with: `ERROR:[level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/github/workspace/main.go:8:8: undeclared name: Foo]"` 

See an example run here: https://github.com/RussellRollins/super-lint-error/runs/785695971

**Expected behavior**
This passes linting without failures.

**Screenshots**
![Screen Shot 2020-06-18 at 3 34 24 PM](https://user-images.githubusercontent.com/3237030/85064207-35344a80-b179-11ea-9811-81972b08250a.png)

**Additional context**
I can see how the current solution is used to enable the "lint only changed files" feature, but this will fall down for relatively simple Go setups.

**Comment by bznein** [comment]
We encountered the same issue and this makes SuperLinter with Golang basically unusable.
An option to run the linter on whole directories when `VALIDATE_ALL_CODEBASE ` is True would be extremely helpful

**Comment by bznein** [comment]
Hi @RussellRollins, I created a PR #370 which aims at fixing this issue. The owners of the repo want to gather some more feedback from other GO developer. If you have some time to spare can you have a look at it and leave your opinion there? Thanks!

**Comment by iggy** [comment]
Slow your roll bot. This is still valid.

Sorry for the noise. Trying to keep this from getting closed.

**Comment by pwmcintyre** [comment]
still valid; super-linter is totally broken for golang :(

**Comment by jtbonhomme** [comment]
Still valid!

**Comment by WendelHime** [comment]
still valid

**Comment by GaboFDC** [comment]
Related to #888

**Comment by karolistamutis** [comment]
What would be the workaround besides disabling Super-Linter completely for go? Having the same issue.

**Comment by masih** [comment]
Not stale

**Comment by WendelHime** [comment]
not stale

**Comment by bznein** [comment]
not stale

**Comment by RussellRollins** [comment]
not stale, although at this point I'm just going to unsubscribe from the issue.

Best of luck to anyone who still cares about this.

**Comment by develerik** [comment]
not stale

**Comment by bznein** [comment]
still not stale, but whatever, doesn't look like it will get any attention

**Comment by Tatsinnit** [comment]
not stale

**Comment by Tuxdude** [comment]
This issue is still very much relevant for any medium or higher sized `go` project which would be splitting the code base across multiple go files. `super-liner` is pretty much useless for `go` in such projects if it is going to be so noisy.

**Comment by bznein** [comment]
> This issue is still very much relevant for any medium or higher sized `go` project which would be splitting the code base across multiple go files. `super-liner` is pretty much useless for `go` in such projects if it is going to be so noisy.

Yeah I ended up dropping it from any go project :(

**Comment by Tuxdude** [comment]
> > This issue is still very much relevant for any medium or higher sized `go` project which would be splitting the code base across multiple go files. `super-liner` is pretty much useless for `go` in such projects if it is going to be so noisy.
> 
> Yeah I ended up dropping it from any go project :(

I ended up doing very much the same thing and configured the `golangci-lint` github action.
