### ISSUE TITLE
Elisp Support

### ISSUE THREAD

**Issue by ericdallo** [github/super-linter#144]
**Is your feature request related to a problem? Please describe.**
 
`super-linter` does not support Emacs lisp (elisp)
 
**Describe the solution you'd like**
 
Use `super-linter` to lint Emacs lisp (elisp) code
 
**Describe alternatives you've considered**
 
Byte compiling and/or checkdoc with Emacs. 
Example of a GH Action: https://github.com/emacs-lsp/lsp-mode/blob/master/.github/workflows/test.yml.

**Comment by ericdallo** [comment]
I'm still interested in that...

**Comment by admiralAwkbar** [comment]
@ericdallo if you can make a PR against the super-linter to help get this added, I would be glad to help get it across the finish line:)

**Comment by ericdallo** [comment]
Thank you @admiralAwkbar, I started a draft PR here: https://github.com/github/super-linter/pull/530 but I'm stuck not being able to install emacs on the docker image correctly:
![image](https://user-images.githubusercontent.com/7820865/89593306-2b4bd100-d825-11ea-92a4-6908d73749ce.png)
I also found this: https://github.com/cask/cask/issues/471

**Comment by akirak** [comment]
Hello, I am currently working on [elinter](https://github.com/akirak/elinter/), which can be a solution to this issue.

It is still in alpha, but I've implemented its basic features. Now I'm starting to apply it to existing projects to test its functionality. If it works, I will start working on integrating it with `super-linter`.

One question: `elinter` depends on [the Nix package manager](https://nixos.org/nix/). Can I install it into the Docker container, or is there any other integration that uses it?

**Comment by ericdallo** [comment]
Nice @akirak, I think you can install on the docker image like many other linters are doing that (and I think nix should be used from other linters in the future too)

**Comment by akirak** [comment]
Sorry, I won't work on this issue soon. I don't mind if it's closed for now, and it can be reopened later. If someone else would implement it, please go ahead.

**Comment by akirak** [comment]
In [elinter-demo](https://github.com/akirak/elinter-demo), I randomly pick a package from top 25% ones on MELPA every day and run lint on it, and [no package has ever passed the checks](https://github.com/akirak/elinter-demo/actions?query=workflow%3A%22Random%22). Maybe you'll want to discuss which checks are essential.

**Comment by tarsius** [comment]
Lalalala.
