### ISSUE TITLE
Refactoring superlinter to use a more powerful language

### ISSUE THREAD

**Issue by xibz** [github/super-linter#1442]
So, I've been debugging a problem I've had with superlinter and came across an abundance of bash. While I think bash is a perfectly fine language for smaller tasks, and simple problems, I believe superlinter has grown to a more complex application where a more powerful language is needed. The benefit of using a more powerful language is the proper design patterns could be used to make the code more readable, maintainable, and extensible. **And most importantly, is it can be tested!!!** Which will help prevent bugs in the future.

If this is something to be considered, I think the choice of either python or golang would be perfect. Python is a pretty good choice as you guys already have a dependency on that in the Dockerfile. However, being a go nut, I think the fast compile times and being another popular languages for CLIs makes golang a strong candidate.

I've already started working on this in a fork that is porting parts of superlinter to call a go CLI but I am more than happy to change languages if the community is for something different. Here's my line of thinking for the basic architecture

```go
type Linter interface {
    Lint(string) error
}

var linters = map[Language]Linter{
    languageFoo: NewFooLinter(),
}

func AddLinter(language Language, linter Linter) {
    linters[language] = linter
}
```

This makes all language logic self contained. I noticed in the bash files, there are references for different languages everywhere with a lot of complicated if statements. This also allows for linters to be more finely tuned and self contained.

Then for the get the list of files to be linted, we can the github API to retrieve that information

```go
type FileLister interface {
    ListFiles() (map[Language][]string, error)
}

type GitHubFileLister struct {}

func (lister GitHubFileLister) ListFiles() (map[Language][]string, error) {
    // implement logic
}
```

Of course, there's more to be architected here, but I think this is a good starting point. Is this something you'd want? If so, I wouldn't mind contributing as I have already started to port the bash over to golang.

**Comment by nvuillam** [comment]
@xibz been there ^^

https://github.com/github/super-linter/pull/791

Please join [Mega-Linter](https://github.com/nvuillam/mega-linter/) project if you are fluent in Python ( or even if you are not ^^ )

**Comment by zkoppert** [comment]
Hi @xibz, Thanks for the input on the architecture. We definitely understand that `bash` isn't a first choice for everyone but it is for the maintainers of this project. Feel free to fork (like it sounds you have 😄) or use the code as allowed by our [`LICENSE.md`](https://github.com/github/super-linter/blob/master/LICENSE)
