### ISSUE TITLE
Can superlinter be locally set to fix what it finds if possible when run on the command line

### ISSUE THREAD

**Issue by hepcat72** [github/super-linter#1456]
E.g.: black & isort.

I understand if it may be problematic in an editor to have superlinter's run of black & isort have side-effects, but if run on the command line, is there like an environment variable that can be set to have it do what it can with linters that offer auto-fixes?

**Comment by zkoppert** [comment]
👋🏻 Hi @hepcat72, personally I push my commits up to GitHub and use GitHub Actions to run the super linter but I see where you are coming from about running the linters sooner and wanting the auto fix capabilities where available. 

Take a look at how to run the super-linter locally [here](https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md) to be able to see if there are any linter issues locally. Then in terms of autofix, I normally download those tools with auto fix myself but you might be able to modify the docker container to do this.

Hope that helps!

**Comment by nvuillam** [comment]
You can also use github super-linter's little brother Mega-linter, who can apply fixes locally or even from CI with a new commit :)
