### ISSUE TITLE
Multistage Docker build

### ISSUE THREAD

**Issue by zkoppert** [github/super-linter#1458]
## Describe the bug

Builds are huge and slow

## Expected behavior

Builds should be 🚀 fast and 🐜 small. Using multistage builds could speed things up.

## Steps to Reproduce

`docker build` or downloading the latest image

## Logs

takes `1m 18s` to download image
https://github.com/github/super-linter/runs/2371468980?check_suite_focus=true

## Additional context

This would likely require a fair amount of work on the Dockerfile and the build process. We would need to go through the image layer by layer and pull in only the libs we truly need. This could greatly pull down the size of the image as well but will require deep Docker knowledge and extensive testing...

cc/ @admiralAwkbar @clemenko

**Comment by clemenko** [comment]
notes from 

- Add a new final image stage that pulls JUST the binaries and only has the packages needed. ie `FROM alpine as final`
- work to limit layers
- do NOT include PIP/NPM  in the final
- leverage less, bigger layers with `&& \`

**Comment by zkoppert** [comment]
Thanks @clemenko! Starting a draft PR here so I can make those changes we discussed. I will switch it over to a real (non-draft) pull request when its ready for review.

**Comment by ferrarimarco** [comment]
Thanks! This is going to be really useful!
