### ISSUE TITLE
Ability to run Prettier on JSON files

### ISSUE THREAD

**Issue by alanhamlett** [github/super-linter#1460]
**Is your feature request related to a problem? Please describe.**
Switching `JAVASCRIPT_DEFAULT_STYLE` from `standard` to `prettier` only runs on glob of JavaScript files. I want to also run it on JSON files.

**Describe the solution you'd like**
One of two solutions:
1. When `JAVASCRIPT_DEFAULT_STYLE` is `prettier`, include JSON files in the glob of files when linting JavaScript
2. Or, add a new JSON linter option to enable `prettier` on JSON files

**Comment by admiralAwkbar** [comment]
@alanhamlett 
Hey!

Would this cause linter issues with just other `json` files in a repository?
Or would it just be validating the `json` and not adding a `javascript` style pass to files that should not be parsed?

If its just validating the `json` for validity, then I see no real issue why it shouldn't :)

**Comment by alanhamlett** [comment]
I think it should have the ability to do both, validate JSON and format `*.json` files with Prettier. I like to run Prettier on some JSON files to make them human readable and nicely formatted.
