### ISSUE TITLE
Which version of CheckStyle is used?

### ISSUE THREAD

**Issue by nanthony21** [github/super-linter#1467]
I'm trying to set up linting for a Java project. I couldn't find it documented but based on old issues it looks like the way to specify custom linting rules for java is to put them in `.github/linters/sun_checks.xml`

I copied the Google style rules from here https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml and renamed the file to `sun_checks`.

When the linter runs I get a bunch of errors like this:
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module JavadocMethod - Property 'accessModifiers' does not exist, please check the documentation
```

Based on this question: https://stackoverflow.com/questions/42095239/maven-checkstyle-plugin-checkstyleexception-property-accessmodifiers-in-modu 
The error is caused by using a very old version of CheckStyle. Looking at the Actions log I didn't see any information about which version is actually being used.

**Comment by admiralAwkbar** [comment]
Hey @nanthony21 

When we build the container we pull in the latest from:
```dockerfile
&& CHECKSTYLE_LATEST=$(curl -s https://api.github.com/repos/checkstyle/checkstyle/releases/latest \
    | grep browser_download_url \
    | grep ".jar" \
    | cut -d '"' -f 4) \
    && curl --retry 5 --retry-delay 5 -sSL "$CHECKSTYLE_LATEST" \
    --output /usr/bin/checkstyle \
```

That is then pushed to the file in the container:
`/action/lib/functions/linterVersions.txt`

From the github/super-linter:latest:
```bash
action/lib/functions # cat linterVersions.txt |grep checkstyle
checkstyle: Checkstyle version: 8.41.1
```

From the github/super-linter:3.15.5:
```bash
checkstyle: Checkstyle version: 8.41
```

Hope this helps!

**Comment by nanthony21** [comment]
Thanks @admiralAwkbar , Looks like something else entirely must be going on, I'll see if I can figure it out.

**Comment by nanthony21** [comment]
Looks like CheckStyle had a formatting change between 8.41 and 8.41.1. https://github.com/checkstyle/checkstyle/issues/7417

So I need to either switch to using ` github/super-linter:latest`, or more likely I'll just wait for  `github/super-linter:3.15.6`

**Comment by admiralAwkbar** [comment]
@nanthony21 Ill try to push a release today to help you out

thanks for helping figure it out :)

**Comment by nanthony21** [comment]
Thanks, seems to be working perfectly now.

**Comment by admiralAwkbar** [comment]
@nanthony21 hey we cut some releases yesterday hope that fixed it

**Comment by nanthony21** [comment]
Thanks @admiralAwkbar ,
I'm no longer getting the initial error however I'm now running into something else entirely.
Super-linter finds no issues with my entire codebase even though it should probably be finding issues in nearly every file.
Here is an example super-linter run: https://github.com/nanthony21/micro-manager/runs/2442521145?check_suite_focus=true
However, when I run CheckStyle 1.42 locally it indicates all sorts of issues with my code.

I'll plan to try installing super-linter locally to see what happens.

**Comment by nanthony21** [comment]
Oops nevermind, it was just a matter of changing my CheckStyle config so that it would report `ERROR`s rather than `WARNING`s. All is well now.
