### ISSUE TITLE
out of date terrascan

### ISSUE THREAD

**Issue by ausfestivus** [github/super-linter#1471]
## Describe the bug

The version of terrascan used by the current release of super-linter (3.15.5) is out of date. The super-linter is using the terrascan commit https://github.com/accurics/terrascan/commit/2d1374b637c43615a94e6e8917bfc9a665d2db61 which contains terrascan 1.2.0. Current release version of terrascan is 1.5.0.

## Expected behavior

super-linter uses a newer version of terrascan.

## Steps to Reproduce

run super-linter

## Additional context

There are a couple of issues fixed in the newer terrascan versions which block my use of super-linter.

https://github.com/github/super-linter/issues/1170
https://github.com/accurics/terrascan/issues/331

This could probably be closed as a dupe of 1170 maybe? The PR that fixes 1170 is closed though so raising this as a new issue to get some visibility of that and also add in reference to 331.

**Comment by admiralAwkbar** [comment]
Hey @ausfestivus Were working on fixing our testing so we can start the update process again. Hope to have that worked out this week, and then push a version update with latest :)
Sorry for the delay
