### ISSUE TITLE
Suport `.rubocop.yml` file

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#148]
**Is your feature request related to a problem? Please describe.**
The rubocop linter uses the `.github/linters/.ruby-lint.yml` file.
But is most likely that people will have defined the setting in the default `.rubocop.yml`

**Describe the solution you'd like**
We could let the super linter use the default and more standard file, instead of the specific one.

**Describe alternatives you've considered**
I tried inheriting from the default file like:
```
inherit_from:
  - ../../.rubocop.yml
```

But I get:
```
Linting [RUBY] files...
----------------------------------------------
----------------------------------------------
---------------------------
File:[./spec/support/matchers/json_schema_matcher.rb]
ERROR! Found errors in [rubocop] linter!
ERROR:[Configuration file not found: /action/.rubocop.yml]
```

I think this is because of file structure inside the linter? Maybe the path would be different to inherit from the file in the root folder, but I'm not sure what would it be.

Also if there is a way to do it, we could put ir in the docs, so people already using `.rubocop.yml` will quickly get up to speed.

**Additional context**
This is kind of related to https://github.com/github/super-linter/issues/124 and in general to all the linters.

It is really common for the linters to have a default config file. So it would be nice if super-linter was able to use the default (standard) config files so we don't need to keep linter configuration in multiple places.

**Comment by benbalter** [comment]
I created a symlink from the project-specific `.ruby-lint.yml` file to the standard `.rubocop.yml` in the project root (`ln -s ../../.rubocop.yml .github/linters/.ruby-lint.yml`). It's not ideal, as it won't support linters not already in the Docker image (e.g., `rubocop-rspec`), but Rubocop seems to follow the symlink.

**Comment by admiralAwkbar** [comment]
This was solved at https://github.com/github/super-linter/commit/d8608a6cf128cc6dfe3223275b98a6dc98459729

I should have been a or... thought I was on a branch... might have beefed it...
