### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#1513]
Is it possible to add the release changes to the releases? Currently I get an email saying a release has happened but with no detail of what’s in that release. There’s usually an issue detailing this (often closed by the time I come to look at it) but any reason not to put the content of that in the release notification itself?

**Comment by admiralAwkbar** [comment]
@bazzadp I need to see about that.
I never notice the emails(flooded with them) but I will try to see what's pushing that and to add more details.

Hope all is well out there!

**Comment by bazzadp** [comment]
Yeah there’s an option to be notified about releases only, and then it includes any info in the release in an email. Happy for repos you care about, but maybe not enough to do a full subscribe to everything!

Also adding release notes to the release itself allows you quickly scan changes in this page, for when something changed or if you’re jumping a few releases: https://github.com/github/super-linter/releases

The [release drafter action](https://github.com/marketplace/actions/release-drafter) automatically adds merged PRs to the a (hidden) draft release which you can then publish as a release (with an edit to clean it up if you want). That is a good basis for release notes - plus a good reminder to yourself what is in this release! Here’s an example of a repo where we use that: https://github.com/HTTPArchive/almanac.httparchive.org/releases (note you can’t see the next draft as you’re not a maintainer, but you can see the old releases).

**Comment by admiralAwkbar** [comment]
@bazzadp i think we will reenable that, it was causing some release issues but I think we are in better shape!

thanks!

**Comment by admiralAwkbar** [comment]
@bazzadp just released `3.17.0` did the email come through better?

**Comment by bazzadp** [comment]
I don't see it released on this page yet: https://github.com/github/super-linter/releases and so didn't get a mail yet.

Note as a maintainer you might be able to see a Draft first on there, but the rest of us can't. Launch it in an Incognito browser to see what I see.

![image](https://user-images.githubusercontent.com/10931297/117052337-860c4d80-ad0f-11eb-8681-c432584f5d45.png)

**Comment by bazzadp** [comment]
Just got the mail there, but alas no info in it again:

![image](https://user-images.githubusercontent.com/10931297/117053352-c15b4c00-ad10-11eb-9cc9-bc3afbf4ad26.png)

**Comment by admiralAwkbar** [comment]
Frustrating...
seems im passifg the info along,

https://github.com/github/super-linter/issues/1517
but it didn't make it to the release body
will check the code

thanks for the help debugging!

**Comment by bazzadp** [comment]
Just got the beautiful release notes mail - thank you!

![image](https://user-images.githubusercontent.com/10931297/118003028-18c87000-b340-11eb-97d4-8c0dcd8cfe19.png)
