### ISSUE TITLE
Super-linter 3.17  - terrascan output is either really sparse or missing

### ISSUE THREAD

**Issue by gclair** [github/super-linter#1526]
## Describe the bug

Superlinter 3.17 terrascan version is giving empty errors.

## Expected behavior

Verbose errors on output.

## Steps to Reproduce

Difficult to reproduce outside of github actions. happening to multiple terraform/terragrunt files.

## Logs

```
2021-05-06 18:45:00 [ERROR]   Found errors in [terrascan] linter!
2021-05-06 18:45:00 [ERROR]   Error code: 1. Command output:
------
2021-05-06T18:45:00.789Z	error	cli/run.go:110	scan run failed{error 26 0  failed to load config file '/github/workspace/path-to/location/main.tf'. error:

}
------
```

**Comment by admiralAwkbar** [comment]
@gclair Seems to be an issue loading its libs, need to validate

**Comment by admiralAwkbar** [comment]
@gclair Can you validate this is still happening on `3.17.0`?
We were a few versions out and want to make sure it wasn't a bad release...

**Comment by gclair** [comment]
That was with 3.17. We've switched over to 3.16.1 in the meantime.

**Comment by phumberdroz** [comment]
I am encoutering the same problem at the moment with https://gitlab.com/r2devops/hub/-/blob/latest/jobs/super_linter/super_linter.yml

While 3.16.1 works fine 3.17.0 and 3.17.1 don't produce an output

**Comment by admiralAwkbar** [comment]
@gclair Hey! trying to get it upgraded, having issues with `R` and its breaking a lot right now...

Will try to get it going this week!
