### ISSUE TITLE
Configure version of each linter

### ISSUE THREAD

**Issue by ashishkeshan** [github/super-linter#153]
It would be awesome to be able to configure the version of the linter to be used in `linter.yml`.

I work on a repo that relies on a specific version of rubocop, and I would love to move all linting to super-linter if support for selecting versions is enabled.

**Comment by Hanse00** [comment]
This is definitely an interesting idea.

If we are to take the announcement literally: "Introducing GitHub Super Linter: one linter to rule them all", then you are right, that for this linter to be applicable to all projects, we must allow for people to use it despite which language and library versions they are depending on.

However it's not a trivial feature to implement, I see a few challenges:
* The linters are installed in the Dockerfile, meaning the distributed container image already has the linters hard coded at that point. We would have to either:
  * Allow people to pass linter versions as build arguments, and build their own versions of the container.
  * Install linters during runtime, increasing the overall runtime of the linter (And wasting computing resources globally, re-running the same installers over and over again).
  * Publish multiple container versions, each containing individual linter versions. The number of permutations would be (number of versions of each linter ^ the number of linters), which gets very big very fast.
* Besides the linters themselves, we need to support the various dependencies at different versions as well, and ensure there are no conflicts there.

In connection to what we are discussing in #7, which is to split each check into an action of it's own, perhaps we make a container for each check / linter, making it easier to support different configurations, as they don't interact with each other at that point?

It's something to think through thoroughly.

**Comment by admiralAwkbar** [comment]
At this point, if you need a specific version, the best option is to fork the repository
