### ISSUE TITLE
Wiki page has incorrect github actions example

### ISSUE THREAD

**Issue by iggy** [github/super-linter#154]
**Describe the bug**

https://github.com/github/super-linter/wiki has an example with the below line of yaml for using super linter in a github action

```yaml
      - name: Lint Code Base
        uses: docker://github/super-linter@v1.0.0
```
It should probably be
```yaml
      - name: Lint Code Base
        uses: github/super-linter@v2.0.0
```
So take off the `docker://` bit and (maybe) bump to the latest version.

Note: This wiki page is linked from the github.blog post announcing this project, so it was the first thing I (and probably others will) read. The `README.md` in the repo root is correct.

**Comment by zkoppert** [comment]
Thanks for submitting the issue @iggy! This has been resolved at https://github.com/github/super-linter/wiki/Home/a5da73e239e9c67137c5e150e2916565939e72af because of your submission. Keep contributing!

**Comment by iggy** [comment]
It was only fixed in one of the examples. There are 2 in that wiki page. Thanks for the quick turnaround btw.
