### ISSUE TITLE
Set outputs for easier use in actions

### ISSUE THREAD

**Issue by leviem1** [github/super-linter#1553]
**Is your feature request related to a problem? Please describe.**
The super-linter can be less than easy to understand for non-technical users. We use super-linter for our blog where authors use markdown. To make things simpler for them, we send notifications on Discord when there is a linting error. However, the best information we can provide about what went wrong is a link to the workflow run, which is still quite confusing. Additionally, some of our authors don't have GitHub accounts, as they make their edits through a third-party CMS, so they have no visibility into why the workflow may have failed. 

**Describe the solution you'd like**
Ideally, you'd use action outputs to store information from the linter run. In my case, I would appreciate a "linter-errors" output, though there could be use cases for "linter-output" or other outputs. This would allow me to send the error messages to a Discord channel, and could enable other actions to parse the output.

**Describe alternatives you've considered**
I've tried to do some hacky tricks by running docker directly in an action and piping that to something like "echo", but the github docker command is quite long and this probably isn't considered best practice.

**Additional context**
Definitely open to other suggestions or ideas on how to accomplish this.

**Comment by admiralAwkbar** [comment]
@leviem1 This is a great idea.
I think adding an output file with the results could be helpful to all users. We used to have a TAP output, but it was rough and causing issues.

I'm going to see about a simple re-implementation, and we can grow back from there

**Comment by leviem1** [comment]
Speaking of which, there's an error in the logs about a missing .sh file with "tap" in the name on every run. Not sure if you were aware of it.

**Comment by admiralAwkbar** [comment]
@leviem1 i thought i pulled that but ill double check :)

**Comment by leviem1** [comment]
Bump

**Comment by leviem1** [comment]
Another suggestion: isn't there a label to exclude certain issues from dependabot? Maybe label the issues you actually plan to work on so that they don't get closer and you lose visibility.

**Comment by leviem1** [comment]
See last comment

**Comment by leviem1** [comment]
Jokes on you bot, I beat you to it
