### ISSUE TITLE
Add tap support back in

### ISSUE THREAD

**Issue by phumberdroz** [github/super-linter#1558]
**Is your feature request related to a problem? Please describe.**
Tap output format got recently removed in a Minor Version with MR #1496 

This broke for example https://gitlab.com/r2devops/hub/-/blob/latest/jobs/super_linter/super_linter.yml which was a nice way of integrating super linter into gitlab for reporting linting issues

**Describe the solution you'd like**
Add Tap support back in

**Describe alternatives you've considered**
n/a

**Additional context**
#1496 

**Note**
I created this more for tracking and to get updates if something changes.

**Comment by zkoppert** [comment]
@admiralAwkbar or @ferrarimarco, Can you add some input here on the reason why tap was removed so we can discuss how to overcome that if it is being proposed to be added back in. Thanks!!

**Comment by admiralAwkbar** [comment]
@zkoppert it was really tied into our testing and was a pain.... tap was always broke and caused a ton of issues for us to maintain. But creating the output for users seemed to be a win.

So if we can add it back for user output, and not the testing side, we should be in good shape...

**Comment by phumberdroz** [comment]
still relevant

**Comment by firefox1337** [comment]
can this be reopened, please? I agree with @admiralAwkbar that the output is really valuable to users. 
We use tap output to convert and import it as testresults in AzureDevOps. Would be awesome if it can be added again

**Comment by admiralAwkbar** [comment]
We just need some help to get it re-implemented... have been slammed with work and not enough time to get features back in :(

**Comment by acauret** [comment]
Please add this back in as its so important with Azure Devops

**Comment by ferrarimarco** [comment]
@acauret can you describe your use case?

**Comment by nvuillam** [comment]
Forget TAP, long live SARIF ! :)

**Comment by acauret** [comment]
Need this for good reporting in AzureDevops that show the test results as per https://adinermie.com/publishing-github-super-linter-terraform-quality-checks-to-azure-devops-pipelines/ . If you can provide a native way of doing this, all the better ..

**Comment by mjonespro** [comment]
Echoing comments that this would be great to add back in specifically for azure devops functionality stated in other comments.

**Comment by CarlDawsonBCA** [comment]
also need tap output. without this supeerlinter is useless to us as as we cant iuntegrate the results in azure devops
