### ISSUE TITLE
Is there a possibility to speed up fetching the docker image?

### ISSUE THREAD

**Issue by saroup** [github/super-linter#1559]
We are using gitlab CI to run linters, formatter and as we decided to try out superlinter to run multiple tools. We noticed that it 
was much slowed 11/2 min slower and we noticed that the very first step takes ~2 mins 

 Running with gitlab-runner 13.12.0-rc1 (b21d5c5b)
  on docker-auto-scale 0277ea0f
  feature flags: FF_GITLAB_REGISTRY_HELPER_IMAGE:true, FF_SKIP_DOCKER_MACHINE_PROVISION_ON_CREATION_FAILURE:true
Preparing the "docker+machine" executor

We would like this process to be faster

Using the tools directly without superlinter, it is much faster as they run in parralel

**Comment by admiralAwkbar** [comment]
@saroup Hey!

Its a very large image and that's the main cause for waiting to pull the image down...
It would also help if the linters ran in parallel, but in its current implementation, its very serial...

Were looking at making a few images to help pull down the size...

I.e github/super-linter:windows, or github/super-linter:rust

Those 2 linters are around 1.5 gb a piece.... so it would help...

**Comment by M1cha** [comment]
another possibility would be allowing the action to run without docker.
many projects probably know very well what language they're using so it'd be more efficient to just install those dependencies in a previous step in case they're aren't doing that already anyway.
On top of that, `ubuntu-latest` contains a lot of packages already anyway.

**Comment by admiralAwkbar** [comment]
@saroup We also just released the slim image that removes a few languages from the image and drastically pulls its size down...

take a look at https://github.com/github/super-linter#slim-image and see if that can help you!
