### ISSUE TITLE
Add webhint

### ISSUE THREAD

**Issue by hxlnt** [github/super-linter#156]
[webhint](https://github.com/webhintio/hint) seems like a good addition to the list of linters. Checks a11y, cross-browser compat, other best practices on HTML, CSS, etc.

**Comment by zkoppert** [comment]
@hxlnt I like it, can you try to put together a PR with the proposed changes?

we have a wiki on all the changes needed :)

https://github.com/github/super-linter/wiki/Adding-new-language-support

**Comment by zkoppert** [comment]
@hxlnt If you want to open this back up again at another time, I'm happy to support. Just let me know. 😃
