### ISSUE TITLE
kubeval fails for CRDs Failed initializing schema https://kubernetesjsonschema.dev/master-standalone-strict/customresourcedefinition-apiextensions-v1.json: Could not read schema from HTTP, response status is 404 Not Found

### ISSUE THREAD

**Issue by vorburger** [github/super-linter#1601]
## Describe the bug

https://github.com/vorburger/LearningKubernetes-CodeLabs/pull/1/checks?check_run_id=2689120040

```
2021-05-27 21:34:01 [INFO]   File:[/github/workspace/docs/files/foo.crd.yaml]
2021-05-27 21:34:01 [ERROR]   Found errors in [kubeval] linter!
2021-05-27 21:34:01 [ERROR]   Error code: 1. Command output:
------
ERR  - /github/workspace/docs/files/foo.crd.yaml: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone-strict/customresourcedefinition-apiextensions-v1.json: Could not read schema from HTTP, response status is 404 Not Found
```

## Expected behavior

Green build.

**Comment by vorburger** [comment]
https://kubernetesjsonschema.dev/master-standalone-strict/customresourcedefinition-apiextensions-v1.json indeed 404s.

https://github.com/github/super-linter/issues/1601 seems related.

Based on https://kubeval.instrumenta.dev/#crds, you would have to be able to pass `--ignore-missing-schemas` when launching `kubeval`.

Perhaps `super-linter` could have something like an `VALIDATE_KUBERNETES_KUBEVAL_OPTIONS` so that one can add things like `--ignore-missing-schemas` et al?

Until then, I guess `VALIDATE_KUBERNETES_KUBEVAL: false`. 😿

**Comment by admiralAwkbar** [comment]
@vorburger this makes sense, will look into being able to pass params... this has been a hot topic :)

**Comment by ferrarimarco** [comment]
For the record, the root cause is https://github.com/instrumenta/kubernetes-json-schema/issues/26 (TLDR: Kubeval cannot find the 1.19 schema descriptors because they aren't available, yet).
