### ISSUE TITLE
To override LINTER_PATH

### ISSUE THREAD

**Issue by sayboras** [github/super-linter#161]
**Is your feature request related to a problem? Please describe.**
Most of the existing repo will already have existing lint rules, and most of them will be placed in root directory of project.

Moving all of them to LINTER_PATH (e.g. .github/linters) wil require either some duplication or breaking exiting way to run lint locally

**Describe the solution you'd like**
To have ability to override this param LINTER_PATH.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by GaboFDC** [comment]
Related to https://github.com/github/super-linter/issues/148
