### ISSUE TITLE
Specific version slim tag missing in Docker rep

### ISSUE THREAD

**Issue by jsol** [github/super-linter#1612]
## Describe the bug

Docker tags prefixed with slim- should match the main docker tags.

latest => slim-latest exists
v4 => slim-v4 exists
v4.0.2 => slim-v4.0.2 does NOT exist.

There is however a tag slim-.

## Expected behavior

I expect being able to specify a version with slim, ie docker pull github/super-linter:slim-v4.0.2

**Comment by admiralAwkbar** [comment]
@jsol thanks for the catch on this. will look into the automation and see what happened!
