### ISSUE TITLE
Change Default of LINTER_RULES_PATH to Root of Project

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/super-linter#1634]
**Is your feature request related to a problem? Please describe.**
Super-Linter is a great tool for enforcing lint rules in CI, but running linters locally (a) is typically faster, (b) can be done before committing to keep each individual commit clean (and not just the entire pull request), (c) doesn't require an Internet connection, and (d) doesn't consume build minutes. Presently, if you have already configured linters to run locally, Super-Linter largely ignores these configuration files, which can be easily overlooked since it doesn't necessarily result in an error.

**Describe the solution you'd like**
Default `LINTER_RULES_PATH` to "." rather than ".github/linters." Nearly all configurable linters look for their configuration files in the root of the project by default, so this would make Super-Linter play better out of the box with most of these linters.

**Describe alternatives you've considered**
At present, the alternative is that every project that desires to both use Super-Linter and run their linters locally needs to independently make this same discovery and then set `LINTER_RULES_PATH` to `.` themselves.

**Comment by admiralAwkbar** [comment]
@Kurt-von-Laven  i believe if you set:
```bash
LINTER_RULES_PATH: /
``` 
then you will get the behavior you expect. Hope this helps!

**Comment by Kurt-von-Laven** [comment]
I already have a working workaround, but I filed this issue, because I feel that ".github/linters" is a poor choice of default that should be changed.
