### ISSUE TITLE
Secretlint support - credential checker

### ISSUE THREAD

**Issue by azu** [github/super-linter#164]
**Is your feature request related to a problem? Please describe.**
Credential linter is missing in super-linter.

A Scanner for SSH Private key, access token, etc...

**Describe the solution you'd like**
[Secretlint](https://github.com/secretlint/secretlint) and [@secretlint/secretlint-rule-preset-recommend](https://github.com/secretlint/secretlint/tree/master/packages/@secretlint/secretlint-rule-preset-recommend) seems like a good addition to the list of linters.
(Its similar implementation of eslint, stylelint #142 )

**Describe alternatives you've considered**

- [awslabs/git-secrets: Prevents you from committing secrets and credentials into git repositories](https://github.com/awslabs/git-secrets)
- [zricethezav/gitleaks: Scan git repos for secrets using regex and entropy 🔑](https://github.com/zricethezav/gitleaks)
- [dxa4481/truffleHog: Searches through git repositories for high entropy strings and secrets, digging deep into commit history](https://github.com/dxa4481/truffleHog)
- [Yelp/detect-secrets: An enterprise friendly way of detecting and preventing secrets in code.](https://github.com/Yelp/detect-secrets)

or GitHub's [secret scanning](https://help.github.com/en/github/administering-a-repository/about-secret-scanning)(not public beta yet).

**Additional context**

**Question**

[Secretlint](https://github.com/secretlint/secretlint) always scan all file extensions.
[Super-Linter](https://github.com/github/super-linter) has a linter per a language.

Where's the right place to put it? `VALIDATE_???`

**Comment by zkoppert** [comment]
Since GitHub already has secret scanning on its way, I’m thinking that this might not be a high value add.

**Comment by zkoppert** [comment]
Closing due to no response or support
