### ISSUE TITLE
Support passing a custom .ini file to the PHP_BUILTIN linter (so I can enable short_open_tag)

### ISSUE THREAD

**Issue by talawahtech** [github/super-linter#1643]
**Is your feature request related to a problem? Please describe.**
I am trying to run the linter on files that use short open tags and it throws errors for valid files.

**Describe the solution you'd like**
I would like to be able to override ini directives using a custom ini file

**Additional context**
I believe the ini file could be passed in on the command line by reusing the same approach you use for custom rules. e.g.
```
LINTER_COMMANDS_ARRAY['PHP_BUILTIN']="php -l -c ${PHP_PHP_BUILTIN_INI}"
```

**Comment by talawahtech** [comment]
@admiralAwkbar wow, that was fast. Thanks!

**Comment by admiralAwkbar** [comment]
@talawahtech  :)
