### ISSUE TITLE
Add pydocstyle to the list of available python linters

### ISSUE THREAD

**Issue by mmrzyglockitivo** [github/super-linter#1648]
[`pydocstyle`](http://www.pydocstyle.org/en/stable/) is a checker for [PEP 257 docstring format](https://www.python.org/dev/peps/pep-0257/). While PEP 257 doesn't go into deep details of docstring conventions, it's accepted as a default formatting convention and the checker is decently popular, so hopefully it can be included.

It's possible to silence its output except for errors, receive error code, give an explicit `--config` argument.

**Comment by admiralAwkbar** [comment]
@mmrzyglockitivo 
Very interesting!

Let's see if we get some cycles to get this added in

thanks for the info!

**Comment by mmrzyglockitivo** [comment]
Bumping up - it would be very useful for `python` code quality to have this part of code checked within `super-linter`, without a necessity for manual actions.
