### ISSUE TITLE
Yamllint doesn't show line numbers

### ISSUE THREAD

**Issue by konstantin-kornienko** [github/super-linter#1669]
## Describe the bug

Yamllint's output doesn't have line numbers. How it can be fixed?

```
2021-06-17 09:06:34 [ERROR]   Error code: 1. Command output:
------
Error: [quoted-strings] string value is not quoted with single quotes
Error: [quoted-strings] string value is not quoted with single quotes
Error: [quoted-strings] string value is not quoted with single quotes
Error: [quoted-strings] string value is not quoted with single quotes
Error: [quoted-strings] string value is not quoted with single quotes
Error: [quoted-strings] string value is not quoted with single quotes
Error: [quoted-strings] string value is not quoted with single quotes
Warning: [line-length] line too long (183 > 180 characters)
Warning: [comments] too few spaces before comment
Warning: [comments] too few spaces before comment
Warning: [comments] too few spaces before comment
Warning: [line-length] line too long (257 > 180 characters)
Warning: [line-length] line too long (335 > 180 characters)
Warning: [line-length] line too long (260 > 180 characters)
Warning: [line-length] line too long (259 > 180 characters)
Warning: [line-length] line too long (259 > 180 characters)
Warning: [line-length] line too long (260 > 180 characters)
Warning: [line-length] line too long (314 > 180 characters)
Warning: [comments] too few spaces before comment
Warning: [comments] too few spaces before comment`
```

## Config files

.yaml-lint.yml:
```
---

extends: 'default'

yaml-files:
  - '*.yml'
  - '*.yml.j2'

rules:
  line-length:
    max: 180
    level: 'warning'
  quoted-strings:
    quote-type: 'single'
```

linter config:
```
---
name: 'Lint action'

on:
  push:
    branches-ignore: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: 'Code Base Lint'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v2'
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: 'Run Super Linter'
        uses: 'docker://ghcr.io/github/super-linter:slim-v4'
        env:
          ANSIBLE_CONFIG_FILE: '.ansible-lint.yml'
          ANSIBLE_DIRECTORY: 'ansible'
          DEFAULT_BRANCH: 'master'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          LINTER_RULES_PATH: '/'
          PYTHON_FLAKE8_CONFIG_FILE: 'tox.ini'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: true
          VALIDATE_BASH: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: '.yaml-lint.yml'
```

**Comment by admiralAwkbar** [comment]
@konstantin-kornienko  Hey this is odd...
I just pulled the image and ran tests and was able to see the line numbers...

Can you try to run it again and add the flag:
```yml
ACTIONS_RUNNER_DEBUG: true
```

**Comment by konstantin-kornienko** [comment]
Sure. Thanks for help.
[logs_85.zip](https://github.com/github/super-linter/files/6671049/logs_85.zip)
![Screenshot 2021-06-17 121940](https://user-images.githubusercontent.com/50887992/122418642-05d63a80-cf93-11eb-916d-8ffcee52ace8.png)

**Comment by admiralAwkbar** [comment]
@konstantin-kornienko This is super odd... It appears all is fine in the image and the version I just tested worked...
I'm at a loss why in your code, it doesn't show the line numbers...

Could you try to run it again but use our `.yaml-lint.yml` file and see if you get the line numbers...

It's odd as there is no real value in the `.yaml-lint.yml` that directly does this, but I would be interested to see if you get the same output or line numbers...

**Comment by konstantin-kornienko** [comment]
@admiralAwkbar , have tried everything.
Looks like it's some sort of magic, nothing to do here, let I close the ticket...
Thanks again!

**Comment by admiralAwkbar** [comment]
@konstantin-kornienko Sorry I cant be more help! it's super weird!

**Comment by ferrarimarco** [comment]
I think we're experiencing this issue: https://github.com/adrienverge/yamllint/issues/357

**Comment by ferrarimarco** [comment]
More specifically: https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-github-actions, which was introduced in yamllint 1.25.0.

> yamllint auto-detects when it’s running inside of GitHub Actions<https://github.com/features/actions> and automatically uses the suited output format to decorate code with linting errors automatically.

So yamllint annotates the files directly using the GitHub actions API.

To revert to the previous behavior, we might set the `--format standard` option
