### ISSUE TITLE
Ansible validator in superlinter validating incorrect files

### ISSUE THREAD

**Issue by dannystaple** [github/super-linter#1671]
## Describe the bug

Our ansible repo has the following structure:

```text
/
 - ansible/
    - inventory/
      - host_vars/
        - host_foo/
          - vars.yml
          - vault.yml
      - group_vars/
        - group_bar/
          - vars.yml
          - vault.yml
      - inventory_live.yml
      - inventory_staging_dev.yml
      - inventory_staging_test.yml
    - playbooks/
      - install_blah.yaml
      - micro_apps/
        - install_micro_app_a.yml
    - roles/
      - micro_app/
      - k8s_namespace/
      - galaxy_roles.yml
    - installed_roles/
      - <3rd party installed roles>
    - installed_collections/
      - <3rd party installed collections>
    - ansible.cfg
    - .ansible-lint.yml
  - .github/
    - workflows/
      - lint_on_pr.yml
```

Our roles have templates in many languages, including some yaml.  
We are successfully able to lint our code with ansible-lint with the following directives in our workflow:

```yaml
-  uses: ansible/ansible-lint-action@master
```

This will spot the majority of linter issues, with some cases we've overridden in the lint config.

When we attempt to run this in superlinter, with the ANSIBLE_DIRECTORY pointing by default at our /ansible folder (or overriding it) it always fails, by trying to parse the inventory files as playbooks. It seems to be validating every file individually - sending them all directly.

I read through the superlinter and ansible-lint code and have been able to reproduce the same behavior by running the following:

```shell
$ ansible-lint  -v -c ansible/.ansible-lint.yml ansible/inventory/inventory_staging_dev.yml
DEBUG    Logging initialized to level 10
DEBUG    Options: Namespace(cache_dir='/Users/dastaple/.cache/ansible-lint/0ddf3c', colored=True, config_file='/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/ansible/.ansible-lint.yml', configured=True, cwd=PosixPath('/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/ansible'), display_relative_path=True, enable_list=[], exclude_paths=['/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/ansible/.github'], extra_vars=None, format='rich', kinds=[{'jinja2': '**/*.j2'}, {'jinja2': '**/*.j2.*'}, {'requirements': '**/meta/requirements.yml'}, {'galaxy': '**/galaxy.yml'}, {'reno': '**/releasenotes/*/*.{yaml,yml}'}, {'playbook': '**/playbooks/*.{yml,yaml}'}, {'playbook': '**/*playbook*.{yml,yaml}'}, {'role': '**/roles/*/'}, {'tasks': '**/tasks/**/*.{yaml,yml}'}, {'handlers': '**/handlers/*.{yaml,yml}'}, {'vars': '**/{host_vars,group_vars,vars,defaults}/**/*.{yaml,yml}'}, {'meta': '**/meta/main.{yaml,yml}'}, {'yaml': '.config/molecule/config.{yaml,yml}'}, {'requirements': '**/molecule/*/{collections,requirements}.{yaml,yml}'}, {'yaml': '**/molecule/*/{base,molecule}.{yaml,yml}'}, {'requirements': '**/requirements.yml'}, {'playbook': '**/molecule/*/*.{yaml,yml}'}, {'yaml': '**/{.ansible-lint,.yamllint}'}, {'yaml': '**/*.{yaml,yml}'}, {'yaml': '**/.*.{yaml,yml}'}], lintables=['inventory/inventory_staging_dev.yml'], listrules=False, listtags=False, loop_var_prefix=None, mock_modules=['site24x7_tag'], mock_roles=[], offline=False, parseable=True, parseable_severity=False, progressive=True, project_dir='.', quiet=False, rules={}, rulesdir=[], rulesdirs=['/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/.venv/lib/python3.7/site-packages/ansiblelint/rules'], skip_action_validation=True, skip_list=['risky-file-permissions', 'unnamed-task', 'no-handler'], tags=[], use_default_rules=True, var_naming_pattern='^[a-z_][a-z0-9_]*$', verbosity=2, version=False, warn_list=['experimental', 'role-name'])
INFO     Added ANSIBLE_LIBRARY=/Users/dastaple/.cache/ansible-lint/0ddf3c/modules
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles
DEBUG    Loading rules from /Users/dastaple/workspace/atom/Atom.DevOps.Ansible/.venv/lib/python3.7/site-packages/ansiblelint/rules
INFO     Added ANSIBLE_LIBRARY=/Users/dastaple/.cache/ansible-lint/0ddf3c/modules:/Users/dastaple/.cache/ansible-lint/0ddf3c/modules
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles:roles
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: inventory/inventory_staging_dev.yml
INFO     Executing syntax check on inventory/inventory_staging_dev.yml (0.70s)
INFO     Matches found, running again on previous revision in order to detect regressions
Preparing worktree (checking out 'old-rev')
HEAD is now at 96bc71c Fix the odd trailing spaces there.
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: inventory/inventory_staging_dev.yml
INFO     Executing syntax check on inventory/inventory_staging_dev.yml (0.42s)
WARNING  Listing 1 violation(s) that are fatal
inventory/inventory_staging_dev.yml:1:1: syntax-check A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - syntax-check  # Ansible syntax check failed
Finished with 1 failure(s), 0 warning(s) on 1 files.
```

The example shows that it picked an inventory file, and tried to parse it as a playbook.

## Expected behavior

I would expect the linter to be supplied with enough data to not attempt treating an inventory item as a playbook. I would also expect it to be reading the ansible.cfg.

## Steps to Reproduce

1. Create an ansible repo shaped a little like the above.
1. Create an workflow yaml using superlinter, enabling VALIDATE_ANSIBLE.
1. Make the github operation to trigger the workflow.
1. See error

**Comment by admiralAwkbar** [comment]
@dannystaple 
Hey, thanks for the info!

It does appear our logic is not the strongest when looking for ansible information.

I need to look over the code a bit and see if there are some easy ways to help it find the information better.
I believe the logic is it looks for playbooks in the `/ansible/ directory, and that's likely causing the issues.

**Comment by admiralAwkbar** [comment]
@dannystaple This seems to be a major issue between how we find all individual files, and how `ansible/ansible-lint-action@master` tries to run a single pass through.

If we went that approach, we would likely be lining all ansible every run, and that's not the goal of how this tool works.

Until we can find a better way to parse a playbook from other files, this is not going to be an easy fix on our side.

Is it possible to show in the `ansible.cfg` where the playbooks are located?

If That is possible, we could likely update some logic to parse, and then make sure we are testing correctly.

thanks

**Comment by ElWeroRanchero** [comment]
[ElWeroRanchero ].patch

**Comment by ElWeroRanchero** [comment]
> ## Describe the bug
> Our ansible repo has the following structure:
> 
> ```
> /
>  - ansible/
>     - inventory/
>       - host_vars/
>         - host_foo/
>           - vars.yml
>           - vault.yml
>       - group_vars/
>         - group_bar/
>           - vars.yml
>           - vault.yml
>       - inventory_live.yml
>       - inventory_staging_dev.yml
>       - inventory_staging_test.yml
>     - playbooks/
>       - install_blah.yaml
>       - micro_apps/
>         - install_micro_app_a.yml
>     - roles/
>       - micro_app/
>       - k8s_namespace/
>       - galaxy_roles.yml
>     - installed_roles/
>       - <3rd party installed roles>
>     - installed_collections/
>       - <3rd party installed collections>
>     - ansible.cfg
>     - .ansible-lint.yml
>   - .github/
>     - workflows/
>       - lint_on_pr.yml
> ```
> 
> Our roles have templates in many languages, including some yaml.
> We are successfully able to lint our code with ansible-lint with the following directives in our workflow:
> 
> ```yaml
> -  uses: ansible/ansible-lint-action@master
> ```
> 
> This will spot the majority of linter issues, with some cases we've overridden in the lint config.
> 
> When we attempt to run this in superlinter, with the ANSIBLE_DIRECTORY pointing by default at our /ansible folder (or overriding it) it always fails, by trying to parse the inventory files as playbooks. It seems to be validating every file individually - sending them all directly.
> 
> I read through the superlinter and ansible-lint code and have been able to reproduce the same behavior by running the following:
> 
> ```shell
> $ ansible-lint  -v -c ansible/.ansible-lint.yml ansible/inventory/inventory_staging_dev.yml
> DEBUG    Logging initialized to level 10
> DEBUG    Options: Namespace(cache_dir='/Users/dastaple/.cache/ansible-lint/0ddf3c', colored=True, config_file='/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/ansible/.ansible-lint.yml', configured=True, cwd=PosixPath('/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/ansible'), display_relative_path=True, enable_list=[], exclude_paths=['/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/ansible/.github'], extra_vars=None, format='rich', kinds=[{'jinja2': '**/*.j2'}, {'jinja2': '**/*.j2.*'}, {'requirements': '**/meta/requirements.yml'}, {'galaxy': '**/galaxy.yml'}, {'reno': '**/releasenotes/*/*.{yaml,yml}'}, {'playbook': '**/playbooks/*.{yml,yaml}'}, {'playbook': '**/*playbook*.{yml,yaml}'}, {'role': '**/roles/*/'}, {'tasks': '**/tasks/**/*.{yaml,yml}'}, {'handlers': '**/handlers/*.{yaml,yml}'}, {'vars': '**/{host_vars,group_vars,vars,defaults}/**/*.{yaml,yml}'}, {'meta': '**/meta/main.{yaml,yml}'}, {'yaml': '.config/molecule/config.{yaml,yml}'}, {'requirements': '**/molecule/*/{collections,requirements}.{yaml,yml}'}, {'yaml': '**/molecule/*/{base,molecule}.{yaml,yml}'}, {'requirements': '**/requirements.yml'}, {'playbook': '**/molecule/*/*.{yaml,yml}'}, {'yaml': '**/{.ansible-lint,.yamllint}'}, {'yaml': '**/*.{yaml,yml}'}, {'yaml': '**/.*.{yaml,yml}'}], lintables=['inventory/inventory_staging_dev.yml'], listrules=False, listtags=False, loop_var_prefix=None, mock_modules=['site24x7_tag'], mock_roles=[], offline=False, parseable=True, parseable_severity=False, progressive=True, project_dir='.', quiet=False, rules={}, rulesdir=[], rulesdirs=['/Users/dastaple/workspace/atom/Atom.DevOps.Ansible/.venv/lib/python3.7/site-packages/ansiblelint/rules'], skip_action_validation=True, skip_list=['risky-file-permissions', 'unnamed-task', 'no-handler'], tags=[], use_default_rules=True, var_naming_pattern='^[a-z_][a-z0-9_]*$', verbosity=2, version=False, warn_list=['experimental', 'role-name'])
> INFO     Added ANSIBLE_LIBRARY=/Users/dastaple/.cache/ansible-lint/0ddf3c/modules
> INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles
> DEBUG    Loading rules from /Users/dastaple/workspace/atom/Atom.DevOps.Ansible/.venv/lib/python3.7/site-packages/ansiblelint/rules
> INFO     Added ANSIBLE_LIBRARY=/Users/dastaple/.cache/ansible-lint/0ddf3c/modules:/Users/dastaple/.cache/ansible-lint/0ddf3c/modules
> INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:roles:roles
> WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: inventory/inventory_staging_dev.yml
> INFO     Executing syntax check on inventory/inventory_staging_dev.yml (0.70s)
> INFO     Matches found, running again on previous revision in order to detect regressions
> Preparing worktree (checking out 'old-rev')
> HEAD is now at 96bc71c Fix the odd trailing spaces there.
> WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: inventory/inventory_staging_dev.yml
> INFO     Executing syntax check on inventory/inventory_staging_dev.yml (0.42s)
> WARNING  Listing 1 violation(s) that are fatal
> inventory/inventory_staging_dev.yml:1:1: syntax-check A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead
> You can skip specific rules or tags by adding them to your configuration file:
> # .ansible-lint
> warn_list:  # or 'skip_list' to silence them completely
>   - syntax-check  # Ansible syntax check failed
> Finished with 1 failure(s), 0 warning(s) on 1 files.
> ```
> 
> The example shows that it picked an inventory file, and tried to parse it as a playbook.
> 
> ## Expected behavior
> I would expect the linter to be supplied with enough data to not attempt treating an inventory item as a playbook. I would also expect it to be reading the ansible.cfg.
> 
> ## Steps to Reproduce
> 1. Create an ansible repo shaped a little like the above.
> 2. Create an workflow yaml using superlinter, enabling VALIDATE_ANSIBLE.
> 3. Make the github operation to trigger the workflow.
> 4. See error
> 
> ## Logs
> ## Additional context
.patch

**Comment by dannystaple** [comment]
I think this issue is still around, and not yet fixed. Not stale.

**Comment by cesarg-0624** [comment]
Yeh

**Comment by djdanielsson** [comment]
this is still an issue
