### ISSUE TITLE
Use eslint-plugin-coffee over coffeelint?

### ISSUE THREAD

**Issue by danielbayley** [github/super-linter#169]
**Is your feature request related to a problem? Please describe.**
_coffeelint_ is somewhat outdated.

**Describe the solution you'd like**
[eslint-plugin-coffee](https://github.com/helixbass/eslint-plugin-coffee) is a better way to lint CoffeeScript files, especially since this project already uses _eslint_. See more of the why [in the README](https://github.com/helixbass/eslint-plugin-coffee#why-does-this-project-exist)…

**Comment by admiralAwkbar** [comment]
@danielbayley I see we had pushed a PR that updated the coffeelint to the `@coffeelint/cli` which was newer and more up to date library... is that ok? Or is the eslint a more complete update?

**Comment by danielbayley** [comment]
@admiralAwkbar coffeelint has been updated (kindly by @UziTech and others, including a few PRs from myself) to support existing projects using it. But [eslint-plugin-coffee](https://github.com/helixbass/eslint-plugin-coffee#why-does-this-project-exist) is a superior approach, as a plugin to the much more widely used ESLint, it uses the AST output from CoffeeScript, rather than the old tokens, and/or regular expressions, and so is much more future proof… See also: https://github.com/coffeelint/coffeelint/issues/35

**Comment by UziTech** [comment]
I do believe `eslint-plugin-coffee` is great to use but there are still a few [rules](https://github.com/helixbass/eslint-plugin-coffee#migrating-from-coffeelint) that do not work in eslint that do in coffeelint.

It would be nice to have an option to choose which one to use.

**Comment by danielbayley** [comment]
@UziTech Could the projects be merged somehow, into a single package? I'd be willing to help with such an effort…

**Comment by admiralAwkbar** [comment]
if @danielbayley and @UziTech can come to an agreement on which is the best approach, I would be glad to implement it. I know `CoffeeScript` but don't know which is the better approach, or which will be the better longstanding approach :)

Please open a PR when you have found the common grounds

**Comment by danielbayley** [comment]
cc: @helixbass
