### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by Drunpy** [github/super-linter#172]
**Possible linters:**

- [~rustfmt~](https://github.com/rust-lang/rustfmt)

- [clippy](https://github.com/rust-lang/rust-clippy) (suggested by @oblique)

**Comment by oblique** [comment]
rustfmt only checks the formatting. A good Rust linter is [clippy](https://github.com/rust-lang/rust-clippy).

**Comment by DDtKey** [comment]
Duplicate #108
