### ISSUE TITLE
linter config files should not live in ./github

### ISSUE THREAD

**Issue by marbar3778** [github/super-linter#174]
**Is your feature request related to a problem? Please describe.**
Currently, in the documentation it states that the linter config files should live in `.github/linters`. 

This will cause some applications to have two config files. Many applications ship commands to run linting, for example in most go projects I have worked on you run `make lint`, this runs golanci-lint. Golangci-lint looks for a config file in the current working directory. So to have this linter action work we would need to have two `.golangcilint.yaml` files, one in `./github/linters` and another at the root of the project. This will lead to discrepancies of what is being linted locally and on ci if both files are not updated. 

I believe this will be the same for all projects using eslint as last time I checked it looks in root for a config file.

If projects do decide to move their linting files to `./github/linters` then code editors will break and or lint with no knowledge of the desired linters or the location of the config files. 

**Describe the solution you'd like**
Allow setting custom paths to config files & default to always look at the root for config files. 

**Describe alternatives you've considered**
I don't think there is an alternative? I may be wrong but as it currently stands this breaks many conventions held by the majority of codebases

**Additional context**

**Comment by GaboFDC** [comment]
Related to https://github.com/github/super-linter/issues/148

**Comment by caitlinelfring** [comment]
I was able to work around this without moving the files by creating a symlink into `.github.linters`. The super-linter seems to pick it up. It's a good enough workaround for now, I think

```
ln -sf ../../.yamllint.yml .github/linters/.yaml-lint.yml
ln -sf ../../.ansible-lint .github/linters/.ansible-lint.yml
```

And in the super-linter logs (running locally):
```
User provided file:[.yaml-lint.yml], setting rules file...
  -> Codebase does NOT have file:[.github/linters/.markdown-lint.yml], using Default rules at:[/action/lib/.automation/.markdown-lint.yml]
  -> Codebase does NOT have file:[.github/linters/.python-lint], using Default rules at:[/action/lib/.automation/.python-lint]
  -> Codebase does NOT have file:[.github/linters/.ruby-lint.yml], using Default rules at:[/action/lib/.automation/.ruby-lint.yml]
  -> Codebase does NOT have file:[.github/linters/.coffee-lint.json], using Default rules at:[/action/lib/.automation/.coffee-lint.json]
----------------------------------------------
User provided file:[.ansible-lint.yml], setting rules file...
  -> Codebase does NOT have file:[.github/linters/.eslintrc.yml], using Default rules at:[/action/lib/.automation/.eslintrc.yml]
  -> Codebase does NOT have file:[.github/linters/.eslintrc.yml], using Default rules at:[/action/lib/.automation/.eslintrc.yml]
  -> Codebase does NOT have file:[.github/linters/.golangci.yml], using Default rules at:[/action/lib/.automation/.golangci.yml]
  -> Codebase does NOT have file:[.github/linters/.dockerfilelintrc], using Default rules at:[/action/lib/.automation/.dockerfilelintrc]
  -> Codebase does NOT have file:[.github/linters/.tflint.hcl], using Default rules at:[/action/lib/.automation/.tflint.hcl]
```

**Comment by marbar3778** [comment]
hey this is awesome!! is the change in a releasee already?
