### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by stepancheg** [github/super-linter#1744]
If there's `.clang-format`, validate all C/C++ files with it.

I see there are linters like [clang-format-lint](https://github.com/marketplace/actions/clang-format-lint), would be nice if super-linter supported it out of the box.

Note I've created a similar [feature request in cpplint tracker](https://github.com/cpplint/cpplint/issues/180), but I'm not sure that cpplint wants it.

**Comment by admiralAwkbar** [comment]
@stepancheg Very cool... Will look into seeing if this is a good fit

**Comment by admiralAwkbar** [comment]
@stepancheg Hey this looks interesting

It seems we could install through alpine clang but the size is roughly 40Mb... seems a bit heavy to add to the linter as it's already a little on the bloated side.

If this can be done in a smaller presence I think we would have no objections, but currently were trying to keep the image size down

**Comment by stepancheg** [comment]
@admiralAwkbar on my mac laptop `clang-format` binary is 7Mb. On my linux server it is 2Mb. Both of them are binaries which do not dynamically linked on any LLVM shared libraries, only on common `.so` files like `libtinfo.so.6`.

So the problem is finding where to fetch a small binary from? What size would be appropriate?

**Comment by admiralAwkbar** [comment]
@stepancheg that's interesting, I was looking at install from alpine, and was 40~ MB

What was the process to install on your Linux server? Documentation was a bit rough :)

**Comment by admiralAwkbar** [comment]
@stepancheg Since we already have many of the c++ libs, i would imagine we don't need much to make this work

**Comment by stepancheg** [comment]
I don't know how exactly it came to my server. I tried this: download prebuilt for Ubuntu 16 from the [release page](https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.0).

Binary size is 2M. List of linked libraries is:

```
$ ldd ./bin/clang-format
	linux-vdso.so.1 (0x00007ffdd69dc000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f52153f3000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f52151eb000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f5214fe7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f5214c65000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f5214a4e000)
	libtinfo.so.5 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f52146b9000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f52144a1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f52140dc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5215613000)
```

so no dependencies on LLVM, but there are dependencies on system libraries. And it didn't work on my server, because my server is not Ubuntu. And it doesn't work because of missing `libtinfo.so.5`. Going to try something else.

**Comment by stepancheg** [comment]
OK, I managed to build `clang-format` with this `Dockerfile` which I copied from some github repo and slightly modified:

```
FROM alpine:latest as clang-format-build

# Build dependencies
RUN apk update && apk add git build-base ninja cmake python3 clang

# Pass `--build-arg LLVM_TAG=master` for latest llvm commit
ARG LLVM_TAG
ENV LLVM_TAG llvmorg-12.0.1

# Download and setup
WORKDIR /build
RUN git clone --branch ${LLVM_TAG} --depth 1 https://github.com/llvm/llvm-project.git
WORKDIR /build/llvm-project

# Build
WORKDIR llvm/build
RUN cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_STATIC=ON -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
RUN ninja clang-format

# Install
FROM alpine:latest

WORKDIR /workdir

COPY --from=clang-format-build /build/llvm-project/llvm/build/bin/clang-format /usr/bin

ENTRYPOINT ["clang-format"]
CMD ["--help"]
```

Resulting `clang-format` binary is 4M and it is completely statically linked, not even dependency on libc (which is probably overkill, since it is built on alpine and to be executed on alpine).
