### ISSUE TITLE
Release for latest version of super-linter

### ISSUE THREAD

**Issue by RobCannon** [github/super-linter#1749]
Is there a reason that the latest super-linter docker image does not have a version tag on it?  We are seeing vulnerabilities in the @v4.2.2 that are resolved in the @latest version.  But we have a policy against using @latest for container images.

**Comment by admiralAwkbar** [comment]
@RobCannon Hey! 

Every time we push to `master/main` that gets the `latest` tag.
Its not until we push a release that its moved up for all else.
We had some issues with `pip` and `R` that made it take a while to get back on track...
As you can see, I merged up like 20 Prs today after getting it fixed :)

So I will be pushing a new release update in a few min :)

thanks for the heads up!

**Comment by RobCannon** [comment]
Thanks for the update!
