### ISSUE TITLE
auto determine image to use

### ISSUE THREAD

**Issue by yxliang01** [github/super-linter#1770]
**Is your feature request related to a problem? Please describe.**
Slim image is perfect when the excluded languages are not validated anyways, e.g. the codebase doesn't have any excluded sources. But, over time, it's possible that new source files are added and some of them are written in excluded languages. What's better than every user in such situation manually switches their image from slim to the normal one is to automatically detect and switch done by super-linter.

**Describe the solution you'd like**
An easy solution is to see whether `VALIDATE_*` are specified, so the exact set of languages wanted to be validated is explicitly specified. Determine image by using that info. This might be doable in action-level. Another solution is to have a script do this, and so `docker` is called by the script, not directly by the action.
This solution can also resolves #1690 .

**Describe alternatives you've considered**
A better approach is to compute all files to be validated outside of docker, then determine the image, but this would base on the second solution above and requires slightly more work although shouldn't be much.

**Comment by admiralAwkbar** [comment]
@yxliang01 Hey! Very valid points.

So a few things to clarify:

## action.yml not interpolated
Currently, the `action.yml` is pulled in by the **GitHub Actions** infra, but is not interpolated at run time.
This means we cannot pass a variable for the container image and choose the correct action...

## Possible ideas
- We could let the user know if a language is detected in the full-size **Super-Linter** while using the `slim` image, we could raise an error or warning letting them know they should switch images to gain additional testing

**Comment by yxliang01** [comment]
Unsure whether action is not interpolated, the testing error posted in #1690 seems more like that `inputs` is undefined. But, even then, the proposed second solution can surely work, this is what's done by many actions.
A message printed by `slim` is a viable improvement, but I think it's not better than just auto determine the image since I think the encapsulation is what super-lints all about, users shouldn't even need to know. Actually, in some issues you mentioned that you guys are thinking about more specific images, so maybe the proposed second solution is a path towards it.

**Comment by yxliang01** [comment]
Hey @admiralAwkbar , I've looked at the action runner source code and indeed seems that `image` name can't be interpolated. But, we still have alternatives - changing the action to use composite or JS to determine image name, then manually run `docker run`. Given the current run-time of super-linter, the overhead of extra steps can be ignored (referred as second solution in my previous comments).

**Comment by yxliang01** [comment]
@admiralAwkbar As per above, this is definitely feasible. If the team doesn't have manpower for this, I would be happy to contribute, if it's confirmed that the PR will be merged as long as well written.

**Comment by admiralAwkbar** [comment]
@yxliang01 Hey would love a PR to help get this rolling
if you can get that, when I have available cycles I can try to contribute as well...
Has been a busy few weeks out here :)

**Comment by yxliang01** [comment]
Hi, I've just tried to use the slim image recently. But found that the time to get the image is actually not very different from the full image... And, also tried to evaluate the effort to achieve this which seems considerably nontrival. So, I'm afraid this might not be a priority for me for now, sorry about this. Instead, looking into how to further speedup getting slim image can be a lot more important to me. Sorry again.

**Comment by admiralAwkbar** [comment]
@yxliang01 Appreciate the effort on this...
I'm always looking for more ways to help speed up this process and appreciate all the help you have given

thank you!
