### ISSUE TITLE
Java's sun_checks.xml

### ISSUE THREAD

**Issue by Mr-Coxall** [github/super-linter#1772]
Is there a reason it is not checking for 4 spaces on indenting?

**Comment by admiralAwkbar** [comment]
Hey @Mr-Coxall 
I believe another user help implement this linter and helped get the `sun_checks.xml` file committed.
If the default behavior should be `4` spaces, can you update the base `TEMPLATES/sun_checks.xml` in a PR?

I would be glad to update if that's the case
