### ISSUE TITLE
Eslint fails cuz can't install plugin eslint-vue-plugin 

### ISSUE THREAD

**Issue by m7salam** [github/super-linter#1774]
Hi all, 

I have faced that the eslint when pointing to my own .eslintrc.js file doesn't recognize the dependandacy 

what I did to overcome is that I added npm install on the steps before the lining process

but I'm not so sure if this is the best way or if there is a way that I should follow that i didn't notice

would appreciate it

thanks

**Comment by apisTrg93** [comment]
Assalamualaikum wbt selamat malam

**Comment by admiralAwkbar** [comment]
@m7salam we shoudl probably have vue installed...
will add that to the docker image

**Comment by m7salam** [comment]
if its possible to add this as well "eslint-plugin-nuxt" 

cuz usually nuxt and vuejs go together so it all can be covered

thanks
