### ISSUE TITLE
Improper error message

### ISSUE THREAD

**Issue by santhoshar-bt** [github/super-linter#1789]
## The error message displayed was not helpful

Superlinter threw an error when linting '.sh' files we had in our repo. The error was not helpful in fixing the issue. The error we were receiving was "**Found errors in [shfmt] linter! Error code: 1. Command output**". There was no clue on what the actual issue was with the file.

On further digging, we figured out the issue to be with the shfmt formatting of the file (We had to install SHFMT on our machines to troubleshoot the actual issue). Once we formatted the file using shfmt, we were able to overcome this error.

## Expected behavior

A clear and concise message explaining what the actual error is.

**Comment by admiralAwkbar** [comment]
@santhoshar-bt 

I'm sorry you were not able to find the good output of the issues that were found

Usually, you can search the log for `[error]` and it will pull up the lines that failed linting

Can you show the log where the errors were received?

thanks!

**Comment by santhoshar-bt** [comment]
@admiralAwkbar 
Thanks for getting back @admiralAwkbar . I am attaching the screenshot of the logs that we were seeing. 
![Logs](https://user-images.githubusercontent.com/83311392/126364478-0260d185-aa47-4d17-975e-583485910b6b.png)
As you can see the logs were not particularly helpful looking the error message. 

Thanks!

**Comment by admiralAwkbar** [comment]
@santhoshar-bt 
It appears it's showing the error message with the `-` and `+` symbols on the side of the output in `diff` format.

I will agree the `diff` format is somewhat tricky to read... Looking over `shft` there is no other supported output at this time...

Do you have any ideas for a better output format that could be helpful?

**Comment by santhoshar-bt** [comment]
@admiralAwkbar 
yes, the `diff` formatting was tricky to understand. 

Since there is no other supported output format, Is it possible to change the error description as I feel that, it is not adding any value in easily figuring what the problem is.
