### ISSUE TITLE
Add directory/file ignore support to option

### ISSUE THREAD

**Issue by dickiesanders** [github/super-linter#179]
**Is your feature request related to a problem? Please describe.**
Currently, the RUN_LOCAL option only supports linting of an entire directory or file.

**Describe the solution you'd like**
It would be useful to have a **.ignore** or **.lintignore** file, similar to _.dockerignore_ or _.gitignore_ files, where a user can list files and folders to ignore in a large multi-language repo/project.

**Comment by wangkuiyi** [comment]
I second @dickiesanders . It would look good to me if super-linter reuses `.gitignore`.

**Comment by stefdworschak** [comment]
This would be really useful!

**Comment by nemchik** [comment]
This might be easily accomplished by using something similar to `git ls-tree -r HEAD` to list files. This would only bring in files NOT ignored by `.gitignore`.

**Comment by jberkers42** [comment]
Would be very useful indeed.  I do not agree that it should use `.gitignore` as this would not make a difference in a CI pipeline integrated with a Git Repo, as Git would already not include it in any commits.

**Comment by rolfkleef** [comment]
In addition to `.gitignore` it might make sense to also ignore paths in `.gitmodules`? I'm only getting linter errors on libraries I have no control over.

**Comment by srcshelton** [comment]
> Would be very useful indeed. I do not agree that it should use `.gitignore` as this would not make a difference in a CI pipeline integrated with a Git Repo, as Git would already not include it in any commits.

As the original author or someone developing the code in the repo, groups of files which are `.gitignore`d and groups of files you don't want to lint probably have a high degree of intersection.

On balance, though, I think I agree that a separate `.super-linter.ignore` or similarly named control-file is the more flexible option less likely to bite in the future.

(But also, it's a great suggestion to ignore anything below a path specified in `.gitmodules` by default)
