### ISSUE TITLE
published actions are always one version behind

### ISSUE THREAD

**Issue by yxliang01** [github/super-linter#1795]
## Describe the bug

e.g. action with tag `v.4.5.1` is using the `v.4.5.0` image.
## Expected behavior
action version should be same as the image version.

## Steps to Reproduce
Just manually check the `action.yml` under tag `v4.5.1`

## Additional context

Seems to be caused by the fact that the GitHub release is created **before** the update of `action.yml`

**Comment by admiralAwkbar** [comment]
@yxliang01 
Hey thanks for the catch!

There was a bug in the 4.5.0 release and that was nice and broke...

The 4.5.1 should be on track as the release works as follows:

- Create a release
- it checks out the code and updates the `action.yml` to the correct version
- It then creates PR with updated code to reflect it
- Branch is merged and all code should be up to date

**Comment by massongit** [comment]
Regarding the release work, if you do not do `Create a release` at the end, the version of GitHub Actions and the docker image may be out of sync.
