### ISSUE TITLE
How would other linters eg sqlfluff be added to this tool?

### ISSUE THREAD

**Issue by dbrtly** [github/super-linter#1812]
**Is your feature request related to a problem? Please describe.**
I like the elegance of running all linters the same way. But the tool isn't compatible with all linters. If a user wanted to add another linter (eg. sqlfluff), is that even possible?

**Describe the solution you'd like**
Instructions on how to extend compatibility with other linters.

**Describe alternatives you've considered**
Alternative is to not use super-linter for some use cases. But then it is no longer "one linter to rule them all".

**Additional context**
None today. 

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

Why did you bury the above link down here? You could have put it in the readme. I wonder if it answers my question.

**Comment by admiralAwkbar** [comment]
@dbrtly Sorry about that, im guessing that should be better linked in the repo :)

Not familiar with SQfluff but looks pretty cool :)

If you can create a branch and PR I can help along the way if you get stuck :)

**Comment by nvuillam** [comment]
@admiralAwkbar if you wanna add sqlfluff, the recipe is here :)
https://www.github.com/nvuillam/mega-linter/tree/master/megalinter%2Fdescriptors%2Fsql.megalinter-descriptor.yml
