### ISSUE TITLE
add instructions for running super-linter as a pre-commit

### ISSUE THREAD

**Issue by ben-marengo-msmg** [github/super-linter#1831]
**Is your feature request related to a problem? Please describe.**
id like to [run the super-linter locally](https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md), but as part of a [pre-commit](https://pre-commit.com/).

the benefit here is that the github action and the pre-commit both do the same thing

**Describe the solution you'd like**
it would be great to add directions to that page

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by admiralAwkbar** [comment]
@ben-marengo-msmg 
Hey!
I'm guessing you're trying to run a local pre-commit in your local environment or on GitHub Enterprise server?

The only side effect I could see would be a long pre-commit wait times.
I know most places try to run in under 5 seconds... the super linter would dominate that timeout :)

**Comment by ben-marengo-msmg** [comment]
hey @admiralAwkbar 
> run a local pre-commit in your local environment
yep

> long pre-commit wait times
true. do you know what strategies to people generally use to work around issues where pre-commit passes locally, then superlinter fails on github? purely because there are extra linters running in superlinter. do people just manually add and maintain each individual linter in the pre-commit?
