### ISSUE TITLE
Comment errors

### ISSUE THREAD

**Issue by massongit** [github/super-linter#1840]
I want super-linter to create pull request comments about the result of linters that caused errors.
If super-linter can do it, linter errors will be easier to see.

**Comment by nvuillam** [comment]
Something like that ? :)

You may convert my [python code](https://github.com/nvuillam/mega-linter/blob/master/megalinter/reporters/GithubCommentReporter.py) into bash ^^

[![image](https://user-images.githubusercontent.com/17500430/130142337-d25021fd-c23b-4fbb-ae40-db7803c95805.png)](https://nvuillam.github.io/mega-linter/reporters/GitHubCommentReporter/)
