### ISSUE TITLE
https://github.com/github/docs/pull/8958#issue-708953675

### ISSUE THREAD

**Issue by amirnateghi1980** [github/super-linter#1859]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by Quasic** [comment]
Why revert?

Here's how we usually link: github/docs#8958
