### ISSUE TITLE
Add non-root user to image

### ISSUE THREAD

**Issue by sanmai-NL** [github/super-linter#1861]
**Is your feature request related to a problem? Please describe.**
When one uses super-linter as VS Code dev container, VS Code tries to run the container as the `USER` specified in the upstream Dockerfile, otherwise it defaults to `root`. Your Dockerfiles currently don't contain `USER` and don't add a non-system user in the first place. So, VS Code ends up running the container as root. Now, when some directory is bind-mounted from the host system into a super-linter container (e.g., the workspace dir with `.git/`), this results in file ownership being 0/`root`.

**Describe the solution you'd like**
Add a non-system user to the Dockerfiles, as suggested in the problem description.

**Describe alternatives you've considered**
Adding a such a user myself in a an extra layer. This means other super-linter users will continue running it needlessly as superuser (e.g., under CI).

**Comment by admiralAwkbar** [comment]
@sanmai-NL 
We need to work on this more as it made a ton of permission issues...
Since the container runs from `/` it wouldn't be great to give the user `super-linter` that access but maybe move some stuff around

**Comment by sanmai-NL** [comment]
Can you give a log of what issues? Normal user accounts can read files under /.

**Comment by sanmai-NL** [comment]
@admiralAwkbar Ping.

**Comment by admiralAwkbar** [comment]
@sanmai-NL Hey
It seems it tries to install additional libs at run time for various linters.

Since all is owned by root, and the user is `docker` it fails to install any run time libs.

Would need someone with some time to test and build

**Comment by admiralAwkbar** [comment]
Also marked not stale to help prevent this from closing again

**Comment by sanmai-NL** [comment]
Is such runtime installation truly needed? If so, must the installation be global?

**Comment by admiralAwkbar** [comment]
hey @sanmai-NL 
For some linters it needs to look at a local file and install some local libs... i think `go` was one of them.
Since the linter starts and runs from `/` we need to take time and make those folders open so it can install.
It can be done, but needed time, and running short on that now

**Comment by sanmai-NL** [comment]
Not stale.
