### ISSUE TITLE
Upgrade Black

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/super-linter#1891]
**Is your feature request related to a problem? Please describe.**
The latest version of Black supports the latest version of Python, 3.9. The version of Black in use by Super-Linter only supports Python 3.8.

**Describe the solution you'd like**
Upgrade to the latest version of Black. Ideally, ensure that Dependabot is able to upgrade Black by itself.

**Describe alternatives you've considered**
Is there a way I can upgrade the version of Black that Super-Linter uses myself?

**Additional context**
```
2021-08-24 21:48:39 [ERROR]   Found errors in [black] linter!
2021-08-24 21:48:39 [ERROR]   Error code: 2. Command output:
------
Usage: black [OPTIONS] [SRC]...
Try 'black -h' for help.

Error: Invalid value for '-t' / '--target-version': invalid choice: py39. (choose from py27, py33, py34, py35, py36, py37, py38)
------
```

**Comment by admiralAwkbar** [comment]
@Kurt-von-Laven  i think we are pulling in the latest version of black.

from the Dockerfile:
```dockerfile
&& wget --tries=5 -q -O /usr/local/bin/black https://github.com/psf/black/releases/download/21.7b0/black_linux \
    && chmod +x /usr/local/bin/black
```

after looking at https://github.com/psf/black that seems to be the latest release and was dropped July 14..

Wondering if I need to bump the release to see if that is all resolved

**Comment by admiralAwkbar** [comment]
@Kurt-von-Laven Just cut a new release can you verify all is well?

**Comment by Kurt-von-Laven** [comment]
@admiralAwkbar, that fixed it. Thank you!

**Comment by Kurt-von-Laven** [comment]
@admiralAwkbar, I believe this issue can be closed.
