### ISSUE TITLE
Latest release (4.6.3 or maybe 4.7.0?) not available on Docker.

### ISSUE THREAD

**Issue by tunetheweb** [github/super-linter#1913]
## Describe the bug

Dependabot [tried to upgrade me to 4.6.3](https://github.com/HTTPArchive/httparchive.org/pull/423) but weirdly tried to use 4.7.0, but it wasn't available:

![image](https://user-images.githubusercontent.com/10931297/131538924-0a87bbdd-1f99-44b5-97d2-d58de1396108.png)

```
11s
Pull down action image 'ghcr.io/github/super-linter:v4.7.0'
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.7.0
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 4.638 seconds before retry.
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.7.0
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 4.765 seconds before retry.
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.7.0
  Error response from daemon: manifest unknown
Error: Docker pull failed with exit code 1
```

Can't see 4.63. in the [Releases page](https://github.com/github/super-linter/releases).

Then I set it to 4.7.0 but that also didn't work

```
45s
Current runner version: '2.280.3'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `github/super-linter@v4.7.0`, unable to find version `v4.7.0`
Retrying in 15.534 seconds
Failed to resolve action download info. Error: Unable to resolve action `github/super-linter@v4.7.0`, unable to find version `v4.7.0`
Retrying in 28.264 seconds
Error: Unable to resolve action `github/super-linter@v4.7.0`, unable to find version `v4.7.0`
```

## Expected behavior

Using an explicitly version number in a GitHub action should work but neither of these work:

```
        uses: github/super-linter@v4.6.3
```
Or
```
        uses: github/super-linter@v4.7.0
```

Possibly related to #1839 ?

**Comment by tunetheweb** [comment]
Same issue with 4.7.1

**Comment by dbergman24** [comment]
we have the same issue

**Comment by admiralAwkbar** [comment]
@tunetheweb @dbergman24 Trying to resolve it now... Seems an internet outage during the build really beefed it...
I wish automation would work somedays :)

**Comment by admiralAwkbar** [comment]
trying to push missing images now...

**Comment by admiralAwkbar** [comment]
@tunetheweb  @dbergman24 Images shoudl now be showing up online... Sorry for any downtime this caused... was not a fun issue to solve...

But on a higher note... I was able to solve the versioning issue on being back 1 version... So from now on this should be fully resolved.
Hope all is well on the other side of the internet :)

**Comment by tunetheweb** [comment]
Unfortunately still seeing it:
https://github.com/HTTPArchive/httparchive.org/pull/423/checks

Should I be using 4.7.1 or 4.7.0?

**Comment by admiralAwkbar** [comment]
![Screen Shot 2021-08-31 at 1 43 27 PM](https://user-images.githubusercontent.com/29484535/131558498-b3a64e54-212d-4fd7-b703-7a70ba72eef7.png)

@tunetheweb  Can you check again? it was still uploading when I was saying it was resolved :)

**Comment by admiralAwkbar** [comment]
![Screen Shot 2021-08-31 at 1 44 54 PM](https://user-images.githubusercontent.com/29484535/131558681-41a73074-60f3-4fb2-a1a2-50f14ca90119.png)

**Comment by tunetheweb** [comment]
Same thing I’m afraid. Btw I’m using the GitHub url if that makes a difference?

```yml
uses: github/super-linter@v4.7.1
```

**Comment by admiralAwkbar** [comment]
@tunetheweb  seems a tagging issue now...

if you use
```yml
uses: github/super-linter@v
```

that works!

but if I do what you have I get the error

Resolving that now :)

**Comment by admiralAwkbar** [comment]
@tunetheweb I think the tags have been created now :)
Tested as well and got success...
This gets crazy when automation fails!

**Comment by tunetheweb** [comment]
Looking good now. And does seem to have resolved the version-1 issue too! 🎉

**Comment by admiralAwkbar** [comment]
@tunetheweb awesome! sorry for any outage this caused... has not been a great Tuesday but there is light at the end of the tunnel...

**Comment by tunetheweb** [comment]
No outage for me. Just some dependabot PRs that couldn’t be merged.

That’s why I like to version lock to specific version and let dependabot upgrade, so stick to old version until I know the new one is good. So glad you solved the version-1 issue here as that was a bit annoying when I wanted the new version as dependabot only worked when using the GitHub (instead of Docker) URL and with a specific version.
