### ISSUE TITLE
Annoying email alert when commenting on issues

### ISSUE THREAD

**Issue by tunetheweb** [github/super-linter#1918]
## Describe the bug

Keep getting an email with the when commenting on issues:

![77E295E7-3FDE-4243-98D4-A09BC0DE00CB](https://user-images.githubusercontent.com/10931297/131561279-5d2f1218-77d7-4ab7-80f5-b6c4a1311eb9.jpeg)

## Steps to Reproduce

Comment on an issue.
Look at your email.

Not sure if specific to non-maintainers?

**Comment by admiralAwkbar** [comment]
@tunetheweb Thats really odd, seems an issue with `stale`?
I don't really see the emails, or they are probably in my junk folder as I get wayyyyy to many...
i tried to look over `actions/stale` but didn't see anything about this issue... Ill try to look around
