### ISSUE TITLE
Psalm not running 

### ISSUE THREAD

**Issue by tylervz** [github/super-linter#1920]
## Describe the bug

Despite Psalm running fine locally in my project with `./vendor/bin/psalm -c .github/linters/psalm.xml`, the following error is output for each PHP file Psalm checks when the Super-Linter runs:

```text
Could not find any composer autoloaders in /github/workspace/
Add a --root=[your/project/directory] flag to specify a particular project to run Psalm on.
```

I am using Mac OS 11.4 and PHP v7.4.23 . For Super-Linter I am using `docker://ghcr.io/github/super-linter:slim-v4`.

I have created a [sample repo](https://github.com/tylervz/php-lint-example) to demonstrate the issue. This [this run of the Super-Linter](https://github.com/tylervz/php-lint-example/runs/3487479266?check_suite_focus=true) in my repo demonstrates the issue.

## Expected behavior

Psalm should outline coding issues in PHP files or have no error output at all.

## Steps to Reproduce

When running super-linter locally in my sample repo on the `master` branch like so, Psalm ran properly without any errors:

```
docker run \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=.github/linters \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -v $(pwd):/tmp/lint \
  ghcr.io/github/super-linter:slim-v4.7.1
```

However, when I deleted the `vendor` directory (which contains all the PHP dependencies defined in `composer.json`)
and ran the same `docker run` command again, then the familiar error appeared:
```
2021-09-01 18:57:59 [DEBUG]   File: /tmp/lint/tests/ServerTest.php, FILE_NAME: ServerTest.php, DIR_NAME:/tmp/lint/tests, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: php_psalm
2021-09-01 18:57:59 [INFO]   ---------------------------
2021-09-01 18:57:59 [INFO]   File:[/tmp/lint/tests/ServerTest.php]
2021-09-01 18:57:59 [DEBUG]   Found errors. Error code: 1, File type: PHP_PSALM, Error on missing exec bit: true
2021-09-01 18:57:59 [ERROR]   Found errors in [psalm] linter!
2021-09-01 18:57:59 [ERROR]   Error code: 1. Command output:
------
Could not find any composer autoloaders in /tmp/lint/
Add a --root=[your/project/directory] flag to specify a particular project to run Psalm on.
------
2021-09-01 18:57:59 [DEBUG]   Error code: 1. Command output:
------
Could not find any composer autoloaders in /tmp/lint/
Add a --root=[your/project/directory] flag to specify a particular project to run Psalm on.
------
```

So it seems the issue is that `composer install` is not being run by the super-linter.
I suspected this was the issue based on my preliminary searching leading me [here](https://github.com/mickaelandrieu/psalm-ga/issues/2). However, I was unable to fix the problem by adding that step to the workflow because the `composer` Docker image uses PHP 8, and I think the `composer install` step should be run by super-linter anyways.

The steps to reproduce the issue locally are:

1. Clone my sample repo: `git clone git@github.com:tylervz/php-lint-example.git`
1. Do NOT install the defined dependencies with Composer.
1. Run 
```
docker run \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=.github/linters \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -v $(pwd):/tmp/lint \
  ghcr.io/github/super-linter:slim-v4.7.1
```
4. See the Psalm errors

## Logs

I have uploaded the [full output](https://gist.github.com/tylervz/140401f40681357c9c5dd168ddd8efd6)
of the local `docker run` that had the errors in case it is of any use.

**Comment by admiralAwkbar** [comment]
Hey @tylervz 
If i understand you:

Does the `composer install` need to happen when the container is first built?
Or does it need to run once it finds PHP code in the run, the run the `composer install`
Sorry PHP is not my strong area :)

**Comment by tylervz** [comment]
Hi @admiralAwkbar 

That's a good question. `composer install` will need to happen during the run if `VALIDATE_PHP_PSALM` is true. Looking at this other pull request, I would have guessed it should [occur here in `linter.sh`](https://github.com/github/super-linter/pull/478/files#diff-0b89e6e14353371aacf69d4b9067d4481dd99c6994409b32e3b906c69d478c21R1532-R1537), but that code section is no longer in [`linter.sh`](https://github.com/github/super-linter/blob/master/lib/linter.sh).

**Comment by admiralAwkbar** [comment]
@tylervz Nice... I will try to find some time, likely friday this week to get a fix in place

thanks for the debugging!~

**Comment by tylervz** [comment]
Thank you @admiralAwkbar !
