### ISSUE TITLE
Tags and Releases are out of sync

### ISSUE THREAD

**Issue by JonZeolla** [github/super-linter#1921]
Note that the tag is v4.6.4 but the release is v4.7.1.

<img width="660" alt="Screen Shot 2021-09-01 at 5 50 34 PM" src="https://user-images.githubusercontent.com/1385510/131750042-b4120e63-7a75-418b-954f-5d1192b317dc.png">

**Comment by MuohamedAbdulwhab** [comment]
> Note that the tag is v4.6.4 but the release is v4.7.1.
> 
> <img width="660" alt="Screen Shot 2021-09-01 at 5 50 34 PM" src="https://user-images.githubusercontent.com/1385510/131750042-b4120e63-7a75-418b-954f-5d1192b317dc.png">
>

**Comment by admiralAwkbar** [comment]
Hey, @JonZeolla  @MuohamedAbdulwhab  Thanks for the catch!
We had a huge failure the other day when updating the release process and this got really out of control... also didn't help I was booked out and didn't have to dedicate myself to resolving this.

Should be fixed now and sorry for any issues this may have caused. Hope all is well out there!
