### ISSUE TITLE
How do mypy stubs get specified for super-linter?

### ISSUE THREAD

**Issue by jamiet-msm** [github/super-linter#1922]
We have been using super-linter successfully on our project for many months. We are currently using github/super-linter@v4:

```yaml
  super-lint:
    name: Lint Code Base
    runs-on: [ self-hosted, ubuntu, dataplatform ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          FILTER_REGEX_EXCLUDE: (docs|.devcontainer|.*gradlew|.*gradlew.bat) #try different combinations here if needed https://regex101.com/r/iOF1SP/1
          VALIDATE_SQLFLUFF: false
```

Yesterday I pushed this python code to our repo:

```python
import pytz
#
# some stuff
# ...
#
var_name = datetime.now(pytz.UTC)
```

And the super-linter job failed with error:

```default
2021-09-03 07:59:17 [INFO]   File:[/github/workspace/dataplatform/tests/features/RealTimeEventProcessing/environment.py]
2021-09-03 07:59:18 [ERROR]   Found errors in [mypy] linter!
2021-09-03 07:59:18 [ERROR]   Error code: 1. Command output:
------
path/to/file.py:4: error: Library stubs not installed for "pytz" (or incompatible with Python 3.9)
path/to/file.py:4: note: Hint: "python3 -m pip install types-pytz"
path/to/file.py:4: note: (or run "mypy --install-types" to install all missing stub packages)
path/to/file.py:4: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

As far as I know there is no incompatibility with python9. Hence my question is, how are mypy stubs made available to super-linter and what needs to be done to make types-pytz available?

---

Background reading, mypy stubs: https://mypy.readthedocs.io/en/stable/getting_started.html#stubs-intro

**Comment by admiralAwkbar** [comment]
@jamiet-msm My best guess is one we  got to the newer version of mypy we hit this issue:
```
Starting in mypy 0.900, most third-party package stubs must be installed explicitly. This decouples mypy and stub versioning, allowing stubs to updated without updating mypy. This also allows stubs not originally included with mypy to be installed. Earlier mypy versions included a fixed set of stubs for third-party packages.
```

Im guessing we need to do some checks to install stubs at this point?

**Comment by jamiet-msm** [comment]
@admiralAwkbar Seems that way, yes. I admit to not being particularly fluent with mypy so not too sure about such nuances. What do you mean "checks" exactly?

**Comment by admiralAwkbar** [comment]
@jamiet-msm I'm guessing if we find python files in the user's code base that need to be parsed, we parse the files for `import xyz` then try to install, the run the linter against it?

**Comment by jamiet-msm** [comment]
That seems like a lot of work to do in a linter!! And who's to say that the module matches the name of the package that needs to be installed? That might be a false assumption.

**Comment by admiralAwkbar** [comment]
It looks like #1937 Might have been the answer to solve this!

**Comment by jamiet-msm** [comment]
Thx for letting me know @admiralAwkbar
