### ISSUE TITLE
Make writing changelogs easier

### ISSUE THREAD

**Issue by zkoppert** [github/super-linter#203]
**Is your feature request related to a problem? Please describe.**
Running through git logs or closed pull requests is not ideal as its manual.

**Describe the solution you'd like**
Use something like [release drafter](https://github.com/apps/release-drafter) to help draft the releases so we can just review for accuracy.

**Describe alternatives you've considered**
- https://github.com/marketplace/actions/automatic-changelog-generator
- https://github.com/CookPete/auto-changelog
- https://github.com/github-changelog-generator/github-changelog-generator

**Additional context**
We should discuss pros and cons of the alternatives vs the suggested release drafter.

**Comment by zkoppert** [comment]
@admiralAwkbar Thoughts on this? Prefer to keep this manual or use the release drafter?

**Comment by admiralAwkbar** [comment]
@zkoppert im bout all that automation life...
