### ISSUE TITLE
Bump actionlint to v1.6.6 in order to get support for workflow_call trigger 

### ISSUE THREAD

**Issue by kamimanzoor** [github/super-linter#2065]
Right now the latest version of superlinter (v4, v4.8.1) seems to be using actionlint version 1.6.4 which is making the linter to fail on workflow_call as can be seen below:
![image](https://user-images.githubusercontent.com/16157737/138529893-61354445-dec7-4a50-a08a-655d3dce45f4.png) 

The support for workflow_call trigger is being added in [v1.6.6 version](https://github.com/rhysd/actionlint/releases/tag/v1.6.6) 

Please publish a new docker image with updated actionlint version

**Comment by dacbd** [comment]
https://github.com/rhysd/actionlint/releases/tag/v1.6.8

includes additional context vars added to `github.*`

**Comment by ferrarimarco** [comment]
We now ship version 1.6.8.
