### ISSUE TITLE
Should Support *-lint.yaml Files

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [github/super-linter#208]
**Describe the bug**
`.yaml` is the official extension for YAML files (https://yaml.org/faq.html), then configuration files must either enforce it or at least allow its use. Creating a `.yaml-lint.yaml` or any other `*-lint.yaml` doesn't work on current implementation. Some projects have guidelines and lint configurations that forbid use of the `.yml` file extension, thus not allowing a `.yaml-lint.yml` file to exist.

**To Reproduce**
1. Create a `.yaml-lint.yaml` file with the correct content.

**Expected behavior**
`.yaml-lint.yaml` should be used instead of the default configuration for YAML Linter.

**Comment by Hanse00** [comment]
Great point @t0rr3sp3dr0 :)

Currently the linter.sh file hardcodes the acceptable filenames in [lines 14 through 53](https://github.com/github/super-linter/blob/master/lib/linter.sh#L14-L53).

We could either update these filenames to end on the .yaml extension, or code in some logic to permit for either extension to be used.

The first would be easier of course, the second seems to me like the right solution 😄

**Comment by admiralAwkbar** [comment]
@t0rr3sp3dr0 agreed.. I will work it to allow for both... :)

**Comment by t0rr3sp3dr0** [comment]
remove stale label

**Comment by GaboFDC** [comment]
We now allow to set the `YAML_CONFIG_FILE` variable, I think that solves the issue.
We are also linting both `.yaml` and `.yml` files

**Comment by t0rr3sp3dr0** [comment]
Indeed @GaboFDC
