### ISSUE TITLE
Invite To Collaborate With Mega-Linter

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/super-linter#2090]
Moving discussion from #1619 where I originally posted this to avoid overrunning that thread.

> I realize this is an optimistic proposal, but I wonder whether Super-Linter would have any interest in joining forces with [Mega-Linter](https://megalinter.github.io/) in some way? I don't have a pre-conceived notion of how such a collaboration would work, but I am hoping to initiate a dialogue (and happy to move this discussion to a more appropriate forum as desired).
> 
> Here are some of [the major highlights](https://megalinter.github.io/mega-linter-vs-super-linter/): 
> - Ported from Bash to Python.
> - Extends [the slim image concept](https://github.com/github/super-linter#slim-image) to [a wide variety of reusable flavors](https://megalinter.github.io/flavors/) to minimize download time.
> - Runs linters in parallel for faster performance.
> - Batches files for linters that support it for faster performance (and correctness in the case of jscpd as discussed above).
> - Can automatically apply the fixes of those linters that support it.
> - Offers [a local runner](https://megalinter.github.io/mega-linter-runner/) (made feasible by flavors) if you don't want to wait in a CI queue or desire to run linters as a [pre-commit](https://pre-commit.com/) hook.
> - Supports multiple report formats (automatically stored as artifacts by [the accompanying GitHub Action](https://github.com/marketplace/actions/mega-linter)).
> - Offers a CLI installation and configuration assistant.
> - Has enhanced documentation.
> - Generates recommended IDE extensions.
> - Supports plugins for less widely used linters.
> - Features a simplified architecture to reduce maintenance burden and increase automation.
> - Has [87% test coverage](https://app.codecov.io/gh/megalinter/megalinter).
> 
> That being said Super-Linter has GitHub's brand recognition and backing, which means greater visibility, more users, more contributors, more maintainer FTEs, more stars, etc. It is worth noting that Mega-Linter is licensed AGPL-3.0, while Super-Linter is licensed MIT, so some legal consideration would need to be put into any effort to collaborate or unite them. Since Mega-Linter began as a hard fork of Super-Linter (#791), there is a great deal of overlap between the two's supported linters. I have summarized the differences below.
> 
> Super-Linter (but not Mega-Linter) includes:
> - [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
> - [eslint-plugin-json](https://github.com/azeemba/eslint-plugin-json#readme)
> - [gitleaks (credentials)](https://github.com/zricethezav/gitleaks#readme)
> - [google-java-format](https://github.com/google/google-java-format#google-java-format)
> - [rustfmt](https://github.com/rust-lang/rustfmt#readme)
> - [textlint (natural language)](https://textlint.github.io/)
> 
> Mega-Linter (but not Super-Linter) includes:
> - [bandit (Python security)](https://bandit.readthedocs.io/en/latest/)
> - [checkov (Terraform, CloudFormation, Kubernetes, Helm, ARM Templates, and Serverless)](https://www.checkov.io/)
> - [cspell (spelling)](https://cspell.org/)
> - [git-diff (merge conflict markers)](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---check)
> - [graphql-schema-linter](https://github.com/cjoudrey/graphql-schema-linter#readme)
> - [jsonlint](https://github.com/zaach/jsonlint#readme)
> - [markdown-link-check](https://github.com/tcort/markdown-link-check#readme)
> - [markdown-table-formatter](https://github.com/nvuillam/markdown-table-formatter#readme)
> - [misspell (spelling)](https://github.com/client9/misspell#readme)
> - [mypy (Python typing)](https://mypy.readthedocs.io/en/stable/)
> - [puppet-lint](http://puppet-lint.com/)
> - [remark-lint](https://github.com/remarkjs/remark-lint#readme)
> - [restructuredtext-lint](https://github.com/twolfson/restructuredtext-lint#readme)
> - [revive (Go)](https://revive.run/)
> - [rstcheck (reStructuredText syntax)](https://github.com/myint/rstcheck#readme)
> - [rstfmt (reStructuredText formatter)](https://github.com/dzhu/rstfmt)
> - [sfdx-scanner (Apex)](https://forcedotcom.github.io/sfdx-scanner/)
> - [scalafix](https://scalacenter.github.io/scalafix/)
> - [scss-lint](https://github.com/sds/scss-lint#readme)
> - [Secretlint (credentials)](https://github.com/secretlint/secretlint#readme)
> - [swiftlint](https://github.com/realm/SwiftLint#readme)
> - [terraform-fmt](https://www.terraform.io/docs/cli/commands/fmt.html)
> - [tsqllint](https://github.com/tsqllint/tsqllint#readme)
> - [v8r (JSON and YAML)](https://github.com/chris48s/v8r#readme)
> 
> There is so much overlap between the two projects that I anticipate a great deal of duplicated effort between our maintenance teams. 3 weeks after you added GitLeaks [we were asked to add it as well](https://github.com/megalinter/megalinter/issues/876). Conversely, I asked for batching support above before I learned of Mega-Linter. Going forward, I expect our communities to often request the same thing from one of us that the other just implemented. I submit that neither one of our projects alone will ever be as good as both together, and that our joint communities would be best served by our joint efforts. Disclosure: I didn't write Mega-Linter (the credit belongs to @nvuillam and many contributors), but I am a happy user that recently become the first co-maintainer.

**Comment by ferrarimarco** [comment]
Disclaimer: I contribute to super-linter, but I'm not entitled to make any call on the direction this project takes. That's a job for @admiralAwkbar and @zkoppert, I suppose.

I don't know the details about the rationale that set the outcome for #791. Of course, collaboration is always welcome, IMHO.

What would this collaboration looks like?

I suppose this heavily depends on how we plan to evolve super-linter. At minimum, there are a few features that we might take inspiration from Mega-linter tho, at least in concept.

IMHO, there are a few questions to answer about medium- and long-term plans for super-linter to outline a possible collaboration with other projects, such as (those are the ones from the top of my mind):

- Do we want to think about a roadmap of things to do for super-linter?
- Do we want to establish criteria to include new linters, and to evaluate existing ones?
- Do we want to streamline the codebase, removing redundancies and duplicated code?
- Are we using the right tools for the job, or do we care about introducing other ones?
- Do we see a differentiation between how we prepare and package super-linter, and how we run it?
- Is it worth packaging a giant container image? Given the relatively recent improvements to GitHub actions ([composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action), [reusing workflows](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows)) and tooling ([act: run GitHub actions locally](https://github.com/nektos/act)), does it still make sense to maintain the image, or maybe it would be better to use existing GitHub Actions (and build only the ones that are missing)?

But maybe we need to track these questions in different issues.

**Comment by zkoppert** [comment]
I see some benefits that the Mega-Linter has regarding performance and actually fixing the lint issues. I believe the main driver of closing #791 was that Python is not a language that we are interested in maintaining. @admiralAwkbar wrote the original code in `bash` because that is his primary language.

In terms of collaboration, We would be happy to look at having some features ported back like the performance improvements and linter fixes. We don't want to go in the direction of a codebase merge, and as @ferrarimarco touches on in his comment, we don't currently have the architecture to just pull in shared components.

Hope that clarifies things. As for @ferrarimarco's bullet points above, I think those would be great to open up each as separate issues.
