### ISSUE TITLE
Superlinter upstrem is failing

### ISSUE THREAD

**Issue by nandusekarv10** [github/super-linter#2091]
We have forked this repo and running `superlinter` in our github-actions but our builds are failing with fallowing error: 

`
buildx failed with: error: failed to solve: process "/bin/sh -c wget --tries=5 -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub     && wget --tries=5 -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk     && apk add --no-cache     bash     ca-certificates     git git-lfs     glibc-${GLIBC_VERSION}.apk     gnupg     php7 php7-phar php7-json php7-mbstring php-xmlwriter     php7-tokenizer php7-ctype php7-curl php7-dom php7-simplexml     && rm glibc-${GLIBC_VERSION}.apk     && wget -q --tries=5 -O /tmp/libz.tar.xz https://www.archlinux.org/packages/core/x86_64/zlib/download     && mkdir /tmp/libz     && tar -xf /tmp/libz.tar.xz -C /tmp/libz     && mv /tmp/libz/usr/lib/libz.so* /usr/glibc-compat/lib     && rm -rf /tmp/libz /tmp/libz.tar.xz     && wget -q --tries=5 -O phive.phar https://phar.io/releases/phive.phar     && wget -q --tries=5 -O phive.phar.asc https://phar.io/releases/phive.phar.asc     && PHAR_KEY_ID=\"0x9D8A98B29B2D5D79\"     && gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys \"$PHAR_KEY_ID\"     && gpg --verify phive.phar.asc phive.phar     && chmod +x phive.phar     && mv phive.phar /usr/local/bin/phive     && rm phive.phar.asc     && phive --no-progress install --trust-gpg-keys     31C7E470E2138192,CF1A108D0E7AE720,8A03EA3B385DBAA1,12CE0F1D262429A5     --target /usr/bin phpstan@^0.12.64 psalm@^3.18.2 phpcs@^3.5.8" did not complete successfully: exit code: 4`

- Also deploy-DEV-slim and deploy-DEV-standard are broken

- This is due to `upstrem` superlinter branch is failing and we have to stop currently 

What is timeline for this issue?

**Comment by sarahc23** [comment]
Here are some of the (maybe?) relevant lines from the build log

```
#34 20.23 Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0xCF1A108D0E7AE720
#34 20.23 Successfully downloaded key.
#34 20.28 
#34 20.28 	Fingerprint: D326 80D5 957D C711 6BE2 9C14 CF1A 108D 0E7A E720
#34 20.28 
#34 20.28 	Ondrej Mirtes <ondrej@mirtes.cz>
#34 20.28 
#34 20.28 	Created: 2019-12-09
#34 20.28 
#34 21.02 Linking /root/.phive/phars/phpstan-0.12.99.phar to /usr/bin/phpstan
#34 21.50 
#34 21.50 [ERROR]   No matching release found!
```

Also not sure if the [Alpine glibc lib](https://github.com/sgerrand/alpine-pkg-glibc) has anything to do with it, i.e.,
```
RUN wget --tries=5 -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget --tries=5 -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk \
    && apk add --no-cache \
    ...
    glibc-${GLIBC_VERSION}.apk \
```
but musl does have its own glibc compatibility library that's available in Alpine's package repository: https://pkgs.alpinelinux.org/package/edge/main/x86/libc6-compat

**Comment by admiralAwkbar** [comment]
Hey all, got it fixed

had some rel dep issues...

But looks like were back in

**Comment by nandusekarv10** [comment]
@admiralAwkbar Thank you for fixing this issue.
