### ISSUE TITLE
Receiving Failed to get [GITHUB_SHA] when running local

### ISSUE THREAD

**Issue by ericjsalazar** [github/super-linter#2117]
## Describe the bug

Receiving the following error when attempting to run this locally.

Command:
```
docker run github/super-linter:slim-latest -e RUN_LOCAL=true -v <windows_path_to_file.R>:/tmp/lint/app.R
```

Results:
```
2021-11-11 19:14:55 [INFO]   --------------------------------------------
2021-11-11 19:14:55 [INFO]   Gathering GitHub information...
2021-11-11 19:14:55 [ERROR]   Failed to get [GITHUB_SHA]!
2021-11-11 19:14:55 [FATAL]   []
```

## Expected behavior

Following the documented guide: https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md
I expect the linter to skip github checks and show any issues with linted codebase.

## Steps to Reproduce
```
docker run github/super-linter:slim-latest -e RUN_LOCAL=true -v <windows_path_to_file.R>:/tmp/lint/app.R
```

**Comment by admiralAwkbar** [comment]
@ericjsalazar so thats a bug... looking to fix it :)

**Comment by admiralAwkbar** [comment]
hey @ericjsalazar 

So not a bug... just a bad copy paste... :)

The command should be in format:

```bash
docker run -e RUN_LOCAL=true -v $(pwd):/tmp/lint github/super-linter:latest
```

As you can see, after the `run` command we need to present the variables and mount, then we give the name of the container.

In your example, its out of order and fails to register the variables.

It took me a while to realize the issue as well :)

have a great one!
