### ISSUE TITLE
Add information to a issue of deployment failure

### ISSUE THREAD

**Issue by massongit** [github/super-linter#2122]
When CI failed to deploy images, a issue is created such as https://github.com/github/super-linter/issues/2118 .
However, the only information on this issue are `Failed to deploy to production` and `Automation has failed us!`.
Therefore, it's a good idea to add informations such as commit hash and CI's URL, kind of image (standard or slim) to the issue.

**Comment by admiralAwkbar** [comment]
@massongit  agree :0 really shotting myself in the foot there
Found the issue!
Token was revoked

**Comment by admiralAwkbar** [comment]
I think i can add this and we should be good:
`${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
