### ISSUE TITLE
Image for release 4.8.3 is missing

### ISSUE THREAD

**Issue by jhagberg** [github/super-linter#2128]
## Describe the bug
Using github actions and workflow is using
 uses: github/super-linter@v4
The action script tryes to pull the latest v4 realese wich is tagged 4.8.3

Pull down action image 'ghcr.io/github/super-linter:v4.8.3'
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.8.3
  Error response from daemon: manifest unknown

But that images does not exist

## Expected behavior

There should be an image name with the same release number

## Steps to Reproduce
Run this workflow
https://github.com/NBISweden/theherdbook/actions/runs/1456253607/workflow

## Logs

Pull down action image 'ghcr.io/github/super-linter:v4.8.3'
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.8.3
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 1.902 seconds before retry.
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.8.3
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 4.717 seconds before retry.
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.8.3
  Error response from daemon: manifest unknown
Error: Docker pull failed with exit code 1

**Comment by rasa** [comment]
You can use github/super-linter@v4.8.1 until this issue is addressed.

**Comment by papersaltserver** [comment]
https://github.com/github/super-linter/actions/runs/1454852722
Someone just need to kick this one again

**Comment by adamralph** [comment]
caused by https://github.com/github/super-linter/issues/2125 ?
