### ISSUE TITLE
 Error response from daemon: manifest unknown

### ISSUE THREAD

**Issue by IvanKuchin** [github/super-linter#2130]
## Describe the bug

/usr/bin/docker pull ghcr.io/github/super-linter:v4.8.3 failed with error message
Error response from daemon: manifest unknown

## Expected behavior

successful pull form ghcr.io

## Steps to Reproduce

I'm using super-linter to check my code. But todays check failed due to unable to pull container from ghcr.io. Here is the link to build with log: https://github.com/IvanKuchin/backend_pi/runs/4207134092?check_suite_focus=true

Steps to see the error:
1. Go to 'https://github.com/IvanKuchin/backend_pi/runs/4207134092?check_suite_focus=true'
1. See the error

**Comment by PhilBeaudoin** [comment]
Same error here.

**Comment by mamilov** [comment]
+1 here

**Comment by gowrisankar22** [comment]
+1 here

**Comment by adamralph** [comment]
dup of https://github.com/github/super-linter/issues/2128 ?

**Comment by bogaertg** [comment]
👍

**Comment by sukumarp2020** [comment]
> Same error here.

+1

**Comment by mgeelen-con** [comment]
+1

**Comment by admiralAwkbar** [comment]
Hey All!

Something went really wrong with AUth on packages
Pushing fix now

sorry for any issues!~

**Comment by admiralAwkbar** [comment]
fixed! Sorry again

**Comment by CodTicker** [comment]
Having this issue now
