### ISSUE TITLE
libs missing needed in go linting

### ISSUE THREAD

**Issue by Bysmyyr** [github/super-linter#2153]
## Describe the bug

When running golangci-lint got error: "../../usr/lib/go/src/runtime/cgo/cgo.go:34:8: could not import C (cgo preprocessing failed) (typecheck)" looks like it is this one, so just need to install some libs: https://github.com/golangci/golangci-lint/issues/1176

## Expected behavior
It do not fail

## Steps to Reproduce

No idea how to reproduce this without our codebase, I can look into it if needed.

## Logs
```2021-11-16 06:50:51 [INFO]   Linting [GO] files...
2021-11-16 06:50:51 [INFO]   ----------------------------------------------
2021-11-16 06:50:51 [INFO]   ----------------------------------------------
2021-11-16 06:50:51 [INFO]   ---------------------------
2021-11-16 06:50:51 [INFO]   File:[/github/workspace/cmd/main.go]
2021-11-16 06:51:09 [ERROR]   Found errors in [golangci-lint] linter!
2021-11-16 06:51:09 [ERROR]   Error code: 1. Command output:
------
../../usr/lib/go/src/runtime/cgo/cgo.go:34:8: could not import C (cgo preprocessing failed) (typecheck)
import "C"
       ^
------
2021-11-16 06:51:09 [INFO]   ---------------------------
```

**Comment by admiralAwkbar** [comment]
@Bysmyyr  Looks like they have the issue here https://github.com/golangci/golangci-lint/issues/1176

Going to add to the linter and push a fix :)

**Comment by Bysmyyr** [comment]
sorry to bother but how I use fixed version? 

currently I use gha pr:
```
  - name: Lint code
      uses: github/super-linter/slim@v4
```

and I also tried this:
```
  - name: Lint code
      uses: github/super-linter/slim@8ad8ddc5780d7968bb82a5fade6fbbc37e9be627
```

**Comment by nantiferov** [comment]
@Bysmyyr  I guess this is related to the usage of slim version of super-linter.
Try with usual one `uses: github/super-linter@v4`
