### ISSUE TITLE
Option to Disable textlint Entirely

### ISSUE THREAD

**Issue by pacroy** [github/super-linter#2154]
**Is your feature request related to a problem? Please describe.**
Yes. We cannot disable the new [textlint](https://textlint.github.io/) that is added in [v4.8.2](https://github.com/github/super-linter/releases/tag/v4.8.2). We found the `terminology` rule that is enabled by default in textlint does not make sense for us so we want to disable it entirely.

**Describe the solution you'd like**
Add `VALIDATE_TEXTLINT` environment variable so we can set to `false` to totally disable the textlint.

**Describe alternatives you've considered**
None

**Additional context**
We have tried to configure the `.textlintrc` to disable the terminology rule as follow:

```json
{
  "filters": {
    "comments": true
  },
  "rules": {
    "terminology": false
  }
}
```

But the textlint still throws an error:

```console
== No rules found, textlint hasn’t done anything ==

Possible reasons:
* Your textlint config file has no rules.
* You have no config file and you aren’t passing rules via command line.
* Your textlint config has a syntax error.

=> How to set up rules?
https://github.com/textlint/textlint/blob/master/docs/configuring.md
```

Also tried with:

```json
{
  "filters": {
    "comments": true
  },
  "rules": {
    "terminology": false,
    "no-todo": true
  }
}
```

But also got this error:

```console
✖ Error
Failed to load textlint's rule module: "no-todo" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md


✖ Stack trace
ReferenceError: Failed to load textlint's rule module: "no-todo" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md

    at TextLintModuleResolver.resolveRulePackageName (/node_modules/textlint/lib/src/engine/textlint-module-resolver.js:63:19)
    at TextLintModuleLoader.loadRule (/node_modules/textlint/lib/src/engine/textlint-module-loader.js:157:45)
    at /node_modules/textlint/lib/src/engine/textlint-module-loader.js:51:22
    at Array.forEach (<anonymous>)
    at TextLintModuleLoader.loadFromConfig (/node_modules/textlint/lib/src/engine/textlint-module-loader.js:50:26)
    at new AbstractTextLintEngine (/node_modules/textlint/lib/src/engine/textlint-engine-core.js:94:27)
    at new TextLintEngine (/node_modules/textlint/lib/src/textlint-engine.js:12:9)
    at Object.executeWithOptions (/node_modules/textlint/lib/src/cli.js:213:28)
    at Object.execute (/node_modules/textlint/lib/src/cli.js:114:25)
    at /node_modules/textlint/bin/textlint.js:37:20
```

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by admiralAwkbar** [comment]
@pacroy Hey!

This is one of those weird-named ones...

The flag is `VALIDATE_NATURAL_LANGUAGE`

That will kick it off :)

**Comment by pacroy** [comment]
Thanks. I missed this one. Might be better to refer to `textlint` at this variable description.
