### ISSUE TITLE
Use actionlint docker image instead of installing it manually

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#2175]
**Is your feature request related to a problem? Please describe.**

@admiralAwkbar given it's the second time this pops up (#2063, #2065), maybe we could switch to using [actionlint's Docker image](https://hub.docker.com/r/rhysd/actionlint)? It get's [automatically built and pushed to Docker hub](https://github.com/rhysd/actionlint/blob/main/.github/workflows/release.yaml#L45) as they release a new version.

**Additional context**

And Dependabot will do its job :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco Smart Idea, i think that would be the smoothest idea
