### ISSUE TITLE
Remove Dockerfilelint

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#2179]
While working on #2178, I've noticed that [Dockerfilelint](https://github.com/replicatedhq/dockerfilelint) didn't see any development in more than one year.

Can we remove that from super-linter, given that we already include [hadolint](https://github.com/hadolint/hadolint), which covers all the checks dockerfilelint covers,  plus more?

This would help make super-linter lighter, and simplify maintainability.

If we do this, we should also take care of properly migrating users away from dockerfilelint, if they explicitly enabled that linter, or configured it somehow.

/cc @admiralAwkbar @zkoppert

**Comment by admiralAwkbar** [comment]
@ferrarimarco Yeah, I would say that if there is no development on it, and we already have another available, then this should be a good way to help reduce image size and complexity.

@zkoppert Thoughts on this?

**Comment by zkoppert** [comment]
Agree with @admiralAwkbar. Go for it!
