### ISSUE TITLE
Support sqlfluff configuration

### ISSUE THREAD

**Issue by withinfocus** [github/super-linter#2184]
**Is your feature request related to a problem? Please describe.**

`sqlfluff` support isn't configurable largely due to their lack of support for passing in a config file path. Now that https://github.com/sqlfluff/sqlfluff/pull/1986 is in place the Super-Linter can follow its common practices for allowing a config file to be ... configured.

**Describe the solution you'd like**

Add the normal variables and passthrough to the linter so `sqlfluff` configuration files can be used.

**Describe alternatives you've considered**

Disabling the `sqlfluff` linter due to compatibility problems with the defaults.

**Comment by tunetheweb** [comment]
(one of the SQLFluff maintainers here)

Thanks for raising this for tracking, but this will need to wait until 0.9.0 is released with that additional configuration optional.

BTW I use the GitHub Super Linter quite happily with SQLFluff simply by placing the `.sqlfluff` config file in the top level directory containing my SQL file (right up to root project if necessary).

So currently I have the following:
```
.github
sql
 └ .sqlfluff
 └ example.sql
 └ project
    └ example2.sql
src
 └ other code
```

But agree it would be good to also allow this to be configured similar to other GitHub Super Linter configuration files like so, for those that prefer, once SQLFluff 0.9.0 is released:

```
.github
 └ linters
    └ .sqlfluff
sql
 └ example.sql
 └ project
    └ example2.sql
src
```

But using the first option means SQLFluff is configurable right now, even without that.

**Comment by withinfocus** [comment]
Definitely on board with your second half there -- a lot of organizations (like mine) will want to have configuration for linting in a central location, and this generally better supports how the Super-Linter wants to work.

**Comment by withinfocus** [comment]
Still a need.

**Comment by tunetheweb** [comment]
FYI opened #2361 to allow config file to be placed in usual location (`.github/linters`).
