### ISSUE TITLE
Remove stale.yml and update actions/stale configuration

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#2200]
## Describe the bug

The `marknotstale` job didn't run as expected, and was instead skipped ([example](https://github.com/github/super-linter/actions/runs/1533117181)). This resulted in issues not being marked as not stale, despite applying them the "mark not stale" labels. I had to explicitly remove the stale label myself ([example](https://github.com/github/super-linter/issues/1619)).

## Expected behavior

The `marknotstale` job should correctly remove the "stale" label.

## Logs

https://github.com/github/super-linter/actions/runs/1533117181

## Additional context

https://github.com/github/super-linter/blob/c3ad7bace60b7845bb563a858c0198f7b738724f/.github/workflows/stale.yml#L51

**Comment by tunetheweb** [comment]
I changed that job a few times to correct the functionality.

Why do you think issue #1619 should have been marked as not stale? As far as I can tell it was last commented on, on the 2nd of November, and so was "stale" and so was correctly marked as such. There was no comment on the issue to mark it as not stale. There was a a reference to that issue in #2180 but I don't think a reference counts as a comment (maybe it should? but it doesn't now) so it's still considered "stale".

The [example workflow you linked](https://github.com/github/super-linter/actions/runs/1533117181) was for a different issue.

The workflow does two things:
- The bot will mark things as "stale" on the cron
- It will only mark things as "not stale" on comment.

So only one job should ever run one of those steps (I corrected a bug previously when it was running both steps and so marking an issue as not stale, and then immediately marking it as stale again!). Looking [at the history](https://github.com/github/super-linter/actions/workflows/stale.yml) it seems to be doing what it's supposed to.

Probably should split these jobs out into two workflows to make this all more obvious.

Anyway, so what did you expect to happen here and why? Could be there's a bug here, could be the missing featured (referencing should be enough to mark not stale) or could be you're misunderstanding what should happen here/.

**Comment by ferrarimarco** [comment]
Maybe the bot is not honoring the [extemptLabels](https://github.com/github/super-linter/blob/c3ad7bace60b7845bb563a858c0198f7b738724f/.github/stale.yml#L6) then?

As you can see in #1619, it had the `marknotstale` and `notstale` labels.

Let me update the issue title to better reflect the issue

**Comment by ferrarimarco** [comment]
Is the stale action even looking at that file? Or is it configured via the workflow only? https://github.com/actions/stale

**Comment by ferrarimarco** [comment]
stale.yml looks like a [probot configuration file](https://github.com/probot/stale) which we don't use in this repo.

**Comment by tunetheweb** [comment]
I suspect it if even looks at that file, it's having the exempt lines overridden by the config in the action:

https://github.com/github/super-linter/blob/c3ad7bace60b7845bb563a858c0198f7b738724f/.github/workflows/stale.yml#L41

I think should just configure in the action.

**Comment by ferrarimarco** [comment]
Yeah,  that's what I was about to write. I think we should:

1. get rid of that file
2. update the stale action config to guide users towards using the right label
3. Remove the `marknotstale` and `notstale` labels

**Comment by tunetheweb** [comment]
Do you need 2 if you're doing 3?

You may also need a 4:

4. Update stale action config to remove stale label on assigning of a an exempt label, even if not commenting on the issue.

As reading the config, I think you currently need to add that label (to prevent it being marked as stale in future) AND comment on it (to remove any current stale label). Though I guess when adding the exempt label you could just remove the stale one at the same time., but people might not realise they have to do that.

Then again the stale bot probably won't close issues with both labels so maybe this is not needed? But would be cleaner to have it.

**Comment by ferrarimarco** [comment]
> Do you need 2 if you're doing 3?

I think so, it was totally not obvious to me.

> 
> You may also need a 4:
> 
> 4. Update stale action config to remove stale label on assigning of a an exempt label, even if not commenting on the issue.

Right. I've starting to crank out a PR (#2201). Feel free to add this as well.

> 
> As reading the config, I think you currently need to add that label (to prevent it being marked as stale in future) AND comment on it (to remove any current stale label). Though I guess when adding the exempt label you could just remove the stale one at the same time., but people might not realise they have to do that.
> 

Maybe we should tune the bot message a bit? I tried adding an explaination.

> Then again the stale bot probably won't close issues with both labels so maybe this is not needed? But would be cleaner to have it.

I don't know :)

**Comment by tunetheweb** [comment]
Ah I get 2 now. I thought you meant update the workflow file to change the stale labels. Which you didn't need if doing 3.

So #2201 LGTM!
