### ISSUE TITLE
Triggering workflows on pull requests

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#2205]
Triggering deploy-DEV workflows on PRs coming from forks seems like a thing we should do, otherwise we're going to miss a big chunk of checks.

Thoughts?

References

- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by tunetheweb** [comment]
Forks do not get access to secrets, otherwise anyone could fork and just do the equivalent of `echo $SECRET`. So not sure how you can do this safely.

The other option is to trigger a dev deploy on merge to `main`. Not quite as good as you’d rather know of issues before merging but at least gives you a heads up that a merge has broken something.

**Comment by ferrarimarco** [comment]
Despite the name, deploy-dev workflows don't do any actual deployment. Check here: https://github.com/github/super-linter/blob/main/.github/workflows/deploy-DEV-standard.yml

There's no need to access secrets, AFAIK.

**Comment by tunetheweb** [comment]
I had noticed it was failing on my fork. Example run here: https://github.com/tunetheweb/super-linter/actions/runs/1516790191. Not sure what that failure means.

And btw there is a Codacy secret, but maybe that's not important and could be skipped for forks?:

https://github.com/github/super-linter/blob/c4e6b0c6f46afc27dec640bf07f558cd168b5cb0/.github/workflows/deploy-DEV-standard.yml#L157-L167

**Comment by ferrarimarco** [comment]
Yeah, think so. If we agree to do this, we can avoid running that step on forks.

**Comment by ferrarimarco** [comment]
Here's another example of why we need this:

```
2021-12-07 18:40:55 [DEBUG]   Invoking rustfmt linter. TEST_CASE_RUN: true
2021-12-07 18:40:55 [DEBUG]    - No files found in changeset to lint for language:[RUST_2021]
2021-12-07 18:40:55 [DEBUG]   SKIP_FLAG: 1, list of files to lint: 
2021-12-07 18:40:55 [ERROR]   Failed to find any tests ran for the Linter:[rustfmt]!
2021-12-07 18:40:55 [FATAL]   Please validate logic or that tests exist!
```

This is the result of merging https://github.com/github/super-linter/pull/2196, which didn't run the deploy-DEV workflows

@admiralAwkbar
