### ISSUE TITLE
Use .markdownlintignore file when present in .github/linters

### ISSUE THREAD

**Issue by kpagacz** [github/super-linter#2214]
Seems the `.markdownlintignore` file is ironically ignored wherever it is placed in the project structure. It doesn't ensure that files are ignored when placed either inside .github/linter or in the project root. 

Some steps to reproduce:
1. Create a markdown file with a long line (> 400 characters).
2. Add a .markdownlintignore file to the root of the project or .github/linters
3. Run `superlinter`

Despite those setups I am still getting linting errors:
![image](https://user-images.githubusercontent.com/24480246/144997550-fa268c94-ce41-4522-aca9-55b88c42f0c2.png)

And here's my .markdownlintignore file:
```
# Snapshots from shiny modules.
**/tests/testthat/_snaps/**
```

I would like `superlinter` to take into account my .markdownlintignore configuration. I know that ignoring files and directories is already supported via the environment variable. The thing is that our CI setup reuses github workflows over multiple repositories, so we have a central workflow repo hosting all our workflows thus changing something for a single repo is troublesome if it requires changes in the workflow file.

**Comment by kpagacz** [comment]
Seems I was wrong on this account. The .markdownlintignore in the root directory is taken into account. Sorry for the trouble.

**Comment by bewuethr** [comment]
It seems that when it's located in the root directory, it actually prevents the linter from running at all, as described in #1948 (and I just experienced myself), but exits successfully.
