### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by quackduck** [github/super-linter#222]
I would like lint support for Java

Common Java linters:
1. Checkstyle
2. FindBugs
3. PMD
4. Error Prone

I have not tried these. Actually, I've never used a linter before

**Comment by guikcd** [comment]
I think you can close this issue; there is another one here: https://github.com/github/super-linter/issues/115

**Comment by quackduck** [comment]
You are right. Sorry for making a duplicate issue. Thanks!
