### ISSUE TITLE
Add csv/tsv linting capabilities

### ISSUE THREAD

**Issue by corneliusroemer** [github/super-linter#2239]
**Is your feature request related to a problem? Please describe.**
I would like `csv`/`tsv` linting capabilities like provided through https://github.com/Clever/csvlint

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by admiralAwkbar** [comment]
@corneliusroemer This is very nice. only a few concerns:
- is this still maintained?
- There is no config file available?
  - Any ideas about how much configuration issues this could cause?

Were just trying to make sure any linter added is configurable and maintained
