### ISSUE TITLE
Lint files in specific directories only

### ISSUE THREAD

**Issue by VladimirMikulic** [github/super-linter#225]
**Is your feature request related to a problem? Please describe.**
I would like to be able to lint my `src` directory only, not `test` or any other directory.

**Describe the solution you'd like**
This could be an option in ENV:

```yaml
env:
  LINT_FILES: [folder, folder/subfolder/*.js]
```

As you can see in the example, this could be further improved by accepting wild cards.

**Describe alternatives you've considered**
I haven't found any alternative so far.

Thank you.

**Comment by leviem1** [comment]
Related #374

**Comment by massto** [comment]
👍👍👍👍

**Comment by massto** [comment]
Very  nice github

**Comment by nvuillam** [comment]
PR attempt to solve this issue : #684
