### ISSUE TITLE
/action/lib/linter.sh: line 57: /action/lib/functions/tapLibrary.sh: No such file or directory

### ISSUE THREAD

**Issue by dshevtsov** [github/super-linter#2253]
## Describe the bug

GitHub action with SuperLinter fails on every run in public and private repositories.

## Steps to Reproduce

See an [example of a failed action in a public repository](https://github.com/magento/devdocs/runs/4596982930?check_suite_focus=true).

## Logs

```
/action/lib/linter.sh: line 57: /action/lib/functions/tapLibrary.sh: No such file or directory
```

**Comment by jduan-highnote** [comment]
Looks like the most recent release of v3.17.1 has broken things. Reverting to 3.17.0 fixed the problem for us (for now).

**Comment by pra-olo** [comment]
Appears to be an issue with the docker image -- the [version of linter.sh tagged v3.17.1](https://github.com/github/super-linter/blob/34b2f8032d759425f6b42ea2e52231b33ae05401/lib/linter.sh#L57) is not trying to load tapLibrary.sh.

**Comment by pra-olo** [comment]
@admiralAwkbar could you please trigger a re-release of v3.17.1?

**Comment by admiralAwkbar** [comment]
@pra-olo YEah something went odd.. local tests all passed... Had to cut a quick release due to a terrible online bounty :)

**Comment by admiralAwkbar** [comment]
@dshevtsov @pra-olo @jduan-highnote 
Sorry about the issues on this. Its trying to be able to back port to the 3.x series and its a nightmare... i would highly advise to move to 4.x series if possible. i will try to get the 3.x image up and running again

**Comment by dshevtsov** [comment]
@admiralAwkbar, moving to 4.x has helped. Thank you!

**Comment by admiralAwkbar** [comment]
@dshevtsov great to hear :) it has a lot more features and like i said, 3.x is a little dead and needs to retire... but i'm sure there could be breaking changes for some

**Comment by admiralAwkbar** [comment]
This is an issue in a hotpatch of 3.x for a critical bug fix

This will not be resolved and the solution is to move to the 4.x releases.

thank you and sorry for any issues this may have caused
