### ISSUE TITLE
Black python linting

### ISSUE THREAD

**Issue by Almenon** [github/super-linter#226]
**Is your feature request related to a problem? Please describe.**
My work uses [black](https://black.readthedocs.io/en/stable/) linting but it's not available in the superlinter 

**Describe the solution you'd like**
A option to use black for linting. 

**Describe alternatives you've considered*
A generic way to specify a executable/program to use for linting. There are a tons of linters and I'm assuming it would be easier to allow the user to specify which linter they want rather than to manually add each linter in as a option.

**Additional context**

**Comment by GaboFDC** [comment]
The problem here is that allowing *any* linter, would need also a way to install such a linter. And with the huge amount of linters there is, it will be difficult to know exactly how to install the linter defined by the user.

One option would be to have a set of pre-defined linters for a language and let the user choose from the set, but this will also scale in a pretty costly way.

**Comment by Almenon** [comment]
> And with the huge amount of linters there is, it will be difficult to know exactly how to install the linter defined by the user.

Maybe https://github.com/replit/upm would help?

**Comment by rpdelaney** [comment]
There is a [docker image for black](https://hub.docker.com/r/kiwicom/black)

**Comment by igor555** [comment]
hi

so no plan for black yet?

**Comment by Almenon** [comment]
@nemchik can the delay before a issue is closed for staleness be increased please?

**Comment by assignUser** [comment]
> One option would be to have a set of pre-defined linters for a language and let the user choose from the set, but this will also scale in a pretty costly way.

https://github.com/github/super-linter/issues/175#issuecomment-663669014
@admiralAwkbar seems to be in support for having multiple options per language.
