### ISSUE TITLE
Consider using check-spelling action

### ISSUE THREAD

**Issue by zkoppert** [github/super-linter#228]
We seem to have a tendency to introduce spelling errors. We might consider adding https://github.com/marketplace/actions/check-spelling

**Comment by GaboFDC** [comment]
Should this be a separate workflow? I have doubts if it could be along the `stack-linter.yml` workflow

**Comment by zkoppert** [comment]
Separate workflow is good with me.

**Comment by IAmHughes** [comment]
There's a Draft PR for adding spell-checking to the linter itself #235 

I'm okay adding the spell-check as a separate workflow, but I personally feel that failing CI due to a spelling mistake is a little noisy. Open to thoughts!
