### ISSUE TITLE
Provide simple pull request checks

### ISSUE THREAD

**Issue by BroderPeters** [github/super-linter#230]
**Is your feature request related to a problem? Please describe.**
While reviewing or even writing a pull request it would help to have some simple default checks in place which confirm that the changes are working.

**Describe the solution you'd like**
An example would be to have a simple check which tries to build the dockerfile.

**Describe alternatives you've considered**
Alternative could be to set up a pull request template with check boxes to confirm that the author at least tried to build and run the project locally. As a kind of reminder.

**Additional context**
None.

**Comment by admiralAwkbar** [comment]
I Think this capability has been merged in :)
