### ISSUE TITLE
Can cpplint use CPPLINT.cfg?

### ISSUE THREAD

**Issue by morphogencc** [github/super-linter#2312]
Is it possible to use `CPPLINT.cfg` with cpp-lint?  I've enabled it with `VALIDATE_CPP=true` and added a `CPPLINT.cfg` file to `.github/linters/`, but cpp-lint doesn't seem to use it, and I don't see any way to manually give cpp-lint a config file to use.

**Comment by admiralAwkbar** [comment]
@morphogencc Hey thanks for the info!
I would love to add a default config and allow users to use their own cpp lint config

can you give me a good default file to utilize?

**Comment by admiralAwkbar** [comment]
Going to see about getting the framework setup and ready

**Comment by admiralAwkbar** [comment]
@morphogencc Also trying to find good documentation on how to use `CCPLint.cfg`
If you could tell me how it uses the file, or if it finds it in the path?
Seems no flags in command `cpplint -c ` or anything like that

**Comment by admiralAwkbar** [comment]
from the output i can see:
```
cpplint.py supports per-directory configurations specified in CPPLINT.cfg
    files. CPPLINT.cfg file can contain a number of key=value pairs.
    Currently the following options are supported:

      set noparent
      filter=+filter1,-filter2,...
      exclude_files=regex
      linelength=80
      root=subdir
      headers=x,y,...

    "set noparent" option prevents cpplint from traversing directory tree
    upwards looking for more .cfg files in parent directories. This option
    is usually placed in the top-level project directory.

    The "filter" option is similar in function to --filter flag. It specifies
    message filters in addition to the |_DEFAULT_FILTERS| and those specified
    through --filter command-line flag.

    "exclude_files" allows to specify a regular expression to be matched against
    a file name. If the expression matches, the file is skipped and not run
    through the linter.

    "linelength" allows to specify the allowed line length for the project.

    The "root" option is similar in function to the --root flag (see example
    above). Paths are relative to the directory of the CPPLINT.cfg.

    The "headers" option is similar in function to the --headers flag
    (see example above).

    CPPLINT.cfg has an effect on files in the same directory and all
    sub-directories, unless overridden by a nested configuration file.
```

does this mean that it will use a config found in that directory only? or do most users have 1 config at the top level?

If I can get some info on that, I should be able to help make this work better :)

**Comment by GaelGuegan** [comment]
is this was resolved ? I am interested in it ...

**Comment by projectitis** [comment]
I would also like to know. I have tried adding CPPLINT.cfg to the root of the repo, and also to `.github/linters/` but neither works.

**Comment by pkazi** [comment]
This worked for me after keeping `CPPLINT.cfg` at root of repo.
