### ISSUE TITLE
Suggestion: use Perlcritic for perl

### ISSUE THREAD

**Issue by bbaassssiiee** [github/super-linter#232]
Perlcritic has 5 levels of code quality, with a reference manual behind it: Perl Best Pracices, from O'Reilly publishers.

**Comment by admiralAwkbar** [comment]
@bbaassssiiee I like it, right now, we're just using the old fashioned way, and this seems to be a more complete way to do it...
Would you like to create a PR and give it a shot?

We have a wiki on how to do it as well :)
https://github.com/github/super-linter/wiki/Adding-new-language-support

**Comment by bbaassssiiee** [comment]
I made fork for a PR.

**Comment by zkoppert** [comment]
@bbaassssiiee Are you still interested in doing this?

**Comment by bbaassssiiee** [comment]
Master didn't build. Then I got distracted.

**Comment by marghidanu** [comment]
Done.
