### ISSUE TITLE
Support for Kotlin

### ISSUE THREAD

**Issue by PatilShreyas** [github/super-linter#236]
**Is your feature request related to a problem? Please describe.**
It's not related to any problem. It's related to support for more programming language i.e. [Kotlin](https://kotlinlang.org).

**Describe the solution you'd like**
Kotlin has [ktlint](https://github.com/pinterest/ktlint) support for lint checking. It would be great if it's implemented in this project.

**Describe alternatives you've considered**
As discussed above, [ktlint](https://github.com/pinterest/ktlint) is the current alternative for this.

**Additional context**
NA

**Comment by admiralAwkbar** [comment]
This looks like it's in the works at #224

**Comment by admiralAwkbar** [comment]
Looks like this was merged!
