### ISSUE TITLE
Rubocop version outdated (super-linter: 1.13.0 / current: 1.25.0)

### ISSUE THREAD

**Issue by fschwahn** [github/super-linter#2365]
The rubocop version used by super-linter is pretty outdated (in rubocop terms, in fact it's just 6 months old). As I'm running close to the latest version locally, I'm running into problem where superlinter flags problem which are not flagged locally, as a check has been changed / fixed / ...

There's a dependabot config to update rubocop (and other ruby dependencies), but it does not seem to work, as it hasn't opened any PRs:
https://github.com/github/super-linter/blob/7308cbd1ad0d6c2e0815d860f3a8f2d318b87dad/.github/dependabot.yml#L20-L25

**Comment by admiralAwkbar** [comment]
@fschwahn Looking into this
thanks!

**Comment by fschwahn** [comment]
@admiralAwkbar thanks for updating the dependencies - did you figure out why dependabot is not opening PRs?

**Comment by admiralAwkbar** [comment]
@fschwahn It was opening some Ruby ones.. which is odd.. but there was a major dep issue with the rubocop and wondering if that was just locked up...
HOpefully now well see if it stays up to date
