### ISSUE TITLE
HTMLHint for HTML

### ISSUE THREAD

**Issue by coliff** [github/super-linter#237]
**Is your feature request related to a problem? Please describe.**

HTML is not linted currently

**Describe the solution you'd like**

HTMLHint is a great HTML linter with a[ wide-range of useful rules](https://htmlhint.com/docs/user-guide/list-rules) and can be run from CLI. Would be happy to see it added to super-linter.

**Describe alternatives you've considered**

**Additional context**

**Comment by admiralAwkbar** [comment]
@coliff I like it, can you try to put together a PR with the proposed changes?

we have a wiki on all the changes needed :)

https://github.com/github/super-linter/wiki/Adding-new-language-support

**Comment by MarcusMorba** [comment]
Besides HTML I would love a check for accessibility issues in general. Most are related to markup.

**Comment by terencedignon** [comment]
Hi all, this is also something I would really like and am on a time-sensitive project that requires it. I'm going to put up a PR but feel free to close it in favor of yours if you think that's better.
