### ISSUE TITLE
markdownlint MD047 rule is not processed

### ISSUE THREAD

**Issue by Nadiahansen15** [github/super-linter#2390]
When running super-linter the MD047 rule from Markdownlint is not processed.

In Markdownlint the rule is enabled as default and in the config file made in super-linter for the Markdownlint  is not overriding the MD047 rule,  which means that it should be enabled.

So my IDE with markdownlint extension highlights it as an error, but when using super-linter is says all files linted successfully.

I am able to enable MD047 by inserting "" in the file or set it to true in the config file. But the question is why it is not default true itself?

MD047/single-trailing-newline: Files should end with a single newline character (markdownlint MD047)

**Comment by harryzcy** [comment]
This issue still exists as of v4.9.4
