### ISSUE TITLE
Add support for docker on ARM

### ISSUE THREAD

**Issue by JonZeolla** [github/super-linter#2428]
**Is your feature request related to a problem? Please describe.**
As a user of `super-linter` it is useful to be able to run it natively on an ARM-based system.

**Describe the solution you'd like**
I would like a `super-linter` docker image which is built for arm (`linux/arm64/v8`).

**Describe alternatives you've considered**
Emulating linux images (`linux/amd64`), which happens on Docker Desktop for Mac by default.

**Additional context**
actions/virtual-environments#2187 may be useful for testing the feature.

**Comment by JonZeolla** [comment]
I would still like this :)

**Comment by JonZeolla** [comment]
Can someone please add the backlog label to this to avoid a bunch of noisy comments like this one?

**Comment by JonZeolla** [comment]
👀

**Comment by JonZeolla** [comment]
👀

**Comment by JonZeolla** [comment]
@admiralAwkbar can I get a backlog label on this please?

**Comment by JonZeolla** [comment]
Related: https://github.com/actions/runner/issues/805#issuecomment-1176590147

**Comment by JonZeolla** [comment]
👀

**Comment by c0h1b4** [comment]
👀

**Comment by JonZeolla** [comment]
@admiralAwkbar can I get a backlog label on this

**Comment by BretFisher** [comment]
I'm tracking the dependencies in this Discussion https://github.com/github/super-linter/discussions/1956

**Comment by JonZeolla** [comment]
Related to https://github.com/super-linter/super-linter/pull/4029
