### ISSUE TITLE
ShellCheck for bash

### ISSUE THREAD

**Issue by tom-halpin** [github/super-linter#243]
wondering how to configure the shellcheck linting for bash rather than posix

normally I would run something like the following

shellcheck --shell=bash file.sh

**Comment by admiralAwkbar** [comment]
@tom-halpin  maybe the docs here can help?
https://github.com/koalaman/shellcheck

**Comment by tom-halpin** [comment]
@admiralAwkbar thanks I know how to do it using a custom action built around shellcheck using the --shell=bash option, just wondering if the super-linter configuration allows or supports command line options for the shellcheck linter

**Comment by admiralAwkbar** [comment]
@tom-halpin makes sense! sorry!
I'm working on adding a `mapping.yml` file that will allow for additional customization and helping interesting cases.
Likely this would be addressed doing that...

Sorry for the wait on it

**Comment by nemchik** [comment]
@tom-halpin I think you're looking for https://github.com/koalaman/shellcheck/wiki/Directive#shell

If you have a shebang in the file you should not need to define `--shell=`. If you don't, or if you need to force a different shell you can add `# shellcheck shell=bash`.

Here are a few links that should be helpful to you:
https://github.com/koalaman/shellcheck/wiki/Recursiveness
https://github.com/koalaman/shellcheck/wiki/SC2239
https://github.com/koalaman/shellcheck/wiki/SC2040

Personally I recommend using `#!/usr/bin/env bash`

**Comment by tom-halpin** [comment]
@nemchik thank you using #!/bin/bash as the shebang resolved my issue.
