### ISSUE TITLE
is it possible to use super-linter for ansible playbook with not only core modules?

### ISSUE THREAD

**Issue by AnatoliChe** [github/super-linter#2512]
Hi!
I try to make github actions to lint my ansible project
In ansible yml I heve
`  - name: Pull default Docker image
    docker_image:
      name: "{{ nginx_container_image }}"
      source: pull
`
When I make actions 
`
uses: github/super-linter@v4
`
I have an error:
`
Error: syntax-check couldn't resolve module/action 'docker_image'. This often indicates a misspelling, missing collection, or incorrect module path.
`

Is it possible to use super-linter for ansible playbook with not only core modules?

**Comment by lindluni** [comment]
Can you share your workflow file, the `- name` field you shared above has colons in it, if you need to include colons the entire line needs to be wrapped in quotes as colon is a yaml reserved character.

**Comment by PranavPurwar** [comment]
I am facing this same issue

**Comment by PaulVerhoeven1** [comment]
facing the same issue

**Comment by ferrarimarco** [comment]
Will be fixed in #3350
