### ISSUE TITLE
Enhance super-linter, via GOOGLE_JAVA_FORMAT, to support newer Java syntax

### ISSUE THREAD

**Issue by david-barley** [github/super-linter#2550]
**Is your feature request related to a problem? Please describe.**
I am trying to use the enhanced switch statement introduced in Java 14. If I allow GOOGLE_JAVA_FORMAT linter to run it errors on every line in the enhanced switch statement

**Describe the solution you'd like**
I'd like for super-linter, via GOOGLE_JAVA_FORMAT, to support newer Java syntax

**Describe alternatives you've considered**
At the moment we have disabled GOOGLE_JAVA_FORMAT so it does not error when using newer Java syntax

**Additional context**
Here is a sample function using the enhanced switch statement I'm talking about, followed by the errors the GOOGLE_JAVA_FORMAT throws, as comments

```
String example(final EnumClass toSwitchOn) {
    return switch (toSwitchOn) {                             //error: illegal start of expression
        case INTERESTING -> "This is interesting";           //error: : expected
        case CODE -> "I like code";                          //error: : expected
        default -> "What are you doing?";                    //error: : expected
    };                                                       //error: illegal start of expression
}
```

**Note**
Thank you for the note :)

**Comment by ferrarimarco** [comment]
Hi @david-barley ! This is already tracked in the google-java-format repo: https://github.com/google/google-java-format/issues/533
