### ISSUE TITLE
PowerShell linter: /github/workspace/.automation/test: No such file or directory

### ISSUE THREAD

**Issue by alagoutte** [github/super-linter#260]
**Describe the bug**
I try PowerShell Linter on one of PowerShell module ( https://github.com/FortiPower/PowerFGT) and get an error (See my commit https://github.com/alagoutte/PowerFGT/tree/super-linter )

**To Reproduce**
using PowerShell linter, i get the following error on the log :
/action/lib/linter.sh: line 1825: cd: /github/workspace/.automation/test: No such file or directory...
You can see log https://github.com/alagoutte/PowerFGT/runs/799749056?check_suite_focus=true

**Comment by hoffmang9** [comment]
I'm getting this also. The powershell script in question works with all of the following:
```
Invoke-ScriptAnalyzer -Path '.\build_windows.ps1' -Settings PSGallery -Recurse
Invoke-ScriptAnalyzer -Path '.\build_windows.ps1' -Recurse
Invoke-ScriptAnalyzer -Path '.\build_windows.ps1'
```` from a local Windows 10 VM.

See: https://github.com/Chia-Network/chia-blockchain/runs/801673014?check_suite_focus=true

**Comment by zkoppert** [comment]
Thanks for opening this issue @alagoutte and @hoffmang9 for confirming its not just this one repo. Digging into this, in particular the offending [code at line 1825](https://github.com/github/super-linter/blob/master/lib/linter.sh#L1825) It seems like this code is trying to get to the test case folder which would only make sense to me if it was running a test and not actually linting the codebase. I believe this section of code [L1817-L1831](https://github.com/github/super-linter/blob/df36e051cac25124ac6bedc58eeecf9826354a9e/lib/linter.sh#L1817-L1831) it was supposed to go in the `TestCodebase()` function. @admiralAwkbar Can you confirm I'm seeing this correctly?

**Comment by IAmHughes** [comment]
This is being addressed in #263 🎉

**Comment by alagoutte** [comment]
Thanks for fix, when do you plan a new release with the fix ?

**Comment by zkoppert** [comment]
@alagoutte Working on a release today. Thanks for hanging in there.
