### ISSUE TITLE
Add an R linter

### ISSUE THREAD

**Issue by nathaneastwood** [github/super-linter#262]
**Is your feature request related to a problem? Please describe.**
There is currently no linter included for R.

**Describe the solution you'd like**
Include the R linter, [lintr](https://github.com/jimhester/lintr).

**Describe alternatives you've considered**
This is the only linter available for R (that I am aware of).

**Additional context**
N/A

**Comment by admiralAwkbar** [comment]
This is super cool!
Can you give it a shot on creating a PR for this?

**Comment by zkoppert** [comment]
use this guide to help add a new linter to the project: https://github.com/github/super-linter/wiki/Adding-new-language-support

**Comment by zkoppert** [comment]
@nathaneastwood Still working on this?

**Comment by nathaneastwood** [comment]
Sorry, haven't had the time due to moving countries. Maybe next week but I can't make promises.

**Comment by zkoppert** [comment]
no problem, just wanted to make sure you were still interested. Good luck on your move, hope its going well!

**Comment by assignUser** [comment]
I am currently working on this but as this is my first docker project I will open a draft pr so someone can check if everything is up to par :)
