### ISSUE TITLE
we suddenly started getting error with location parameter in ARM Template.

### ISSUE THREAD

**Issue by pshahid1** [github/super-linter#2638]
WE had no issues until last week and suddenly super linter started throwing below error 
 [-] Location Should Not Be Hardcoded (71 ms)
        azuredeploy.json must use the location parameter, not resourceGr
oup().location or deployment().location (except when used as a default value in
 the main template)

**Comment by ferrarimarco** [comment]
I think this is due to https://github.com/Azure/arm-ttk/issues/454

Likely will be fixed in the next super-linter release where we pull the latest arm-ttk.
