### ISSUE TITLE
Licenses in Container?

### ISSUE THREAD

**Issue by JeroenKnoops** [github/super-linter#2642]
I've ran a scan and I found a lot of different dependencies which are shipped in the container.

# Problem
Are we allowed to use this container?

# Licenses in container

```
   1    "licenseConcluded": "Apache-2.0 AND BSD-2-Clause",
   1    "licenseConcluded": "Apache-2.0 AND MIT AND Unlicense",
   1    "licenseConcluded": "BSD-3-Clause AND GPL-2.0-only",
   1    "licenseConcluded": "BSD-3-Clause AND GPL-2.0-or-later",
   1    "licenseConcluded": "FTL AND GPL-2.0-or-later",
   1    "licenseConcluded": "GPL-1.0-or-later AND Artistic-1.0-Perl",
   1    "licenseConcluded": "GPL-2.0 AND GPL-3.0-or-later AND LGPL-2.0",
   1    "licenseConcluded": "GPL-2.0+ AND LGPL-3.0+",
   1    "licenseConcluded": "GPL-2.0-or-later AND GPL-3.0-or-later AND LGPL-3.0-or-later",
   1    "licenseConcluded": "GPL-2.0-or-later AND GPL-3.0-or-later",
   1    "licenseConcluded": "GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT",
   1    "licenseConcluded": "GPL-2.0-or-later AND LGPL-2.0-or-later",
   1    "licenseConcluded": "GPL-3.0-only",
   1    "licenseConcluded": "LGPL-2.0-or-later AND MPL-1.1",
   1    "licenseConcluded": "LGPL-2.1",
   1    "licenseConcluded": "LGPL-2.1-or-later AND GPL-2.0-or-later",
   1    "licenseConcluded": "LGPL-2.1-or-later AND MPL-1.1",
   1    "licenseConcluded": "MIT AND GPL-3.0-only",
   1    "licenseConcluded": "MIT AND ISC",
   1    "licenseConcluded": "MIT AND X11",
   1    "licenseConcluded": "ODC-By-1.0",
   1    "licenseConcluded": "OLDAP-2.8",
   1    "licenseConcluded": "WTFPL",
   1    "licenseConcluded": "X11",
   1    "licenseConcluded": "blessing",
   1    "licenseConcluded": "libtiff",
   2    "licenseConcluded": "Apache-2.0 AND MIT",
   2    "licenseConcluded": "BSD-2-Clause AND BSD-3-Clause",
   2    "licenseConcluded": "BSD-3-Clause AND IJG AND Zlib",
   2    "licenseConcluded": "CC-BY-3.0",
   2    "licenseConcluded": "GPL-2.0-with-classpath-exception",
   2    "licenseConcluded": "LGPL-3.0-or-later",
   2    "licenseConcluded": "Libpng",
   2    "licenseConcluded": "MPL-2.0 AND MIT",
   2    "licenseConcluded": "MPL-2.0",
   2    "licenseConcluded": "PSF-2.0",
   2    "licenseConcluded": "TCL",
   2    "licenseConcluded": "Zlib",
   2    "licenseConcluded": "bzip2-1.0.6",
   3    "licenseConcluded": "CC0-1.0",
   3    "licenseConcluded": "GPL-1.0-or-later",
   3    "licenseConcluded": "GPL-3.0-or-later AND GPL-2.0-or-later AND GPL-2.0-only",
   3    "licenseConcluded": "LGPL-2.0-or-later",
   3    "licenseConcluded": "MIT AND ICU AND Unicode-TOU",
   3    "licenseConcluded": "Net-SNMP",
   3    "licenseConcluded": "OpenSSL",
   3    "licenseConcluded": "Ruby AND BSD-2-Clause AND MIT",
   4    "licenseConcluded": "LGPL-3.0-or-later AND GPL-2.0-or-later",
   4    "licenseConcluded": "Python-2.0",
   6    "licenseConcluded": "Artistic-2.0",
   6    "licenseConcluded": "GPL-2.0-only",
   7    "licenseConcluded": "Ruby",
   9    "licenseConcluded": "GPL-2.0-or-later",
  13    "licenseConcluded": "GPL-2.0-or-later AND LGPL-2.1-or-later",
  14    "licenseConcluded": "0BSD",
  14    "licenseConcluded": "Unlicense",
  16    "licenseConcluded": "GPL-3.0-or-later",
  19    "licenseConcluded": "LGPL-2.1-or-later",
  42    "licenseConcluded": "BSD-2-Clause",
  53    "licenseConcluded": "BSD-3-Clause",
  57    "licenseConcluded": "Apache-2.0",
  67    "licenseConcluded": "Ruby AND BSD-2-Clause",
 186    "licenseConcluded": "ISC",
 832    "licenseConcluded": "NONE",
1124    "licenseConcluded": "MIT",
20823    "licenseConcluded": "NOASSERTION",
```

## How did I create the list
I've used [syft](https://github.com/anchore/syft) to generate a SBOM in spdx format.

``` bash
syft packages ghcr.io/github/super-linter:v4.8.7 -o spdx-json > super-linter.spdx.json
```

This will create a 20mb json file with the SBOM in SPDX format.

I've filtered the output with `licenseConcluded`.

``` bash
grep licenseConcluded super-linter.spdx.json > super-linter-licenseConcluded.txt
```

That results in 23372 licenses.
```bash
wc -l super-linter-licenseConcluded.txt
   23372 super-linter-licenseConcluded.txt
```

Grouping them will result in the list above:
```bash
sort super-linter-licenseConcluded.txt | uniq -c | sort -n
```

## Automation

I'm preparing a PR to attach the SBOM (and signature and SLSA provenance) to the container so machines can read this and decide on whether to use the image. This was derived from [this blog](https://marcofranssen.nl/secure-your-software-supply-chain-using-sigstore-and-github-actions)

https://github.com/JeroenKnoops/super-linter/commit/f84ea941dfcf22d1e5e874d94b48ec224a8ba3c8

Is this something you're interested in?

**Comment by ferrarimarco** [comment]
Hi @JeroenKnoops . What is the use case you're tackling with this?

**Comment by JeroenKnoops** [comment]
The use case is that you should be aware what you are importing from outside.
Also the legal license obligations since you're publishing / distributing code.

The law in the US is changing. Biden has send out an executive order to include SBOMs in all products from may 2022 onwards. https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/?msclkid=d75d7fb4a5c911ec9ea5464271c93d3f

Also things around the secure software supply chain are becoming more and more important due to log4shell. This is covered in: https://slsa.dev/

**Comment by lindluni** [comment]
This is something your legal teams will have to decide for you, not something we can give you guidance on.

In my completely non-legal professional analysis (so do not take this as anything other than an opinion), a cursory read of the actual minimum elements: https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf

Leads me to believe that only dependencies of your project need to be included in a commercial SBOM. Unless you are redistributing Super-Linter it seems to me this isn't within scope of your SBOM. If all tools involved in your SDLC had to be included in the SBOM, you would need to provide the SBOM elements for your IDE, for your CICD system, for your version control system, etc.

For us, as non-commercial product, we are not required to provide an SBOM ourselves, though thats not to say we wouldn't, it's just not something we have planned at the moment.

**Comment by ferrarimarco** [comment]
SGTM!

**Comment by JeroenKnoops** [comment]
Publishing the container in GitHub Packages is redistributing in my opinion. License obligations do not only apply to commercial licenses, so I think adding the list might be a good thing. I know of the tool https://github.com/github/licensed , but that tool does not create a SBOM from the linux packages.

I will create a PR with the generation of the (SPDX) SBOM and you can see if you want to use it or not.
