### ISSUE TITLE
Textlint doesn't parse .textlintignore

### ISSUE THREAD

**Issue by jonesy1234** [github/super-linter#2688]
## Describe the bug

As per the documentation here https://textlint.github.io/docs/ignore.html, creating a .textlintignore file should enable exclusions to be added similar to a .gitignore file. This currently isn't working within the superlinter.

## Expected behavior

Creating a .textlintignore file in the root of the repository and adding files that should be excluded in it should remove them from being checked by textlint. 

## Steps to Reproduce

- Created the following repo contents

```
README.md
CHANGELOG.md
.textlintignore
```
.textlintignore contents

```
$ cat .textlintignore 
CHANGELOG.md
```

Run linter locally

```
docker run -it -e "RUN_LOCAL=true" -e "DEFAULT_WORKSPACE=/source" --rm -v `pwd`:/source github/super-linter:latest
```

This file should be ignored

```
2022-03-27 23:33:50 [ERROR]   Found errors in [textlint] linter!
2022-03-27 23:33:50 [ERROR]   Error code: 1. Command output:
------

/source/CHANGELOG.md
  1:11  ✓ error  Incorrect usage of the term: “repo”, use “repository” instead  terminology

✖ 1 problem (1 error, 0 warnings)
✓ 1 fixable problem.
Try to run: $ textlint --fix [file]
------
```

**Comment by admiralAwkbar** [comment]
@jonesy1234 This is interesting as when the super linter runs, it starts in the root of the repository.
SO I assume this is an issue with textlint and not the super-linter, but would love to see how we could help.I would try to open an issue on their repo to see if this is a known issue?

**Comment by ScottGuymer** [comment]
This still doesnt seem to work.
