### ISSUE TITLE
super-linter runs very slowly against json and yaml files

### ISSUE THREAD

**Issue by mmrobins** [github/super-linter#2713]
## Describe the bug

Similar to what https://github.com/github/super-linter/issues/2553 reported, individual files take many minutes to lint, taking 4+ total hours to lint https://github.com/github/rest-api-description

```
 ------
2022-03-23 23:37:51 [INFO]   ---------------------------
2022-03-23 23:37:51 [INFO]   File:[/github/workspace/descriptions-next/ghes-3.1/dereferenced/ghes-3.1.deref.json]
2022-03-24 00:11:15 [INFO]    - File:[ghes-3.1.deref.json] was linted with [eslint] successfully
2022-03-24 00:11:15 [INFO]      - Command output:
------

------
2022-03-24 00:11:15 [INFO]   ---------------------------
2022-03-24 00:11:15 [INFO]   File:[/github/workspace/descriptions-next/ghes-3.1/ghes-3.1.json]
2022-03-24 00:12:00 [INFO]    - File:[ghes-3.1.json] was linted with [eslint] successfully
2022-03-24 00:12:00 [INFO]      - Command output:
------

------
2022-03-24 00:12:00 [INFO]   ---------------------------
2022-03-24 00:12:00 [INFO]   File:[/github/workspace/descriptions-next/ghes-3.2/dereferenced/ghes-3.2.deref.json]
2022-03-24 00:47:01 [INFO]    - File:[ghes-3.2.deref.json] was linted with [eslint] successfully
2022-03-24 00:47:01 [INFO]      - Command output:
------
```

Not sure if you can see the run for this project, but the project is public so perhaps you can
https://github.com/github/rest-api-description/runs/5668239655?check_suite_focus=true

## Expected behavior

I would expect this whole repo to run in a few minutes tops

## Steps to Reproduce

I'm having trouble getting this to run locally with the given instructions in this repo.  https://github.com/github/super-linter/issues/2712  But I'll update here if I manage to reproduce locally.  For now, you can see how we've configured out github actions https://github.com/github/rest-api-description/blob/main/.github/workflows/linter.yml

Update

This is reproducible locally in docker running on my macbook

```
% docker run \
  -it --entrypoint /bin/bash \
  -e RUN_LOCAL=true \
  -e VALIDATE_JSON=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -v $HOME/ghwork/rest-api-description/.git:/tmp/lint/.git \
  -v $HOME/ghwork/rest-api-description/descriptions-next/api.github.com/api.github.com.json:/tmp/lint/descriptions-next/api.github.com/api.github.com.json \
  github/super-linter:slim-v4
```

That ^ lets me try out individual commands in the container, you can just remove the `-it --entrypoint /bin/bash \` to let the scripts from super-linter run directly

```
bash-5.1# TIMING=1 time eslint --no-eslintrc -c /action/lib/.automation/.eslintrc.yml --ext .json /tmp/lint/descriptions-next/api.github.com/api.github.com.json
Rule                               | Time (ms) | Relative
:----------------------------------|----------:|--------:
jsonc/no-dupe-keys                 |  1401.195 |    19.7%
jsonc/no-useless-escape            |   920.252 |    13.0%
jsonc/no-unicode-codepoint-escapes |   861.818 |    12.1%
jsonc/comma-dangle                 |   660.380 |     9.3%
jsonc/quotes                       |   643.153 |     9.1%
jsonc/no-parenthesized             |   586.937 |     8.3%
jsonc/quote-props                  |   402.124 |     5.7%
jsonc/no-multi-str                 |   298.139 |     4.2%
jsonc/no-floating-decimal          |   288.022 |     4.1%
jsonc/no-octal                     |   248.088 |     3.5%
real    1m 40.27s
user    1m 47.26s
sys     0m 0.89s
```

There's no reason an individual file should take nearly 2 minutes to lint.  I'm not a docker expert, but there's something really odd going on here.  I'd say it might be something with docker on mac with an m1, but since I see the same slow behavior in our github actions runs, I don't think that's it.

## Logs

Included in the initial description.  Can add more as needed

**Comment by ferrarimarco** [comment]
The size of the file you're linting is 3.8MB. I doubt the issue is on super-linter. I'd check with the eslint developers if there's something you can do to tune it's behavior to speed up the linting.

**Comment by mmrobins** [comment]
granted `eslint` isn't the fastest for large files, but something about the docker setup for this project makes the linting 3x slower

running `eslint` locally against a file takes 30 seconds

```
% time eslint -c .eslintrc.yml descriptions/api.github.com/api.github.com.json
eslint -c .eslintrc.yml descriptions/api.github.com/api.github.com.json  30.79s user 0.52s system 103% cpu 30.191 total
```

running `super-linter` in docker against the same file ends up taking 1 minute 40 seconds

```
% docker run \
  -e RUN_LOCAL=true \
  -v $HOME/ghwork/rest-api-description/.git:/tmp/lint/.git \
  -v $HOME/ghwork/rest-api-description/descriptions/api.github.com/api.github.com.json:/tmp/lint/descriptions/api.github.com/api.github.com.json \
  github/super-linter:slim-v4
...
2022-03-29 23:15:23 [INFO]   File:[/tmp/lint/descriptions/api.github.com/api.github.com.json]
2022-03-29 23:17:03 [INFO]    - File:[api.github.com.json] was linted with [eslint] successfully
2022-03-29 23:17:03 [INFO]      - Command output:
```

I know docker adds overhead, but 3x seems problematic to me

**Comment by ferrarimarco** [comment]
Reopening the issue to check if we got something wrong in our container image.

A couple of questions @mmrobins:

- Are you running the same version of eslint?
- Can you enable debug logging as instructed in the bug report template?

I wonder if there's any operation that we do before actually running eslint that might incur in this performance penalty.

**Comment by ferrarimarco** [comment]
I was able to partially reproduce this. It takes a minimum of 2 mins to lint a single of those files (I ran it against the whole repo), for some even more. I think the increase in time you're seeing is due to the fact that super-linter performs additional checks to detect if a file has to be linted with additional linters, besides checking the extension of the file.

For example, [super-linter checks if `json` files](https://github.com/github/super-linter/blob/14eb37a88c395bb0faf9e3cfe7678acc94caaa3e/lib/functions/buildFileList.sh#L505) are also OpenAPI files, ARM files, etc. If you enable debug logging, you're going to see the relevant log messages.

So, in brief: when super-linter runs against a single file, it still performs additional (needed) checks.

**Comment by rtk-willm** [comment]
I am still seeing this issue while running `super-linter/super-linter/slim@v5.7.2`, any reason why  this issue was marked as closed or is there some otherway to disable all the other checks json linting does?

Here is a chunk of a very very slow (30 + minute) json linting job with debug enabled `ACTIONS_RUNNER_DEBUG: true`
```
....

2023-12-27 21:56:33 [DEBUG]   File:[/path/subpath/xxx.json], File_type:[json], Base_file:[xxx.json]
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is an OpenAPI file...
2023-12-27 21:56:33 [DEBUG]   /path/subpath/xxx.json is NOT an OpenAPI descriptor
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is an ARM file...
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is a Cloud Formation file...
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is a AWS states descriptor...

...
```

**Comment by ferrarimarco** [comment]
Hi @rtk-willm ! Can you please open a fresh issue about this problem, trying against the `latest` image as well?

**Comment by rtk-willm** [comment]
> Hi @rtk-willm ! Can you please open a fresh issue about this problem, trying against the `latest` image as well?

no problem. no issue here https://github.com/super-linter/super-linter/issues/5073 😄
