### ISSUE TITLE
super-linter doesn't read config file from expected location

### ISSUE THREAD

**Issue by jjlangen** [github/super-linter#2716]
## Describe the bug
Specifying config location yields unexpected behaviour

During a local run of mypy with superlinter I import my own config file, using `-e PYTHON_MYPY_CONFIG_FILE=pyproject.toml` but this seems to import pyproject.toml from /action/lib/.automation/ which is not what I expected.

## Expected behavior
Import the specified config file from /tmp/lint

## Steps to Reproduce
```cd ~
mkdir my-python-project
cd my-python-project
touch pyproject.toml
docker run -e RUN_LOCAL=true -e VALIDATE_PYTHON_MYPY=true -e PYTHON_MYPY_CONFIG_FILE=pyproject.toml -v ~/my-python-project:/tmp/lint github/super-linter:slim-latest
```

outputs

2022-03-31 13:34:41 [FATAL]     -> PYTHON_MYPY_LINTER_RULES rules file (/action/lib/.automation/pyproject.toml) doesn't exist. Terminating...

I can fix this by running
`docker run -e RUN_LOCAL=true -e VALIDATE_PYTHON_MYPY=true -e PYTHON_MYPY_CONFIG_FILE=../../../tmp/lint/pyproject.toml -v ~/my-python-project:/tmp/lint github/super-linter:slim-latest` but this is not user friendly.

## Additional context
I run super-linter on a Azure devops build agent which means it has to run in local mode.

This applies to mypy, but also applies to any other config file I've tested, such as flake8 and isort

**Comment by ferrarimarco** [comment]
You can set the rules location with the `LINTER_RULES_PATH` variable, which is relative to `DEFAULT_WORKSPACE`, as detailed in the README. This lets you avoid changing the directory with `../../..`

**Comment by jjlangen** [comment]
Thanks ferrarimarco, now it works:

`docker run -e RUN_LOCAL=true -e DEFAULT_WORKSPACE=/tmp/lint -e LINTER_RULES_PATH=. -e VALIDATE_PYTHON_MYPY=true -e PYTHON_MYPY_CONFIG_FILE=pyproject.toml -v ~/my-python-project:/tmp/lint github/super-linter:slim-latest`
