### ISSUE TITLE
:tada: is wider than the reported box on macOS / Chrome 83

### ISSUE THREAD

**Issue by jsoref** [github/super-linter#278]
**Describe the bug**
There isn't enough space / a way to provide space after :tada:.

**To Reproduce**

macOS 10.14.6 (18G5033)
Google Chrome.app Version 83.0.4103.116 (Official Build) (64-bit)

Load this issue (or any issue where #270 has commented)
> Thanks for opening your first pr in the **super-linter** repo! 🎉 This project is built on contributions just like this.
> Thanks for opening your first pr in the **super-linter** repo! 🎉  This project is built on contributions just like this.
> Thanks for opening your first pr in the **super-linter** repo! 🎉  - This project is built on contributions just like this.
> Thanks for opening your first pr in the **super-linter** repo! 🎉  \ This project is built on contributions just like this.

**Expected behavior**
It should be possible to have a space after :tada: (or a period after :tada:) without it running into :tada:…

In fact, if you look at the markdown, you'd expect to see a space between `:tada:` and `This`.

**Screenshots**
![image](https://user-images.githubusercontent.com/2119212/85795424-3c71d000-b706-11ea-8140-04ab436d12e7.png)
![image](https://user-images.githubusercontent.com/2119212/85795710-bace7200-b706-11ea-9f1b-dcb5d93f515d.png)

**Additional context**

**Comment by jsoref** [comment]
@zkoppert: This is more of a "can you please file a bug to GitHub" -- I suspect you have a better way to give feedback than I do.

**Comment by jsoref** [comment]
Fwiw, here's the bounding box for that message:
![image](https://user-images.githubusercontent.com/2119212/85795857-f49f7880-b706-11ea-95ae-c2089e89d5f2.png)

**Comment by IAmHughes** [comment]
Hey @jsoref, thanks for the bug report. I can't actually reproduce this on Windows or Mac...

Thanks for opening your first pr in the **super-linter** repo! 🎉 This project is built on contributions just like this.

#### Windows


#### Mac

**Comment by jsoref** [comment]
Ok. It's a HiDPI adventure. Those are fun.

I have multiple monitors.

My primary is "Built-in Retina Display" - 15.4-inch (2880x1800)
My secondary displays are both BenQ GW2760HS - 27-inch (1920x1080)
(Changing the primary display doesn't impact this.)

If I drag this window from either BenQ where the problem is present to the Retina, the problem goes away:
![image](https://user-images.githubusercontent.com/2119212/85796949-cc187e00-b708-11ea-814b-35ba1e0970f8.png)

Sigh. Ok, it's a bug in Google Chrome.app (note: the problem isn't present in Firefox/Safari -- I should have checked).

Sorry. I'm not sure I have the energy to file a bug against Chrome.
