### ISSUE TITLE
no way to disable ktlint

### ISSUE THREAD

**Issue by lattice0** [github/super-linter#2787]
**Is your feature request related to a problem? Please describe.**

There's no way to disable ktlint or disable one file from ktlint in the super linter itself. On the templates folder there's no template for ktlint

**Describe the solution you'd like**
A template on ktlint so I can instruct which files to disable. My kotlint file is self-generated so I'd like to not put any comments inside of it.

**Describe alternatives you've considered**
I didn't find any way of excluding a file from super-linter for kotlin

**Comment by admiralAwkbar** [comment]
@lattice0 
It looks like we have `VALIDATE_KOTLIN` which you can set to false to not validate using `ktlint`
Im not familiar with ktlint but it doesn't seem there is a config file to pass to it?

If there is, then we could ave it parse there as well
