### ISSUE TITLE
Invoke-ScriptAnalyzer error

### ISSUE THREAD

**Issue by bgs113** [github/super-linter#279]
**Describe the bug**
When running PowerShell linting using the current latest version tag, which I'm using because a tagged release addressing #260 hasn't been pushed yet, I get the following error:

```
Invoke-ScriptAnalyzer: The term 'Invoke-ScriptAnalyzer' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR! Found errors in [pwsh] linter!
ERROR:[]
```

**To Reproduce**
1. Trigger a run containing a PowerShell file in scope

**Expected behavior**
PowerShell linting completes successfully.

**Screenshots**
N/A

**Additional context**
I'm using the linter.yml file directly from the example in the README, with the only change being the version tag. Other linters complete successfully. I have an exclude rule in .github/linters/.powershell-psscriptanalyzer.psd1.

**Comment by alagoutte** [comment]
i get the same error too
Coming from missing import(-module) (it is no autoload by default with PS Core)

**Comment by Rubemlrm** [comment]
I'm getting this error too. That looks a missing module loading.

**Comment by admiralAwkbar** [comment]
@alagoutte @Rubemlrm can you tell me what module is missing? or not imported?
If you can help me find that, then I can try to put in a fix!

Thanks!

**Comment by Rubemlrm** [comment]
@admiralAwkbar in the end of the day i can try give you more information relative to this bug.

**Comment by Rubemlrm** [comment]
@admiralAwkbar i've been doing some tests and i have the following information:

- Running with github actions i'm getting this error: 

```File:[./windows/magpi-issue-downloader.ps1]
Invoke-ScriptAnalyzer: The term 'Invoke-ScriptAnalyzer' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR! Found errors in [pwsh] linter!
ERROR:[] ```

- If i run locally i don't get any error. 

- Running the container with the debug option and with entry point command as bash, i can call the powershell linter without any problem.

Looks that the linter.sh don't reload the powershell environment to get the new installed module, like @alagoutte  was talking about.

**Comment by alagoutte** [comment]
I found the issue, i will push a fix soon (need to make some test...)

**Comment by admiralAwkbar** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/06/Sean_connery_raction.gif)
