### ISSUE TITLE
Only merge the code when superlinter passes

### ISSUE THREAD

**Issue by siddharthrajaraja** [github/super-linter#2825]
Hi, currently I am working on my side project. I have enabled superlinter Github Actions [here](https://github.com/siddharthrajaraja/ChatApp/blob/master/.github/workflows/super-linter.yml)

I want to merge the code only after the github action returns a success. Can someone please help me achieve this?

Thanks in advance.

**Comment by adrielldagasuan** [comment]
If there are issues found during the linting process, then the workflow should fail and you should not be able to merge your pull request.
