### ISSUE TITLE
Adding Super Linter to itself?

### ISSUE THREAD

**Issue by quackduck** [github/super-linter#284]
Would adding Super Linter as a workflow to the Super Linter repo have any problems?
Are there any reasons this shouldn't be done?

**Comment by IAmHughes** [comment]
Hey @quackduck,

No issue at all, and we actually have it here already: https://github.com/github/super-linter/blob/master/.github/workflows/stack-linter.yml

This repo is linted by the super linter, and also does the CI/CD to update the docker container as we do new releases.

**Comment by quackduck** [comment]
Wow! Thanks for the quick reply!
