### ISSUE TITLE
C# Linter fails on 'global using'-directives

### ISSUE THREAD

**Issue by sentouki** [github/super-linter#2846]
## Describe the bug

Linter fails on `global using`, e.g.
```csharp 
global using System.Text.Json;
global using Microsoft.CSharp;
using System.Threading.Tasks;
using Microsoft.Win32;
```

## Expected behavior

Should pass.

## Steps to Reproduce

This error occurs most likely because super-linter action uses an old version of `dotnet-format` which seems to have problems with global usings.

To reproduce this error:
- Create a new .NET 6 project
- Add .editorconfig with `dotnet_separate_import_directive_groups = false`
- Run `dotnet-format --check` (will fail)
- Run `dotnet format --verify-no-changes` (newer version of dotnet-format that comes with .NET 6 SDK; will pass)

## Logs

```
[INFO]   ---------------------------
[INFO]   File:[/github/workspace/UI.Blazor/Program.cs]
[ERROR]   Found errors in [dotnet-format] linter!
[ERROR]   Error code: 2. Command output:
------
  Formatting code files in workspace '/github/workspace/UI.Blazor'.
  UI.Blazor/Program.cs(1,1): Fix imports ordering.
  Formatted code file '/github/workspace/UI.Blazor/Program.cs'.
```
## Additional context

Running `dotnet-format` will sort using-directives alphabetically mixing `global using` and `using` which makes the code not compilable since `global using`-directives have to come before `using`-directives.

Replacing `dotnet-format --check` with `dotnet format --verify-no-changes` should solve the issue.

**Comment by brazarb** [comment]
would like to use super linter, but this is a problem for us as we need to use the built in version of dotnet format `dotnet format` instead of `dotnet-format`.

the [dotnet-format](https://github.com/dotnet/format) project has been archived as the newer built in command is now recommended.

**Comment by ferrarimarco** [comment]
Hi. Super-linter uses `dotnet format` since a few releases.
