### ISSUE TITLE
Configuration file of Dockerfilelint ignored

### ISSUE THREAD

**Issue by jgaffiot** [github/super-linter#285]
**Describe the bug**
Dockerfilelint seems ignoring the configuration file `.dockerfilelintrc` in  `.github/linter/`.

After some research, it appears that Dockerfilelint does not search for a configuration file at the root of the repository or where Dockerfilelint is run, but expects a configuration file in the same directory than the Dockerfile to lint. If a repository contains several Dockerfile in separates directories, each directory is expected to contain its `.dockerfilelintrc`. So the file  in the `.github/linter/` seems to be logically ignored by Dockerfilelint, even if correctly taken into account by super-linter (with the message "User provided file:[.dockerfilelintrc], setting rules file..." in debug mode).

**To Reproduce**
1. Create a repository with a Dockerfile triggering a warning (`FROM ubuntu:lastest` will trigger "Base images should not use the latest tag").
2. Add a `.dockerfilelintrc` in `.github/linters/` containing:

    ---
    rules:
      latest_tag: off
    ...
3. Run the super-linter

**Expected behavior**
No error should be reported by Dockerfilelint.

**Workaround**
Instead of modifying super-linter (or Dockerfilelint or both), maybe mentioning in the documentation to place the `.dockerfilelintrc` file next to the Dockerfile instead of in `.github/linter/` could be enough.

**Comment by past-due** [comment]
See #283, which should hopefully fix this for you?

**Comment by jgaffiot** [comment]
#283 should definitively fix the issue, but as far as I understand a change in Dockerfilelint is required to make it work, no ? If the publication of an update of Dockerfilelint is not expected soon, should we temporarily change the documentation to signal `.dockerfilelintrc` should be next to the Dockerfile and not in `github/linters` ?
Anyway, thanks for your reactivity !

**Comment by admiralAwkbar** [comment]
@jgaffiot sorry for the bug seems we made a small mistake when this was published...
