### ISSUE TITLE
Allow reading github action as local configuration.

### ISSUE THREAD

**Issue by tmc** [github/super-linter#2851]
Currently it's necessary to duplicate linter rules between action yaml and some local scripts. Having the linter be able to discover configuration settings from a supplied github action would reduce this type of duplication.

**Comment by BryanQuigley** [comment]
It could be configured by say a super-linter.env existing in .github/linters.  

This would let environment variables be set in code for both a local or Github Action run.

**Comment by BryanQuigley** [comment]
Any thoughts on my proposed location above?
