### ISSUE TITLE
ESLint requires duplicate configuration?

### ISSUE THREAD

**Issue by AlbinoGeek** [github/super-linter#2853]
## Describe the bug

`TSX_LINTER_RULES rules file (/action/lib/.automation/.eslintrc.json) doesn't exist. Terminating...`

Why is it looking in `/action/lib/.automation/`?

It didn't copy my repository there, what gives?

**If this is user error, then the env variables like `TYPESCRIPT_ES_CONFIG_FILE` need to be documented better to explain why and how you would point it at your existing rules files, to prevent duplication of linter configuration.**

## Expected behavior

**It should use the .eslintrc.json file at the repository root, not whatever it's looking for.**

## Steps to Reproduce

1) Add super-linter to an otherwise working React or NextJS Repository with TypeScript
2) Configure super-linter to use `slim` image and only `TypeScript` linters (saves multiple minutes)
3) Watch it fail because it expects you to commit duplicate rule files with default configuration

## Logs

```
2022-05-02 01:10:49 [INFO]   Gathering user validation information...
2022-05-02 01:10:49 [INFO]   - Validating ALL files in code base...
2022-05-02 01:10:52 [FATAL]     -> TSX_LINTER_RULES rules file (/action/lib/.automation/.eslintrc.json) doesn't exist. Terminating...
```

## Additional context

You can see this failing in action here: 

- [Action Configuration](https://github.com/Rethunk-Tech/nextjs-boilerplate/blob/github-actions-super-linter/.github/workflows/lint.yml)
- [Failed Pull Request](https://github.com/Rethunk-Tech/nextjs-boilerplate/pull/14)
- [Failed Action](https://github.com/Rethunk-Tech/nextjs-boilerplate/runs/6251032405?check_suite_focus=true)

**Comment by AlbinoGeek** [comment]
Not resolved.

**Comment by cichu** [comment]
I am having a similar issue when trying to set `JAVA_LINTER_RULES` to read rules from file named "checkstyle.xml" in the root of my repository.

```
2022-06-11 06:58:39 [INFO]   Gathering user validation information...
2022-06-11 06:58:39 [INFO]   - Only validating [new], or [edited] files in code base...
2022-06-11 06:58:41 [FATAL]     -> JAVA_LINTER_RULES rules file (/action/lib/.automation/checkstyle.xml) doesn't exist. Terminating...
```

I also tried to remove setting `JAVA_LINTER_RULES` in workflow configuration and renaming my rules file to match Super-Linter default name for that configuration, but it didn't help. My linter configuration is ignored and instead Super-Linter uses its default configuration for java files.

**Comment by cichu** [comment]
Looking around in this repository some more I found this file: https://github.com/github/super-linter/blob/main/docs/using-rules-files.md . In it there is a mention of the `LINTER_RULES_PATH` variable, that lets you change the directory where it's looking for linter configuration files.

In my case adding `LINTER_RULES_PATH: /` solved the issue.

Now I see that this is mentioned in the main README, but it is only a small paragraph in otherwise lengthy wall of text. Maybe it would be better it it was included in one of examples or have an example in its own paragraph?
