### ISSUE TITLE
Rubocop rule Style/FetchEnvVar not found

### ISSUE THREAD

**Issue by yoshih** [github/super-linter#2877]
## Describe the bug

When super linter runs after pushing a branch, the linter fails to complete:
```
2022-05-09 10:54:43 [ERROR]   Found errors in [rubocop] linter!
2022-05-09 10:54:43 [ERROR]   Error code: 2. Command output:
------
Error: unrecognized cop or department Style/FetchEnvVar found in ...
Did you mean `Style/PercentQLiterals`?
```

The rule `Style/FetchEnvVar` has recently been changed (https://github.com/rubocop/rubocop/commit/4087baee6a925cd482af2e03c4813f46cdf73c6a), but not sure if this is related. Is it possible that the rubocop dependency has to be updated in super linter?

**Comment by andreas-venturini** [comment]
fixed by GH-2898
