### ISSUE TITLE
Ignore unrecognized cops with rubocop

### ISSUE THREAD

**Issue by fschwahn** [github/super-linter#2893]
**Is your feature request related to a problem? Please describe.**
superlinter sometimes lags behind the current rubocop version for a few weeks (eg. current latest release is from April 1st - there have been 6 new rubocop versions in that time).

However, developers update rubocop more often locally, and run into cops we might not want to enforce, so we update our central rubocop config to disable / tweak rules. However, now github superlinter fails because we include configuration which it doesn't understand yet due to being on an older version of rubocop.

**Describe the solution you'd like**
I raised this issue with rubocop (https://github.com/rubocop/rubocop/issues/10627), and they added a flag (https://github.com/rubocop/rubocop/pull/10630) named `--ignore-unrecognized-cops`. When superlinter picks up this flag it will be "forward-compatible" with cops added in new rubocop versions.

**Additional context**
Note that this was just merged today, and hasn't been released in an official rubocop version yet. Using that flag with the current rubocop release raises an error.

**Comment by admiralAwkbar** [comment]
@fschwahn this is great. once released, we can add that feature!

**Comment by fschwahn** [comment]
@admiralAwkbar this has been released yesterday: https://github.com/rubocop/rubocop/releases/tag/v1.30.0

Can be added here I guess: https://github.com/github/super-linter/blob/431ee7836e8cdce5a460b0db682d9169563d919b/lib/linter.sh#L955
