### ISSUE TITLE
Update terrascan to 1.15.1

### ISSUE THREAD

**Issue by codezninja** [github/super-linter#2955]
It seems like terrascan has changed its docker image and superlinter is behind on this version.

https://github.com/github/super-linter/blob/a34f330477ba7d5ba3e1f96503cd77c109993918/Dockerfile?rgh-link-date=2022-05-25T02%3A55%3A40Z#L10

**Comment by ferrarimarco** [comment]
Dependabot will take care of this when the 1.15.0 becomes available on Docker Hub.

**Comment by ferrarimarco** [comment]
Reopening because the PR also migrates to the correct Docker Hub org.

**Comment by codezninja** [comment]
@ferrarimarco The `main` branch build seems to have failed cause of a network related issue. Is there a way to retry that again?
