### ISSUE TITLE
Check if text files end with a newline

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#297]
**Is your feature request related to a problem? Please describe.**
Some tools have some issues in rendering text files that don't end with a new line. Additionally, that's what the [POSIX standard mandates](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

**Describe the solution you'd like**
I'd like a way to check if files end with a new line, and notice the user with an error if they don't.

**Describe alternatives you've considered**
Simple, language-agnostic, POSIX-compliant way:

```shell
find "$(pwd)" -type f -not -path "*/\.git/*" -not -path "*/\node_modules/*" >tmp
while IFS= read -r file; do
    case "$(git diff --no-index --numstat /dev/null "$file")" in
    "$(printf '%s\t-\t' -)"*)
        echo "skipping newline check for $file because it's a binary"
        continue
        ;;
    *)
        echo "Checking if $file ends with a newline"
        [ -z "$(tail -c1 "$file")" ] || echo "ERROR: $file doesn't end with a newline" || exit 1
        ;;
    esac
done <tmp
rm tmp
```

**Comment by ahmadnassri** [comment]
you might wanna check out #221

**Comment by zkoppert** [comment]
@ferrarimarco Does #221 solve what you are trying to accomplish?

**Comment by zkoppert** [comment]
Closing due to no response. Please reopen to discuss further.

**Comment by ferrarimarco** [comment]
Hi @zkoppert ! Sure, we can close this :)
