### ISSUE TITLE
Utilize python Black profile in iSort config

### ISSUE THREAD

**Issue by Viridius** [github/super-linter#3039]
**Is your feature request related to a problem? Please describe.**
[iSort now has a `black` profile which can be applied to ensure the two tools play nicely with one another](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html). Currently super-linter has a custom config to try and facilitate this but this could be streamlined as detailed below:

**Describe the solution you'd like**
TEMPLATES/.isort.cfg
```yml
[settings]
profile=

; vertical hanging indent mode also used in black configuration
multi_line_output = 3

; necessary because black expect the trailing comma
include_trailing_comma = true
```

simply becomes:
```yml
[settings]
profile=black
```

**Comment by Charlie-iProov** [comment]
bump
