### ISSUE TITLE
How to change linter config for CSharp?

### ISSUE THREAD

**Issue by ClockWise89** [github/super-linter#3040]
I have read the documentation numerous times and I've looked through previous issues but I can't for the life of me figure out how to change the rules for C#. The `TEMPLATES` folder doesn't contain one, as far as I can tell?

I also wonder if it would be possible to specify a `.editorConfig` as the file with rules when linting, since I already have one in my project.

**Comment by Hamza-octav** [comment]
Any Updates on how to specify `.editorConfig` as the file with rules when linting
