### ISSUE TITLE
Generate a new docker image to incorporate the latest version of checkstyle which fixed a bug

### ISSUE THREAD

**Issue by MadaraUchiha-314** [github/super-linter#3045]
## Describe the bug

Checkstyle (the linter for Java) recently fixed a bug https://github.com/checkstyle/checkstyle/issues/11508

This fix is incorporated in the version https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.3

github-super-linter uses the latest version of the checkstyle: https://github.com/github/super-linter/blob/main/Dockerfile#L248

but the docker image has not been generated which has this latest version which is failing the linter for Java projects.

Using the `github/super-linter@latest` also doesn't solve the problem.

## Expected behavior

Java projects don't see the linter issues.

## Steps to Reproduce
Build failing due to this: https://github.com/doctorify/core/runs/6918583086?check_suite_focus=true#step:4:589

## Logs

Build failing due to this: https://github.com/doctorify/core/runs/6918583086?check_suite_focus=true#step:4:589

## Additional context

Generating a new docker image and creating a release should solve the problem.

**Comment by djthornton1212** [comment]
O: stale 🤖

**Comment by djthornton1212** [comment]
Could really use an update on this issue. It's been a couple of months and still waiting on an update.

**Comment by MadaraUchiha-314** [comment]
Yup. Considering that just a new release of the docker image has to be created, it shouldn't take much to resolve.

**Comment by djthornton1212** [comment]
@admiralAwkbar Feels like it's a bit overdue since there's been no new release since May.
