### ISSUE TITLE
Multi-line Commands

### ISSUE THREAD

**Issue by Mickelback00** [github/super-linter#3100]
When using super-linter, any GitHub Actions that use the multi-line format such as:
```- name: XYZ
    run: |
        echo "line 1"
        echo "line 2"
```

reports the error:
```
2022-06-28 20:13:22 [ERROR]   Found errors in [actionlint] linter!
2022-06-28 20:13:22 [ERROR]   Error code: 1. Command output:
------
.github/workflows/example.yml:43:9: shellcheck reported issue in this script: SC2086:info:1:53: Double quote to prevent globbing and word splitting [shellcheck]
   |
43 |         run: |
   |         ^~~~
------
```

I've attempted to add the standard shell ignore, `# shellcheck disable=SC2086` within the yaml but as expected, doesn't make a difference.  Is there a way to properly disable this relatively common multi-line shellcheck without ignoring the whole file or `.github/workflow/` files all together?

**Comment by IslamSakrak** [comment]
Try this out https://stackoverflow.com/questions/38745696/how-to-use-multiline-command-in-script-with-yaml

**Comment by Mickelback00** [comment]
Thanks for the reply @IslamSakrak, unfortunately, I don't think that addresses the issue I'm having.  In short, I'm not stuck on how to break lines out over multiple, I've attempted to use both the `|` and `>` block scalar styles (additionally, the chomping indicator in YAML is not supported in GitHub Actions last I knew).

The part I'm stuck on is how to get the [super-linter](https://github.com/github/super-linter) to ignore the **shellcheck's** linting error, SC2086.

**Comment by Mickelback00** [comment]
Friendly bump on this - any suggestions on how to handle the above?

**Comment by Mickelback00** [comment]
Hi @SoumayaMauthoorMOJ. Unfortunately, no, I've not yet found any real solutions to this with GitHub Actions and what `super-linter` flags.

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks for clarifying :-)

**Comment by AlexNik4** [comment]
We found the issue was not just that it was mutli-line but the shellcheck did not recognize our inline powershell commands. We were using the slim version of superlinter. What fixed the linter for us was explicitly indicating what shell we are using. In our case we added this in the yml in each step with powershell command:

    shell: powershell

**Comment by ferrarimarco** [comment]
Hi! This is a question/issue about actionlint, rather than super-linter. I suggest you open an issue in their repository. Thanks!

**Comment by rtkkroland** [comment]
Does anyone have a link to a an `actionlint` issue?
