### ISSUE TITLE
editorconfig-checker outputs error for final newline

### ISSUE THREAD

**Issue by harryzcy** [github/super-linter#3103]
## Describe the bug

editorconfig-checker outputs "No final newline expected" for markdown files with a newline ending. But MD047 specifies that newline should be added by default.

## Expected behavior

editorconfig-checker should follow `InsertFinalNewline` rule.

**Comment by harryzcy** [comment]
Bot go away

**Comment by harryzcy** [comment]
Not stale

**Comment by ferrarimarco** [comment]
This looks like an issue with `editorconfig-checker. I suggest you open an issue in their repo. Thanks!
