### ISSUE TITLE
Add kube-linter

### ISSUE THREAD

**Issue by tis-rpage** [github/super-linter#3118]
**Is your feature request related to a problem? Please describe.**
Please add kube-linter for the following reasons:
* kube-linter is actively maintained whereas kubeval was last worked on 15 months ago
* kube-linter provides robust checks enable/disable

**Describe the solution you'd like**
Add kube-linter as another linter option for kubernetes manifests

**Describe alternatives you've considered**
kubeval

**Comment by tiagovrtr** [comment]
This should stay open

**Comment by ferrarimarco** [comment]
Useful pointers:

- Container image: https://docs.kubelinter.io/#/?id=using-docker
- CLI Usage: https://docs.kubelinter.io/#/?id=usage

**Comment by anrayliu** [comment]
Is this still being worked on? I'm willing to take it on as a new contributor if not.

**Comment by ferrarimarco** [comment]
Sure, feel free to go ahead! Thanks 🙂
