### ISSUE TITLE
deploy-RELEASE workflow: error on image name

### ISSUE THREAD

**Issue by zkoppert** [github/super-linter#314]
**Describe the bug**
The deploy-RELEASE workflow does not complete successfully. It sites an error in the image name: `docker image push is only supported with a tag of the format :owner/:repo_name/:image_name.`

**To Reproduce**
https://github.com/github/super-linter/runs/820118509?check_suite_focus=true#step:4:626

**Expected behavior**
The workflow should complete successfully.

**Screenshots**
<img width="930" alt="Screen Shot 2020-06-29 at 2 43 52 PM" src="https://user-images.githubusercontent.com/6935431/86059117-f757e180-ba16-11ea-8862-7521ad210c5e.png">

**Additional context**
Given the screeenshot it seems this hasn't worked the last few times.

**Comment by IAmHughes** [comment]
Just to add some info to this, the Docker Hub deploy worked, it's the GitHub Package Registry step that is failing.

**Comment by admiralAwkbar** [comment]
this is solved in #317

I forgot that for docker the name should be:
`github/super-linter:version`
For GPR it should be:
`docker.pkg.github.com/github/super-linter/super-liner:version`

- Totally missed that second `super-linter`
