### ISSUE TITLE
Ask superlinter to use a specific version of ktlint

### ISSUE THREAD

**Issue by alexandrefavre4** [github/super-linter#3166]
I have two questions about ktlint version management in superlinter:
1. Where can we see which version of ktlint is used by a specific version of superlinter
2. Can we ask superlinter to use a specific version of ktlint?

**Comment by jeremycarroll** [comment]
See #153 this seems to be a no-fix

**Comment by ferrarimarco** [comment]
@jeremycarroll is correct. The linters are installed when we build the super-linter container image, so it's not feasible to customize the installed version at run time. You can see which linter version is installed by running super-linter with debug output enabled (set `ACTIONS_RUNNER_DEBUG` to `true`).
