### ISSUE TITLE
Comment on PR with linting results / stats

### ISSUE THREAD

**Issue by sammcj** [github/super-linter#3179]
**Is your feature request related to a problem? Please describe.**

It's not always easy to scroll through the large console output to find errors.

**Describe the solution you'd like**

It would be great if the Action could comment on PRs with the results of the checks (pass/fail - if fail what failed and a link to the console log line) and perhaps some stats (number of files checked etc...).

**Comment by Zee2** [comment]
This seems linked to my issue (#3137 ), where the linter doesn't seem to submit any status results to the Status API. Does your Action show any kind of errors around uploading the status to the API?
