### ISSUE TITLE
tflint fails on external source modules

### ISSUE THREAD

**Issue by jdyke** [github/super-linter#320]
**Describe the bug**
I am attempting to use `VALIDATE_TERRAFORM` (tflint) on a main.tf that contains a source module of `terraform-google-modules/scheduled-function/google`. The lint fails due to:

```
Error: `pubsub_scheduled_example` module is not found. Did you run `terraform init`?

  on main.tf line 59, in module "pubsub_scheduled_example":
  59: module "pubsub_scheduled_example" {]
```

I'm not aware of a way for super-linter to run terraform init during runtime. 

**To Reproduce**
1. Create a `main.tf` that contains a source module.
2. Execute super-linter with `VALIDATE_TERRAFORM` enabled.

**Expected behavior**
The super-linter should either run `terraform init` before executing `tflint` or support the `tflint` flag `--ignore-module`

**Comment by admiralAwkbar** [comment]
@jdyke great find on this one!
I will get a fix in the morning :)

**Comment by admiralAwkbar** [comment]
@jdyke what would you prefer it to do?

**Comment by jdyke** [comment]
Hi - thank you!

I like the idea of performing a `terraform init` because the alternative is to skip external source modules which could be the bulk of someone's terraform code - rendering the linting useless. The downside of the `init` route is that it could be a heavy call depending on the amount of providers and source modules referenced. 

IMO the `init` option is the better of the two and it's typically a quick call - you may even catch some providers errors as an added bonus during the call.

**Comment by admiralAwkbar** [comment]
@jdyke It looks like we had modules set to true for default. Setting to false in our templates, and looking at allowing the init to run in the future

**Comment by jdyke** [comment]
Sounds good, should I keep my version at `uses: docker://github/super-linter:v3` ? If so, I'll give it a test now.
