### ISSUE TITLE
super-linter image can't be pulled

### ISSUE THREAD

**Issue by kriswuollett** [github/super-linter#3203]
Repeat of #2130 with the latest release which doesn't seem to be tagged as a release on GitHub which is only [`v4.9.5`](https://github.com/github/super-linter/releases/tag/v4.9.5) at the moment.

```
Pull down action image 'ghcr.io/github/super-linter:v4.9.6'
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.9.6
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 1.7[2](...)4 seconds before retry.
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.9.6
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 9.102 seconds before retry.
  /usr/bin/docker pull ghcr.io/github/super-linter:v[4](...)
  Error response from daemon: manifest unknown
```

**Comment by kriswuollett** [comment]
```yaml
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: \.vscode/.*
```

**Comment by benhammondmusic** [comment]
Same issue

<img width="1369" alt="Screen Shot 2022-08-02 at 9 45 49 AM" src="https://user-images.githubusercontent.com/41567007/182423887-2ade758e-2701-4add-ba8b-f38d8f89eb29.png">

Pinning my github action to 4.9.5 worked to fix it:

in linter.yaml
```
      # Lint using Super Linter. See https://github.com/github/super-linter.
      - name: Lint Code Base
        uses: github/super-linter@v4.9.5
```

**Comment by klaernie** [comment]
I'd say this is a race condition - the repo needs to be updated before setting the tag, but without the tag the image can not yet be published to the ghcr.io. Pulling works fine for me now, but it's 30min later now.

**Comment by kriswuollett** [comment]
Yes, it is a race condition that can be fixed by pinning the version. But I assume most developers will not find it reasonable to have builds fail for a half hour each time an upgrade happens if they don't pin a specific version.

Bumping the action.yml should likely be the last step of a release process after the tagging and the upload to the image registry, see #3202. There can even be an actions check to make sure the image can be downloaded anonymously before merging such a PR.

**Comment by admiralAwkbar** [comment]
@kriswuollett @klaernie Yeah there was a huge delay in the upload to ghcr and docker... not sure what caused it but looking to make the window smaller for these releases. Sorry for any issues caused... Its really been a week out here...

**Comment by benhammondmusic** [comment]
Interesting. Thanks for all your hard work!!
