### ISSUE TITLE
Customize git config for repo auth, e.g., private terraform module linting

### ISSUE THREAD

**Issue by kriswuollett** [github/super-linter#3204]
As discussed earlier in #375 there is no way to currently configure git to allow linters such as `tflint` to retrieve private repos. Example:

```
╷
│ Error: Failed to download module
│ 
│ Could not download module "MY_MODULE" (main.tf:42) source code from
│ "git::https://github.com/ME/MY_REPO?ref=MY_REF":
│ error downloading
│ 'https://github.com/ME/MY_REPO?ref=MY_REF:
│ /usr/bin/git exited with 128: Cloning into
│ '.terraform/modules/MY_MODULE'...
│ fatal: could not read Username for 'https://github.com/': No such device or
│ address
│ 
╵

2022-08-04 02:24:03 [ERROR]   Found errors in [tflint] linter!
```

Although it would be nice to have a specific option like a map from owner to personal access token so that a pattern like this is used:

```bash
git config --global \
    url."https://git:${{ inputs.personal_access_token }}@github.com/${{ inputs.owner }}".insteadOf \
    "https://github.com/${{ inputs.owner }}"
```

A more generic escape hatch could simply be providing a variable for a run script that could be invoked before the linters start to run the above myself. I believe I can't do that already because the linters are run in a Docker container, not a composite action.

**Comment by kriswuollett** [comment]
Also tried using `SSH_KEY` but got same error. Not sure if Terraform can map `HTTPS` to `SSH` style auth. I shouldn't have to change the URL style in my Terraform code to accommodate a linter.

According to GitHub's CLI project the `HTTPS` is [supposed to be the default protocol for `git` operations](https://github.com/cli/cli/discussions/5532), so that should be a reasonable justification for its support here in `super-linter`.

**Comment by codezninja** [comment]
#3223 seems to be a similar problem. If we could run some `git config` commands like you suggested we should be able to workaround this issue. I'd +1 for a `pre-lint.sh` at least

**Comment by dancorne** [comment]
Comment to avoid stalebot closing the issue as it'd be a really useful feature.

**Comment by ferrarimarco** [comment]
Hi!

As a workaround, you could (relatively easily) change the entrypoint of the container image to point to your script, and then invoke entrypoint that we set.

You're right in thinking that there's no way, currently, to run a script inside the container before the whole linting process starts.

I don't think we discussed this possibility in the past, but that looks like an interesting use case.

Feel free to contribute a PR for this, I'll happily review it!
