### ISSUE TITLE
caching image between workflow runs

### ISSUE THREAD

**Issue by ahmadnassri** [github/super-linter#3205]
I know this is more of a general question about GH Actions itself, but is there a way to cache docker images between workflow runs so that it doesn't pull the image every time?

![image](https://user-images.githubusercontent.com/183195/182854660-18327c4c-c0fb-45f3-976b-89aecc25738b.png)

It's quite hard to search for such an answer, since all the results are on caching a docker image build within an action job / step ... and the official docs mention nothing more beyond usage on `use:`

**Comment by admiralAwkbar** [comment]
@ahmadnassri YOu can use your own build agent and have that image cached on the build machine
that would do it...
Other than that, you're at the mercy of the size of the image...
you can use the `slim` image if you're not doing windows stuff...

**Comment by ahmadnassri** [comment]
@admiralAwkbar by "build agent" are you referring to [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)?
