### ISSUE TITLE
Github host key verification failed when using SSH_KEY

### ISSUE THREAD

**Issue by cornet** [github/super-linter#3223]
## Describe the bug

When running super-linter via GH actions `terraform get` fails to download modules from private repositories due to Host key verification failure. When running in a local Docker container with the same SSH_KEY it works fine.

## Expected behavior

`terraform get` downloads the modules. Instead our GH Action logs have the following error:

```
│ Error: Failed to download module
│ 
│ Could not download module "database" (main.tf:25) source code from
│ "git::ssh://git@github.com/XXX/XXX.git?ref=v0.24.2":
│ error downloading
│ 'ssh://git@github.com/XXX/XXX.git?ref=v0.24.2':
│ /usr/bin/git exited with 128: Cloning into '.terraform/modules/database'...
│ Host key verification failed.
│ fatal: Could not read from remote repository.
│ 
│ Please make sure you have the correct access rights
│ and the repository exists.
│ 
```

Looking back near the beginning of the logs we can see that the SSH host key was added successfully:

```
2022-08-10 12:07:47 [INFO]   SSH key found, setting up agent...
2022-08-10 12:07:47 [INFO]   Adding github.com SSH keys
2022-08-10 12:07:47 [INFO]   Successfully verified github.com key
```

## Steps to Reproduce

1. Add private a private ssh key to github actions secrets with access to your private repos
1. Configure super-linter, setting `SSH_KEY` to get the key from secrets

```
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_NATURAL_LANGUAGE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.TF_MODULES_SSH_KEY }}
```
3. Lint a terraform code that pulls in a module from a private repository to which the SSH_KEY has access to.

## Additional context

These errors don't actually affect tflint with the default configuration supplied since [module inspection](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/module-inspection.md) is disabled by default.

If you're not running module inspection then you don't need to run `terraform get` to download the external modules.

**Comment by hoitomt-verodin** [comment]
More info:

If you shell into the container, and run the command manually, it will ask for the key to be added to the known hosts file. We are seeing the error when running [TFLint](https://github.com/terraform-linters/tflint)

1. Set an SSH_KEY environment variable 
2. Run the container (full command is below): 
   1. Pass in the SSH_KEY env var `-e SSH_KEY`
   2. Override the entrypoint: `--entrypoint /bin/bash`
4. Once in the container run super-linter `/action/lib/linter.sh`

When running super linter it will stop and await a response on whether to add the key to the hosts file.

```
2022-08-23 13:55:35 [INFO]   File:[/<file_path>.tf]
The authenticity of host 'github.com (<github ip>)' can't be established.
ED25519 key fingerprint is SHA256:<ssh key fingerprint>
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
```

If you run the container with the default entry point (i.e. no manual intervention) it will throw the error mentioned by the OP

```
docker run --name local-super-linter --label mike-h-special --workdir /github/workspace --rm -e TFLINT_LOG -e SSH_AUTH_SOCK -e SSH_AGENT_PID -e DEFAULT_BRANCH -e RUN_LOCAL -e GITHUB_TOKEN -e VALIDATE_ALL_CODEBASE -e IGNORE_GITIGNORED_FILES -e VALIDATE_DOCKERFILE -e VALIDATE_GO -e VALIDATE_JSCPD -e VALIDATE_SHELL_SHFMT -e VALIDATE_EDITORCONFIG -e VALIDATE_KUBERNETES_KUBEVAL -e VALIDATE_PYTHON_BLACK -e VALIDATE_PYTHON_ISORT -e VALIDATE_JAVASCRIPT_STANDARD -e VALIDATE_TYPESCRIPT_STANDARD -e SSH_KEY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e MULTI_STATUS -v "/Users/mikehoitomt/Code/verodin/tf-live":"/github/workspace" ghcr.io/github/super-linter:slim-v4.9.4
```


Command to run the container. A lot of this may not be needed, but this is almost exactly how Github Actions runs it.

```
docker run -it --rm --name local-super-linter --label mike-h-special --workdir /github/workspace --rm -e TFLINT_LOG -e SSH_AUTH_SOCK -e SSH_AGENT_PID -e DEFAULT_BRANCH -e RUN_LOCAL -e GITHUB_TOKEN -e VALIDATE_ALL_CODEBASE -e IGNORE_GITIGNORED_FILES -e VALIDATE_DOCKERFILE -e VALIDATE_GO -e VALIDATE_JSCPD -e VALIDATE_SHELL_SHFMT -e VALIDATE_EDITORCONFIG -e VALIDATE_KUBERNETES_KUBEVAL -e VALIDATE_PYTHON_BLACK -e VALIDATE_PYTHON_ISORT -e VALIDATE_JAVASCRIPT_STANDARD -e VALIDATE_TYPESCRIPT_STANDARD -e SSH_KEY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e MULTI_STATUS -v "<path/to/code/that/will/be/linted>":"/github/workspace" --entrypoint /bin/bash ghcr.io/github/super-linter:slim-v4.9.4
```

**Comment by codezninja** [comment]
Were you able to have a workaround for this?

**Comment by codezninja** [comment]
I was able to workaround this issue following similiar steps here https://github.com/github/super-linter/issues/375#issuecomment-681630963

**Comment by hoitomt-verodin** [comment]
@codezninja I'll give that a shot. Thank you for the comment!

**Comment by codezninja** [comment]
comment to keep it unstale

**Comment by ferrarimarco** [comment]
@hoitomt-verodin can you open a shell in the container and check the contents of `~/.ssh/known_hosts`? Thanks!

**Comment by piwan** [comment]
@ferrarimarco 

> @hoitomt-verodin can you open a shell in the container and check the contents of `~/.ssh/known_hosts`? Thanks!

I run modified GitHub action:
```
- name: Lint Code Base
  uses: docker://ghcr.io/github/super-linter:slim-v4
  with:
    entrypoint: "/bin/bash"
    args: -c "/action/lib/linter.sh; cat ~/.ssh/known_hosts"
```

and got:
```
github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
```

Following that, just to prove it really is problem with host key verification, in the command above you can add
```
Host *
  StrictHostKeyChecking no
```
to `~/.ssh/config` and that really bypasses the issue (but is not proper solution - I'm not even pasting here more details)
