### ISSUE TITLE
Scaning specific directory

### ISSUE THREAD

**Issue by aniket2499** [github/super-linter#3271]
Is there a way to scan a specific directory in the GitHub repository I don't see any environment variable to set the path of the directory we want to scan in the document. It would be great If you can add that functionality. In local scan too.

**Comment by tamirkamara** [comment]
We use something like this when running the docker image locally:
```
FILTER_REGEX_INCLUDE=./my_app/.*'
```

**Comment by ferrarimarco** [comment]
That would work, yes.

When running locally, you can use the `DEFAULT_WORKSPACE` environment variable for this.
