### ISSUE TITLE
Configuring the docker image provenenace

### ISSUE THREAD

**Issue by denisa** [github/super-linter#3302]
**Is your feature request related to a problem? Please describe.**
My company wants to use a centralized cache for all docker images.

**Describe the solution you'd like**
I’d like an optional input to the the action that would default to "ghcr.io" but that let me configure to a different proxy

**Describe alternatives you've considered**
We’re maintaining a private fork of the action  in which we re-write the action.yml.

**Additional context**
n/a

**Comment by ferrarimarco** [comment]
I think I don't fully get your feature request. Can you please share a more detailed example?
