### ISSUE TITLE
General question: multiple linters for a single language?

### ISSUE THREAD

**Issue by nemchik** [github/super-linter#335]
Is there any interest in having multiple linters for a single language?

Example: for bash I use shellcheck, shfmt, and bashate regularly. So much that I made a repo to automate linting for bash https://github.com/nemchik/ShellSuite before I started using GitHub actions (back when Travis CI was the top dog).

Another example: there's another issue in this repo regarding prettier for JavaScript (and possibly other languages) being used with eslint.

So this issue is meant to be a discussion: where do the maintainers stand on the idea of having multiple linters included in this tool? Are others interested in this idea?

**Comment by admiralAwkbar** [comment]
I like the idea of being able to decide and not forcing a specific style on everyone... I believe there is another issue open to change the linter from rubocop to standard I believe... it would be nice to allow users to choose if they wanted... but not sure about multiple for the same...

**Comment by zkoppert** [comment]
I personally try to avoid multiple linters for the same lang. Okay to close this issue @nemchik ?

**Comment by nemchik** [comment]
> I personally try to avoid multiple linters for the same lang. Okay to close this issue @nemchik ?

It seems the topic didn't garner much attention, so I think it's fine to close. If there becomes a need for it in the future it can be addressed in a PR.
