### ISSUE TITLE
4.9.6 is not a release

### ISSUE THREAD

**Issue by codezninja** [github/super-linter#3369]
## Describe the bug

4.9.6 seems to be released as a tag but not as a github release. Is there a bug in the release process automation?

## Expected behavior

When a release is made GitHub releases should contain that release as well as a changelog about the release

**Comment by ferrarimarco** [comment]
This is correct. I think we didn't mark the release as `Released` (we have a draft for it). This caused the release history to be somewhat clobbered. Hang on so I can check more.

/cc @admiralAwkbar who created the tag.

**Comment by ferrarimarco** [comment]
Ok, should be good now. Thanks for reporting!
