### ISSUE TITLE
Optimise the "How To" GIF

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#337]
It looks like a "How to" video was create as part of #333 and added to the main README.md which shows when visit this repo.

For a start it is linked from the home page to the branch that this was created in, which is now deleted, so you've a broken image showing:

![Screenshot of READ.md showing broken image link](https://user-images.githubusercontent.com/10931297/86218695-179fb180-bb79-11ea-87ee-1c5f0813a615.png)

However, I think that's a good thing because, [as noted](https://github.com/github/super-linter/pull/333/files#r448169527) this is a 2300px x 1606px 17Mb GIF. That means everyone who visits this repo, no matter on what device, and even if on a slow mobile network is downloading 17MB of super widescreen video.

I compressed it through https://ezgif.com/resize to make it 1150 x 803, which makes it 5.8 MB which is better but still very large.

However in general [GIF is a terrible format for videos](https://web.dev/replace-gifs-with-videos/) for a number of reasons:
- They are huge (even if dimensions are correct - and I think they are too big here).
- There is no way to pause, rewind, for skip to sections - this is especially important for a How To.

Is there any way to move this to a real video - hosted on YouTube if GitHub markdown doesn't support this? And should we show it by default or make it a link (perhaps with a still?) so people only download it if they click it?

**Comment by IAmHughes** [comment]
@zkoppert I'll let you chime in here. The gif link is broken as stated, and I'd like your input on the file size bit. Maybe a link to the gif so it's not rendered every time? Not sure how we want to do that 👍

**Comment by zkoppert** [comment]
Currently testing out other video formats. I'll check back in a bit.

**Comment by zkoppert** [comment]
`m4v` takes it down to 574KB which i think is reasonable. I'll open up a PR to see if I can get it to play nice with GitHub. Also will be linking to a longer YouTube video with audio and more explanation.
