### ISSUE TITLE
The version updater workflow fails with permission issues

### ISSUE THREAD

**Issue by ajkerr** [github/super-linter#3372]
## Describe the bug

I think the latest release may have broken something? Our CI runs just started failing with the following error:

```
[Lint Code Base](https://github.com/carmigo/eblock-graphql/actions/runs/3151226047/jobs/5125073568#step:1:24)
Unable to resolve action `github/super-linter@v4`, unable to find version `v4`
```

## Expected behavior

The action should work.

## Steps to Reproduce

Run a workflow that uses this action.

## Additional context

I was able to get unblocked by using the full version number:

`github/super-linter@v4.9.6`

**Comment by ajkerr** [comment]
Update: I was able to unblock our CI pipeline by using the full version number:

`github/super-linter@v4.9.6`

I do believe that `@v4` should still be working, however, so something is definitely wrong.

**Comment by nantiferov** [comment]
I guess it was removed somehow during this issue https://github.com/github/super-linter/issues/3369 fixing
Timing is exactly the same

**Comment by ferrarimarco** [comment]
The root cause is likely [this workflow](https://github.com/github/super-linter/actions/workflows/versioning.yml) failing. We're looking into that.

**Comment by ValarDragon** [comment]
Thanks for working on it! Running into the same issue as of ~2 hours ago.

**Comment by ferrarimarco** [comment]
Hi folks! While we investigate the workflow issues, I've manually pushed the `v4` and a `latest` tags to point at what `v4.9.6` is pointing. Can you verify that your jobs are now able to correctly pull the image? Thanks!

**Comment by ValarDragon** [comment]
Yup! Its working now

Thank you!

**Comment by abhinov-netapp** [comment]
@ferrarimarco , I've just updated our GH action with v4.9.6 to unblock incoming PRs, would the v4.9.6 continue to work or mandates v4 ?

**Comment by ferrarimarco** [comment]
The `v4` Is there to stay, and points to the latest v4 release, which is v4.9.6 in this case. When we publish a new release, a workflow (the one that's currently failing) updates the both the `v4` and the `latest` tag to point at that one. If you want fully reproducible builds, I suggest using the full version number.

**Comment by ferrarimarco** [comment]
I'm leaving this open so we can investigate about the failing [workflow](https://github.com/github/super-linter/blob/main/.github/workflows/versioning.yml). [Example of a failing run](https://github.com/github/super-linter/actions/runs/3151238193).

Some investigation:

it appears the GITHUB_TOKEN the action uses has the right permissions:

From the [debug log](https://github.com/github/super-linter/actions/runs/3151238193/jobs/5127079656):

```
GITHUB_TOKEN Permissions
  Contents: write
...
```

which [grants POST permission on `/repos/:owner/:repo/git/refs`](https://super-linter.slack.com/archives/C0183RWBU1W/p1664459752397239) that the [action we use to create and update the refs](https://github.com/Actions-R-Us/actions-tagger) uses, according to [its source](https://github.com/Actions-R-Us/actions-tagger/blob/8082799423f3a68e8e1f4b9f2606ca6c8f558ec4/src/functions.ts#L187) (it calls the `createRef` or the `updateRef` functions, which are described in the Octokit source (https://octokit.github.io/rest.js/v19#git-create-ref and https://octokit.github.io/rest.js/v19#git-update-ref)

**Comment by rhysd** [comment]
I just wonder why `contents` permission is set to `write` in the debug log. `read` seems set to `contents:` in the workflow:

https://github.com/github/super-linter/blob/84c0d52acc00d1b75361613c21eaf9c0b04dc02c/.github/workflows/versioning.yml#L29
