### ISSUE TITLE
api errors

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [github/super-linter#3387]
Hi,

We are getting api errors on the linter and we are not sure how to fix it.

examples: 
- https://github.com/FreeTubeApp/FreeTube/actions/runs/3161465085/jobs/5147079861
- https://github.com/FreeTubeApp/FreeTube/actions/runs/3160351900/jobs/5144708361
- https://github.com/FreeTubeApp/FreeTube/actions/runs/3078105990/jobs/4973439296

location of file https://github.com/FreeTubeApp/FreeTube/blob/development/.github/workflows/super-linter.yml

**Comment by ferrarimarco** [comment]
The API errors you're seeing don't prevent the workflow to succeed. Your workflows are failing because linters detect errors.

Nevertheless, those are interesting cases, and may be interesting for #3137

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> The API errors you're seeing don't prevent the workflow to succeed. Your workflows are failing because linters detect errors.

Yes i noticed that the workflow succeeded but what i meant with my question is how to fix the api errors?

> Nevertheless, those are interesting cases, and may be relevant for #3137

Ah ok so is this a duplicate? Do i need to close this?

**Comment by ferrarimarco** [comment]
I *think* there might not be anything to do on your end to fix API errors. I don't see any particular permission configuration in your workflows. Did you change the default permissions for workflows in those repos?

Also, you could try re-running those failed workflows and enable debug logging, so we should get more output.

Thanks!

**Comment by ferrarimarco** [comment]
PS: no need to close this issue, we can use it to track our findings.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I _think_ there might not be anything to do on your end to fix API errors. I don't see any particular permission configuration in your workflows. Did you change the default permissions for workflows in those repos?

No we didnt change default permissions.

> Also, you could try re-running those failed workflows and enable debug logging, so we should get more output.
Never tried that. Is this the output your looking for https://github.com/FreeTubeApp/FreeTube/actions/runs/3161465085/jobs/5152961863

**Comment by ferrarimarco** [comment]
I think that in your case, it depends on the workflow having read-only permissions on the `Statuses `API.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
So basically nothing to do about it?

**Comment by ferrarimarco** [comment]
You may grant the workflow `Status: write` permission, provided that is compatible with your desired security model.
