### ISSUE TITLE
GH action not working since 4 days ago with v4.9.6

### ISSUE THREAD

**Issue by zdtsw** [github/super-linter#3391]
## Describe the bug
We started to see problem when use super-linter over the weekend.
We have not changed any config in the GH action nor the source code in our repo. Surprisingly, warning from groovy lint failed GH action checks.

e.g 
```
2022-10-03 02:24:59 [INFO]   File:[/github/workspace/pipelines/build/common/build_base_file.groovy]
2022-10-03 02:25:11 [ERROR]   Found errors in [npm-groovy-lint] linter!
2022-10-03 02:25:11 [ERROR]   Error code: 1. Command output:
....
npm-groovy-lint results in 1 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │     60      │
│    2    │  'Info'   │     197     │
└─────────┴───────────┴─────────────┘
Failure: 0 error(s) have been found 
 60 warning(s) have been found

2022-10-03 02:25:14 [ERROR]   ERRORS FOUND in GROOVY:[1]
```

In the past, we did not have showing as Warning. Now, we have lots of Warnings and GH action failed with 0 Error.

Could that be related to https://github.com/github/super-linter/issues/3381 which should release a new version (i.e v4.9.7) ? 

## Logs
```
Pull down action image 'ghcr.io/github/super-linter:v4.9.6'
  /usr/bin/docker pull ghcr.io/github/super-linter:v4.9.6

2022-10-03 09:28:38 [INFO]   --- GitHub Actions Multi Language Linter ----
2022-10-03 09:28:38 [INFO]    - Image Creation Date:[2022-09-30T18:47:17Z]
2022-10-03 09:28:38 [INFO]    - Image Revision:[be49e014f85f8ccb3d230[32](https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/3173039824/jobs/5168201211#step:4:33)3cfae46df1d85c322]
2022-10-03 09:28:38 [INFO]    - Image Version:[be49e014f85f8ccb3d230323cfae46df1d85c322]

```
## Additional context
old logs from 5 days ago
```
2022-09-30 14:54:38 [INFO]   --- GitHub Actions Multi Language Linter ----
2022-09-30 14:54:38 [INFO]    - Image Creation Date:[2022-08-02T15:34:12Z]
2022-09-30 14:54:38 [INFO]    - Image Revision:[01d[32](https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/3159653845/jobs/5143152136#step:4:33)18744765b55c3b5ffbb27e50961e50c33c5]
2022-09-30 14:54:38 [INFO]    - Image Version:[01d3218744765b55c3b5ffbb27e50961e50c[33](https://github.com/adoptium/ci-jenkins-pipelines/actions/runs/3159653845/jobs/5143152136#step:4:34)c5]
```

**Comment by ferrarimarco** [comment]
Hi @zdtsw. One of our release workflows had a couple of issues that we fixed last week. Hopefully we can re-test it when v4.9.7 comes out.

Anyway, [we configured `npm-groovy-lint` to fail on warnings](https://github.com/github/super-linter/blob/808436342ff40e12ce3ba5d9cfbad17a9c0eee99/lib/linter.sh#L899) since 10 months ago or so, so I don't know why it didn't fail before, in your case.

**Comment by zdtsw** [comment]
> Hi @zdtsw. One of our release workflows had a couple of issues that we fixed last week. Hopefully we can re-test it when v4.9.7 comes out.
> 
> Anyway, [we configured `npm-groovy-lint` to fail on warnings](https://github.com/github/super-linter/blob/808436342ff40e12ce3ba5d9cfbad17a9c0eee99/lib/linter.sh#L899) since 10 months ago or so, so I don't know why it didn't fail before, in your case.

Thanks @ferrarimarco for your quick reply!

Interesting to how it was enabled long time ago, I will check if anything has been changed in the past days from our side.

Btw, I assume there is no flag I can use in the GH action config to overwrite `LINTER_COMMANDS_ARRAY['GROOVY']`
so the only way if I want to not failed on warnings, is to add  `.grovylinterc.json` in` .github/linters` ?

**Comment by theotherjason** [comment]
@zdtsw, we just had a similar thing happen to us with this most recent version.  When looking back at previous passing github action logs, I saw
```
[INFO]    - File:[filename.groovy] was linted with [npm-groovy-lint] successfully
```
followed by
```
npm-groovy-lint results in 0 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │      0      │
│    2    │  'Info'   │      0      │
└─────────┴───────────┴─────────────┘
```
With the v4.9.6 version, we're seeing
```
[INFO]   File:[/github/workspace/filename.groovy]
[ERROR]   Found errors in [npm-groovy-lint] linter!
```
followed by 
```
npm-groovy-lint results in 1 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │     15      │
│    2    │  'Info'   │     179     │
└─────────┴───────────┴─────────────┘
Failure: 0 error(s) have been found 
 15 warning(s) have been found
```
So even though it was showing that a file was linted successfully with the first message, I'm not sure it was actually being linted.  If you look back, do you see a similar thing happening with y'all?

**Comment by ferrarimarco** [comment]
Also, it could be that newer checks were implemented in that linter. Can you verify which version of that linter are running? It should tell you at the beginning of the build.

**Comment by theotherjason** [comment]
Turns out it was pulling `ghcr.io/github/super-linter:slim-v4.9.6` in all recent cases, but we weren't having any issues (or it wasn't actually linting) with this image:
```
Digest: sha256:508e6fdb931dc0b722286ca49d9fc806fe4d9f994ac263757a541bf1ca712b56
Status: Downloaded newer image for ghcr.io/github/super-linter:slim-v4.9.6
ghcr.io/github/super-linter:slim-v4.9.6
```

The issue started with this image:
```
Digest: sha256:8a81df9ee59ad4d2e51f540344f316b27ce80a85245410988c1d9c8359e61cda
Status: Downloaded newer image for ghcr.io/github/super-linter:slim-v4.9.6
ghcr.io/github/super-linter:slim-v4.9.6
```

And our timeline fits with what @zdtsw was seeing.  Our last successful run was 4 days ago, 2022-09-29 21:28 UTC and our first failed run was 3 days ago, 2022-09-30 20:37 UTC.

**Comment by nvuillam** [comment]
Hi, since its v10, npm-groovy-lint uses CodeNarc v3.1.0 (before, it was v2.2)

https://github.com/nvuillam/npm-groovy-lint/releases/tag/v10.0.0 

So if you updated it recently within MegaLinter, @ferrarimarco your guess is good, it's probably new errors that were not in previous versions of CodeNarc

**Comment by zdtsw** [comment]
So, if I understand all correctly:
`npm-groovy-lint `had a newer release v10.0.0 on 13th Aug which includes new codenarc rules
`super-linter ` built new images but somehow set to the same tag as `v4.9.6 `on 30th Sep with the change https://github.com/github/super-linter/blob/main/dependencies/package.json#L33 from 15th Aug
that's why we started to see the new warnings (not because of --failon implemented 10 months ago, but the new rules)
