### ISSUE TITLE
#3137 followup: Linting PRs from forks

### ISSUE THREAD

**Issue by Zee2** [github/super-linter#3419]
## Describe the bug

Followup from #3137, the error is an HTTP 403 when it fails to report the result of linting to the Status API.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/5544935/193923104-3de327b5-619e-4056-a08d-1a583d9faa14.png">

## Steps to Reproduce

Here's the specific job: https://github.com/microsoft/MixedRealityToolkit-Unity/actions/runs/3185206059/jobs/5194506060

And the PR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10726

**Comment by ferrarimarco** [comment]
@Zee2 Can you also share the list of permissions that `GITHUB_TOKEN` has? They should be listed at the beginning of the workflow log. I suspect this could be due to the fact that `GITHUB_TOKEN` doesn't have `write` access to the Status API.

**Comment by ferrarimarco** [comment]
Ah yes, I can see that:

```
Statuses: read
```

**Comment by Zee2** [comment]
Ahhhh gotcha. Thanks.

**Comment by Zee2** [comment]
Ahh, well... @ferrarimarco it seems as though there is no way to get this to work on PRs coming in from public forks. 

`pull_request` trigger on PRs from forks always have `statuses: read` permissions, never write, regardless of what you request.

**Comment by Zee2** [comment]
This is confusing... the other issue on this repo implies that PRs from forks can be linted by this action, but afaik there is no way to get a `statuses: write` on a `pull_request` trigger from a fork?

![image](https://user-images.githubusercontent.com/5544935/194138897-2395b295-0244-4de7-94fd-fb7df4665d53.png)

**Comment by Zee2** [comment]
Yeah @ferrarimarco testing further, the template YAML does not function on PRs from forks because I don't believe it's possible to obtain a `statuses:write`.

**Comment by ferrarimarco** [comment]
CCing @admiralAwkbar who implemented the Status API update IIRC. Maybe he has some more clues.

I guess there's little we can do at this point, besides capturing the error code and printing a more meaningful error message perhaps.

**Comment by ferrarimarco** [comment]
PS: that error means that super-linter couldn't write the Status using the Status API, but it's still linting files.

**Comment by Zee2** [comment]
Yeah... the linter always lints, but if it can't actually tell us that the linting found problems, it isn't very useful :(

**Comment by Zee2** [comment]
@ferrarimarco this definitely needs to be made clear on the docs. If super-linter can't publish the linting results on PRs from forks, that excludes its use from a lot of large public repositories whose contribution model is for community members to create forks and PR their changes in from their forks.

**Comment by ferrarimarco** [comment]
This is about updating the Status of the build to publish the results of the individual linters. You can still rely on the build status.

**Comment by ferrarimarco** [comment]
See an example here: https://github.com/github/super-linter/pull/3070

**Comment by eitsupi** [comment]
unstale
