### ISSUE TITLE
Trailing Comma in Headers for JSON formatting

### ISSUE THREAD

**Issue by crypticraven** [github/super-linter#3420]
## Describe the bug

The linter wants to add a comma to the last variable in a JSON header in python code.

## Expected behavior

Without the comma, the header is valid when constructed this way:

```python
headers = {
        "Authorization": basic_auth,
        "content-type": "application/json",
        "accept": "application/json"
}
```

The linter should honor the best practice for JSON where trailing commas are not required on the last variable in a grouping.

## Steps to Reproduce

We are running the linter from GitHub actions. The only step we are running is to have the check executed when the PR is submitted.

## Logs

```
2022-10-04 22:45:01 [ERROR]   Found errors in [black] linter!
2022-10-04 22:45:01 [ERROR]   Error code: 1. Command output:
------
--- /github/workspace/Rapid7/users.py	2022-10-04 22:44:57.958260 +0000
+++ /github/workspace/Rapid7/users.py	2022-10-04 22:45:01.494043 +0000
@@ -44,11 +44,11 @@
 def rapid7_request(method, url, payload):
     """Default Rapid7 API Request"""
     headers = {
         "Authorization": basic_auth,
         "content-type": "application/json",
-        "accept": "application/json"
+        "accept": "application/json",
     }
     response = requests.request(
         method, url, data=payload, headers=headers, verify="valid.pem"
     )
     return response.text
would reformat /github/workspace/Rapid7/users.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```

## Additional context

The original code without the trailing comma is the way JSON should be formatted. While the script will perform with the trailing comma, there is encouragement for bad practice when constructing JSON variables within scripting code.

**Comment by ferrarimarco** [comment]
> The linter should honor the best practice for JSON where trailing commas are not required on the last variable in a grouping.

Can you give us a link to this best practice, so we can evaluate if we should change the default behavior?

We're using the default Black configuration, which says [this about trailing commas](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas):

```
Black will add trailing commas to expressions that are split by comma where each element is on its own line. This includes function signatures.
```

I think you might want to tune your Black configuration not to add trailing commas.

**Comment by crypticraven** [comment]
I still think that's an improper check/action; where in any variable group does the last entry have a trailing comma?

When we create lists it's `list_group = [1, 2, 3]`. When we have dictionary lists it's `dictionary = {"brand": "Ford",  "model": "Mustang",  "year": 1964}`

In neither situation does a comma trail the variables. JSON follows this same principle; but really this is a fundamental thing in Python.

**Comment by ferrarimarco** [comment]
I think this something you should discuss in the [black](https://github.com/psf/black) repository. We're just applying their defaults. You also have the ability to tune this behavior by providing your own `black` configuration file.

**Comment by crypticraven** [comment]
I've been trying to tune the configuration with the .python-black and .isort.cfg configurations with zero luck. Is there better documentation around how to make this work?

**Comment by ferrarimarco** [comment]
I don't know :).

I'd seek help asking in the `black` community.
