### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by ford-at-aws** [github/super-linter#3421]
Close this issue and re-open https://github.com/github/super-linter/issues/127. It seems to have been forgotten and people are getting frusterated.

**Comment by ferrarimarco** [comment]
@ford-at-aws hi! Feel free to contribute a PR. I'll happily review it.

**Comment by ford-at-aws** [comment]
Will do! I'll talk to my team to see if we can bring this into scope. Can you re-open the above issue as mentioned so we can track it appropriately?

**Comment by ferrarimarco** [comment]
I do, yes.

**Comment by ford-at-aws** [comment]
OK.  Will talk to the team today and perhaps get this in the backlog. Reviewing the code I don't think I'm the right one for the job but perhaps a team member can help.
