### ISSUE TITLE
Add superlinter docker image to Github Actions Runners image

### ISSUE THREAD

**Issue by felipem1210** [github/super-linter#3518]
**Is your feature request related to a problem? Please describe.**
I'm using superlinter but I don't like that each time I trigger it on my workflow is spending 1 minute downloading the docker image, even using the slim image. I'm using github runners

![image](https://user-images.githubusercontent.com/50753325/199430501-0fce289b-354e-45f9-a37e-96df61e0c6bb.png)

**Describe the solution you'd like**
I'd like to know if it is possible to add superlinter as a predefined docker image in the [Github Actions runners images](https://github.com/actions/runner-images). So I don't need to wait to download the image each time I use superlinter. 
**Describe alternatives you've considered**
Using self-hosted runners, but I don't want to do it right now.

**Comment by lkraav** [comment]
> Using self-hosted runners, but I don't want to do it right now.

Looks like this idea got shot down, but how would we configure it with self-hosted runners?
