### ISSUE TITLE
C# linter is very slow

### ISSUE THREAD

**Issue by StephenHodgson** [github/super-linter#3537]
## Describe the bug

Linting takes >1 hour for ~1k .cs files

## Expected behavior
running `dotnet format .\project.sln` takes less than 5 seconds

See https://github.com/github/super-linter/issues/736

**Comment by StephenHodgson** [comment]
Bump

**Comment by StephenHodgson** [comment]
Bump

**Comment by ferrarimarco** [comment]
Reopening #736
