### ISSUE TITLE
dockerfilelinter

### ISSUE THREAD

**Issue by lechen26** [github/super-linter#355]
Hi

so i want to lint my Dockerfile.
i've added the following:

```
- name: Super Linter
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_DOCKER: true
          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_YAML: true
```

i've copied the .dockerfilelintrc from the TEMPLATES directory and put it within .github/linters folder on my repo.
and disabled one of the rules (`latest_tag: on` to `latest_tag: off`)

when it got executed i see the line that indicate my overwrite:
`User provided file:[.dockerfilelintrc], setting rules file...`

but i still get the error:

```
ERROR! Found errors in [/dockerfilelint/bin/dockerfilelint] linter!
ERROR:[File:   /github/workspace/Dockerfile ]

Issue  Category      Title                 Description
    1  Clarity       Base Image Latest     Base images should not use the latest tag.
```

what am i missing?

thanks!

**Comment by jeonghanlee** [comment]
With the latest tag, I have the same issue with `invalid_port: off`.  The error message I've got
```
Line 94: EXPOSE $CF_PORT_HTTP/tcp
Issue  Category      Title                 Description
    1  Possible Bug  Invalid Port Exposed  Exposing ports should only be valid port numbers.
```

**Comment by admiralAwkbar** [comment]
Hello, Can you try with the latest?
I think we had a global var issue

Thanks

**Comment by jeonghanlee** [comment]
Tried with the latest, saw the same issue. Please see <https://github.com/jeonghanlee/ChannelFinder-env/runs/831749806?check_suite_focus=true> with  options are off.

**Comment by past-due** [comment]
I can confirm.

I think part of the confusion may be that `dockerfilelint` will silently proceed with the defaults if an invalid path to a `.dockerlintrc` is passed. Reference: https://github.com/replicatedhq/dockerfilelint/blob/master/lib/index.js#L85

So you can't rely on the fact that `dockerfilelint` executes successfully with the path that is currently being provided by **super-linter** to determine whether it's actually _using_ the `.dockerlintrc` file. You need a combination of a Dockerfile that triggers a rule that is default-on, and a `.dockerlintrc` that disables said rule, for testing.

As mentioned in #305, `dockerfilelint`'s `-c` option expects the `<path to folder _containing_ .dockerlintrc>` and *not* the path _including_ `.dockerlintrc`.

**Comment by szolll** [comment]
Same here.

```
Run docker://github/super-linter:latest
  env:
    VALIDATE_ALL_CODEBASE: true

```

```
----------------------------------------------
User provided file:[.dockerfilelintrc], setting rules file...
```

added 
`  invalid_line: off
`

Yet I get

```
File:[/github/workspace/Dockerfile]
ERROR! Found errors in [/dockerfilelint/bin/dockerfilelint] linter!
ERROR:[
File:   /github/workspace/Dockerfile
Issues: 1
```

```
Line 4: HEALTHCHECK --interval=1m --timeout=3s CMD curl -f http://localhost:80/ || exit 1
Issue  Category      Title                 Description
    1  Possible Bug  Invalid Command       Only valid commands are allowed in a Dockerfile.]
```

**Comment by LukeMondy** [comment]
Yes, agreed, same issue for me.

```
User provided file:[.dockerfilelintrc], setting rules file...
...

File:[/data/dockerfiles/apply-binary_decomp.Dockerfile]

ERROR! Found errors in [/dockerfilelint/bin/dockerfilelint] linter!
ERROR:[
File:   /data/dockerfiles/apply-binary_decomp.Dockerfile
Issues: 1

Line 2: FROM $BASE_IMG
Issue  Category      Title                 Description
1  Clarity       Base Image Missing    Base images should specify a tag to use.
```
but in my `.dockerfilelintrc` file, I have:
```yaml
rules:
  missing_tag: off
```

**Comment by admiralAwkbar** [comment]
This should have been resolved in the latest at this point. Can anyone verify it?

**Comment by jeonghanlee** [comment]
With the latest, I see the same issue.

**Comment by nemchik** [comment]
Possibly related https://github.com/github/super-linter/pull/384
