### ISSUE TITLE
ANSIBLE_FILE_NAME unused

### ISSUE THREAD

**Issue by AndreasPelzer** [github/super-linter#3557]
## Describe the bug

When specifying the env var ANSIBLE_FILE_NAME v4.9.7, the following error is displayed:
"ANSIBLE_LINTER_RULES rules file (/action/lib/.automation/.ansible-lint) doesn't exist. Terminating..."

## Expected behavior

ANSIBLE_FILE_NAME is used to run ansiblelint.

## Steps to Reproduce

1. use ANSIBLE_FILE_NAME to point to a non-standard Ansiblelint file, e.g. .ansible-lint
1. run superlinter.

## Cause
most probably in linter.sh#L879 ANSIBLE_LINTER_RULES should be replaced by ANSIBLE_FILE_NAME

## Additional command
while https://ansible-lint.readthedocs.io/configuring/ uses .ansible-lint or .config/ansible-lint.yml as standard, super-linter uses .ansible-lint.yml as a different standard. This should be aligned.

**Comment by AndreasPelzer** [comment]
please do not mark this issue as stale.

**Comment by ferrarimarco** [comment]
The variable to use to configure the name of the ansible-lint config file is `ANSIBLE_CONFIG_FILE`, not `ANSIBLE_FILE_NAME`. See the [Environment variables section in the README](https://github.com/github/super-linter#environment-variables). The default value is set to `.ansible-lint.yml`.

https://github.com/github/super-linter/blob/80c75ea8a27d73260fbea14da35057da68e0db42/lib/linter.sh#L88

**Comment by AndreasPelzer** [comment]
OK. Thanks
