### ISSUE TITLE
Super linter not picking up user specified lint config files

### ISSUE THREAD

**Issue by vishad-slice** [github/super-linter#356]
**Describe the bug**
In the latest version v3.2.0, the user specified lint config file locations are not working. It is always using the default files.
**To Reproduce**
1. Set these envs:
    JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
    LINTER_RULES_PATH: /path/to/config/directory
**Expected behavior**
User specified lint config file should be used

**Screenshots**
<img width="1383" alt="Screenshot 2020-07-02 at 6 11 08 PM" src="https://user-images.githubusercontent.com/60728725/86360213-ab63a180-bc8f-11ea-92c1-e786ffe64d49.png">

**Additional context**
Working as expected in v3.1.1

**Comment by techotron** [comment]
I've noticed the same issue this morning. I've added a comment to this issue which at the time looked similar: https://github.com/github/super-linter/issues/234#issuecomment-652903651

**Comment by techotron** [comment]
I think it's a scoping thing with the `declare` statement. If I change [this line](https://github.com/github/super-linter/blob/9d5d792af8d1c365b2bf34535908c6df92921704/lib/linter.sh#L320) to:

`declare -g "${LANGUAGE_LINTER_RULES}=$GITHUB_WORKSPACE/$LINTER_RULES_PATH/${!LANGUAGE_FILE_NAME}"` 

then the custom linter works for me
