### ISSUE TITLE
Files beginning with . excluded from JSON linting

### ISSUE THREAD

**Issue by muiriswoulfe** [github/super-linter#3574]
## Describe the bug

Files beginning with `.` are excluded from JSON linting. This also applies to JSON files in folders beginning with `.`.

## Expected behavior

Ignore settings passed through the variables should be respected, as well as potentially the ESLint settings. It appears that JSON linting is using settings from the tool used, that cannot be adjusted through Super Linter.

## Steps to Reproduce

1. Create a repo with a JSON file beginning with `.`, e.g. `.test.json`.
2. Scan the repo with Super Linter, including JSON linting.
3. You will see the warning
> /github/workspace/.test.json
> Warning:   0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

## Logs

```
/github/workspace/.test.json
Warning:   0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override
```

**Comment by muiriswoulfe** [comment]
I believe this issue should remain open, as it still exists and the behavior does not match that documented.

**Comment by ferrarimarco** [comment]
I think this is an [upstream design decision](https://github.com/eslint/rfcs/tree/main/designs/2019-update-default-ignore-patterns) that you'd need to address by tuning your configuration. Some references:

- https://github.com/eslint/eslint/issues/10341
- https://github.com/eslint/eslint/issues/12348
- https://github.com/eslint/eslint/issues/10597
- https://github.com/eslint/eslint/issues/12938

We _might_ decide to tune the default configuration to include dotfiles, but I don't know the implications of that.

**Comment by muiriswoulfe** [comment]
Thanks @ferrarimarco for investigating this. I understand that the issue arose with eslint, but my take would be that super-linter should override this behaviour for consistency across the different linting tools.

The other issue I have with the current setup is that there appears to be no way for this behaviour to be overridden by consumers of super-linter, whereas I believe that eslint consumers can override the behaviour. I feel that super-linter has imposed a constraint on its consumers that it would be preferable to avoid.

**Comment by muiriswoulfe** [comment]
FYI, I tried adding that snippet to `.eslintrc.yml` but it doesn't seem to work with super-linter as I'm still seeing the warning about files with those names being skipped. That's one of the reasons I believe it would be beneficial to have it set as a default within super-linter. And it would also allow for consistent behaviour across the different linters, hiding the internal details of the different linters.

**Comment by ferrarimarco** [comment]
@muiriswoulfe Are you sure super-linter is picking up your `.eslintrc.yml`? If so, it should write that in the output.

**Comment by muiriswoulfe** [comment]
@ferrarimarco Yes, it appears to be picking up the config correctly. If you look at [the build](https://github.com/microsoft/PR-Metrics/actions/runs/3855811423/jobs/6571281311), you can see in the output:

```
    TYPESCRIPT_ES_CONFIG_FILE: ../../.eslintrc.yml
```

followed later by

```
2023-01-06 14:07:37 [INFO]   User provided file:[/github/workspace/.github/linters/../../.eslintrc.yml] exists, setting rules file...
2023-01-06 14:07:37 [INFO]   ----------------------------------------------
2023-01-06 14:07:37 [INFO]   User provided file:[/github/workspace/.github/linters/../../.eslintrc.yml] exists, setting rules file...
2023-01-06 14:07:37 [INFO]   ----------------------------------------------
2023-01-06 14:07:37 [INFO]   User provided file:[/github/workspace/.github/linters/../../.eslintrc.yml] exists, setting rules file...
```

But then the following is seen during the scanning phase:

```
2023-01-06 14:10:00 [INFO]   ---------------------------
2023-01-06 14:10:00 [INFO]   File:[/github/workspace/.markdownlint.json]
2023-01-06 14:10:01 [INFO]    - File:[.markdownlint.json] was linted with [eslint] successfully
2023-01-06 14:10:01 [INFO]      - Command output:
------

/github/workspace/.markdownlint.json
Warning:   0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

✖ 1 problem (0 errors, 1 warning)
```

If you look at [`.eslinrc.yml` for that branch](https://github.com/microsoft/PR-Metrics/blob/muiriswoulfe/eslint-configuration/.eslintrc.yml), you'll see that I added the following to the end of the file so that `.markdownlint.json` should have been scanned:

```YAML
ignorePatterns:
  - '!.*'
 ```

If you know of some way to resolve this problem locally, that would be great. It was the belief that I couldn't resolve it locally that especially prompted me to create this issue.
