### ISSUE TITLE
not able to disable JAVASCRIPT_PRETTIER

### ISSUE THREAD

**Issue by Ganesh-Ponipireddy** [github/super-linter#3626]
## Describe the bug
I'm not able to stop the lint error thrown due to JAVASCRIPT_PRETTIER.

## Expected behavior
Should be able to disable JAVASCRIPT_PRETTIER

## Steps to Reproduce
<img width="746" alt="image" src="https://user-images.githubusercontent.com/48117290/207100164-f5cc4945-477f-46cb-ab79-febf93aa7a62.png">

1. Click on '....'
1. Scroll down to '....'
1. See error

**Comment by ferrarimarco** [comment]
This might be a documentation issue. Did you try setting `VALIDATE_JAVASCRIPT_PRETTIER` to `false`?

**Comment by Ganesh-Ponipireddy** [comment]
yes, I have tried it, but it is not working.

**Comment by ferrarimarco** [comment]
How are you running super-linter? Also, can you run it again after enabling debug output? It's hard to troubleshoot this issue without more data.
