### ISSUE TITLE
`eslint --no-eslintrc`

### ISSUE THREAD

**Issue by jason-stoudt** [github/super-linter#3627]
Why does `--no-eslintrc` get passed to all `eslint` commands? 

It's defeating the purpose of passing in something like:
`JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml`

**Comment by jason-stoudt** [comment]
E.g. https://github.com/github/super-linter/blob/c839c0b828957c8a754d9653ec7dc526672248f3/lib/linter.sh#L902

**Comment by jason-stoudt** [comment]
` 71:49  error  Cannot have untranslated text in JSX  formatjs/no-literal-string-in-jsx`

vs.

`  69:10  error  Definition for rule 'formatjs/no-literal-string-in-jsx' was not found  formatjs/no-literal-string-in-jsx`

**Comment by ferrarimarco** [comment]
Likely a duplicate of #3627. We can discuss there.
