### ISSUE TITLE
`--no-eslintrc` hardcoded for all `eslint` commands

### ISSUE THREAD

**Issue by jason-stoudt** [github/super-linter#3628]
## Describe the bug

For any linters that use `eslint` under the hood, `--no-eslintrc` is hard-coded.

## Expected behavior

It should not be hard-coded, in fact, it should not be there at all. It is ignoring any of the `*_CONFIG_FILE`, e.g. `JAVASCRIPT_ES_CONFIG_FILE`

## Steps to Reproduce
```
- name: Lint Code Base
   uses: docker://ghcr.io/github/super-linter:latest
   env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
```
## Logs
```
2022-12-13 17:15:11 [DEBUG]   Running LintCodebase. FILE_TYPE: TSX. Linter name: eslint, linter command: eslint --no-eslintrc -c /github/workspace/.eslintrc.yml, TEST_CASE_RUN: false, FILTER_REGEX_INCLUDE: , FILTER_REGEX_EXCLUDE:  files to lint: <snip>
...
Error:   27:5   error  Definition for rule 'react-hooks/exhaustive-deps' was not found        react-hooks/exhaustive-deps
Error:   69:10  error  Definition for rule 'formatjs/no-literal-string-in-jsx' was not found  formatjs/no-literal-string-in-jsx
```

## Additional context
Running it locally, you have this:
```
npx eslint <the file>  --no-eslintrc -c .eslintrc.yml`
69:10  error  Definition for rule 'formatjs/no-literal-string-in-jsx' was not found  formatjs/no-literal-string-in-jsx
```

but should have this:
```
npx eslint <the file>  -c .eslintrc.yml
71:49  error  Cannot have untranslated text in JSX  formatjs/no-literal-string-in-jsx
```

**Comment by ferrarimarco** [comment]
I _think_ the original idea was to explicitly pass the configuration file with the `-c` flag for more predictable results.

https://github.com/github/super-linter/blob/aad87c569b8a3de467bf6504c06127822e2845aa/lib/linter.sh#L918

**Comment by ferrarimarco** [comment]
> `--no-eslintrc` overrides EVERYTHING else

What do you mean here?

The eslint docs don't say that [--no-eslintrc option](https://eslint.org/docs/latest/user-guide/command-line-interface#--no-eslintrc) disables what you pass with the [-c (--config) option](https://eslint.org/docs/latest/user-guide/command-line-interface#-c---config), but quite the contrary:

> If .eslintrc.* and/or package.json files are also used for configuration (i.e., --no-eslintrc was not specified), the configurations are merged. Options from this configuration file have precedence over the options from .eslintrc.* and package.json files.

So I think the configuration file we pass with `-c` gets picked up.

Unless I misunderstood your previous comment :)

**Comment by jason-stoudt** [comment]
The link does indeed say that everything in `-c` is disabled:

<img width="640" alt="Screen Shot 2023-01-09 at 4 12 50 PM" src="https://user-images.githubusercontent.com/44677126/211409530-aaf5c417-6657-4722-aac1-7a960d2e4aee.png">

**Comment by ferrarimarco** [comment]
I think that is not the case. See https://github.com/eslint/eslint/issues/9535 for example.
