### ISSUE TITLE
env should be `YAMLLINT_CONFIG_FILE` instead of `YAML_CONFIG_FILE`

### ISSUE THREAD

**Issue by Neudrino** [github/super-linter#3644]
## Describe the bug

[Documentation](https://github.com/github/super-linter#environment-variables) tells, that there should be an env called `YAML_CONFIG_FILE`. However, defining this env does not have any effect whatsoever.

According to the [yamllint documentation](https://yamllint.readthedocs.io/en/stable/configuration.html) the env should be called `YAMLLINT_CONFIG_FILE`.

## Expected behavior

Update the documentation to provide the correct env according to the yamllint documentation.

**Comment by ferrarimarco** [comment]
Those variables don't have the same meaning.

`YAML_CONFIG_FILE` is what we use to set the *name* of the yamllint configuration file:

https://github.com/github/super-linter/blob/80c75ea8a27d73260fbea14da35057da68e0db42/lib/linter.sh#L206

**Comment by marcobjorge** [comment]
The but does indeed exist.

The variable in the documentation and expected in the defaults is `YAML_CONFIG_FILE`.
```
L206 YAML_FILE_NAME="${YAML_CONFIG_FILE:-.yaml-lint.yml}"
```

The variable consumed and passed on to yaml lint is `YAML_LINTER_RULES`.
```
L970 if [ "${YAML_ERROR_ON_WARNING}" == 'false' ]; then
L971   LINTER_COMMANDS_ARRAY['YAML']="yamllint -c ${YAML_LINTER_RULES} -f parsable"
L972 else
L973   LINTER_COMMANDS_ARRAY['YAML']="yamllint --strict -c ${YAML_LINTER_RULES} -f parsable"
L974 fi
```
