### ISSUE TITLE
release 3.2.0 seems to ignore user provided lint override files

### ISSUE THREAD

**Issue by hoffmang9** [github/super-linter#368]
**Describe the bug**
We have two issues that we must override in our codebase - one in markdown and one in python. I have merged all the ongoing changes to the template files while preserving our two overrides. Super Linter acknowledges the two user provided files and then seems to not actually use them when running the markdown and python lints.

**To Reproduce**
1. Go to the debug-superlint branch in chia-blockchain - https://github.com/Chia-Network/chia-blockchain/tree/debug-superlint
2. Cause a push or pull (feel free to fork)
3. Hit the super-lint action
4. See Markdown MD024 errors that should be overriden by https://github.com/Chia-Network/chia-blockchain/blob/d1a8a3dc7e3963836d73c3550edcf8a8b313d3cb/.github/linters/.markdown-lint.yml#L26 and python errors that should be overriden by https://github.com/Chia-Network/chia-blockchain/blob/d1a8a3dc7e3963836d73c3550edcf8a8b313d3cb/.github/linters/.python-lint#L246

**Expected behavior**
.markdown-lint.yml and .python-lint should override the lint errors (as they have in earlier releases.

**Screenshots**

**Additional context**
You can follow my debugging attempts in this PR: https://github.com/Chia-Network/chia-blockchain/pull/302
A recent run - https://github.com/Chia-Network/chia-blockchain/runs/833154863?check_suite_focus=true#step:4:56

**Comment by past-due** [comment]
I can also reproduce this issue.

**Comment by jhomarolo** [comment]
I did the test in version 3.0 and it is ok, in 3.1 it is also with error

**Comment by lechen26** [comment]
its not working for me also when using v3 
 ```
- name: Super Linter
    uses: docker://github/super-linter:v3
    env:
        VALIDATE_KOTLIN: true
        VALIDATE_YAML: true
```
i do see it recognize i have yaml linter file:
`User provided file:[.yaml-lint.yml], setting rules file...`
but later when linting the yaml files i still see errors which indicate he ignores my updated rules.

to be honest i'm trying for the last few days to get this working on few repositories, with different versions, no luck.

**Comment by lechen26** [comment]
ok this first issue was fixed by setting the variables globally scoped.
it works with master.

**Comment by leviem1** [comment]
Could be fixed by associative array in Bash 4...? This is an annoying little bug...

**Comment by admiralAwkbar** [comment]
@leviem1 agree this bug sucks... Any help to resolve is much appreciated, busy week and not a ton of time to hunt :)

**Comment by hoffmang9** [comment]
I have narrowed this down to being introduced after 3.1.1. [This](https://github.com/Chia-Network/chia-blockchain/runs/842002998?check_suite_focus=true) is a successful run for 3.1.1 on the same codebase/branch from above.

**Comment by leviem1** [comment]
@admiralAwkbar That might help. If _I_ get the sword do _I_ get to be king? 😆

**Comment by admiralAwkbar** [comment]
![](https://media.giphy.com/media/125WvQGXcUfEBy/giphy.gif)

**Comment by nemchik** [comment]
![!](https://media2.giphy.com/media/yUI3a7RwLhOFy/200.gif)
