### ISSUE TITLE
Cache Docker layer of Super-linter image in Github action

### ISSUE THREAD

**Issue by ABRAJ11** [github/super-linter#3736]
### Discussed in https://github.com/github/super-linter/discussions/3101

<div type='discussions-op-text'>

<sup>Originally posted by **ABRAJ11** June 29, 2022</sup>
Thanks for Awesome  action . Currently the Docker pull takes around  1-2 min in pulling docker image . can we enable caching of super-linter container image to enable fast execution of workflow  </div>

**Comment by ferrarimarco** [comment]
I think that would require pre-pulling a super-linter container image in the runner image. Your best bet might probably be opening an issue in https://github.com/actions/runner
