### ISSUE TITLE
Exclude folder from lint operations

### ISSUE THREAD

**Issue by lechen26** [github/super-linter#374]
Hi

is it possible to somehow exclude entire directory from linting?
during my workflow except checking out the current repository i also checking out another repository which includes personal github actions.
i want to exclude this directory from super linter operation as i dont want it to be analyzed for all repos.

any way to achieve this?
10x!

**Comment by leviem1** [comment]
It doesn't appear to be possible at this moment from what I can tell. I think it'd be very powerful if this tool allowed you to specify your own regex in its rule file, though that's probably more for a feature request.

**Comment by zkoppert** [comment]
You could write a script to remove the files that you don't want linted and run that before the linter runs. That may work.
That would mean adding this to your workflow file before the linter section: 
```yaml
 - name: Remove files before linting
      run: ./scripts/removeFiles.sh
```

**Comment by lechen26** [comment]
@zkoppert yea i can, its just that i need these files later on the workflow.
its just the usually the first steps of a workflow is checkout .
but i end up checking out a smaller repository and ignore the specific things i dont want through the yml ignore file.

its still would have been nice to tell the linter which folder to analyze or which to exclude

**Comment by nvuillam** [comment]
PR attempt to solve this issue : #684
