### ISSUE TITLE
No matching version found for @typescript-eslint/experimental-utils@3.5.0

### ISSUE THREAD

**Issue by tzachshabtay** [github/super-linter#378]
**Describe the bug**

I tried to enable super linter (via github actions) on [my repository](https://github.com/tzachshabtay/krowser).
I'm getting a build failure: 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/experimental-utils@3.5.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@typescript-eslint/eslint-plugin'
npm ERR! notarget 
```

Build log: https://github.com/tzachshabtay/krowser/runs/819913058

**To Reproduce**
Make a PR against my repo (I guess).

**Expected behavior**
I expected some linting action.

**Comment by GaboFDC** [comment]
Can you run against the latest version?

**Comment by tzachshabtay** [comment]
Works with latest, thanks
