### ISSUE TITLE
Image pull fails in rootless mode since version 4.10.0

### ISSUE THREAD

**Issue by tropicalwave** [github/super-linter#3846]
## Describe the bug

Since version 4.10.0, pulling the super-linter image (eg. for local execution) fails if
1. using Docker in rootless mode (ie. with user namespaces) or
2. using Podman as non-root user.

## Expected behavior

Pulling the super-linter image succeeds (this was the case until including version 4.9.7).

## Steps to Reproduce

podman:
```bash
$ podman pull ghcr.io/github/super-linter:v4.10.0
[...]
Error: writing blob: adding layer with blob "sha256:81e952a70a024a71417cd76b5d6e75d49aa70502b5d0b319ca83ee05e400143b": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 369884941:1876110778 for /node_modules/ast-types-flow/lib/types.js): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /node_modules/ast-types-flow/lib/types.js: invalid argument): exit status 1
```

docker in rootless mode:
```bash
$ docker pull ghcr.io/github/super-linter:v4.10.0
[...]
failed to register layer: Error processing tar file(exit status 1): Container ID 369884941 cannot be mapped to a host ID
```

The same happens with the latest image version 4.10.1.

## Logs

n/a (see output above)

## Additional context

Looking at <https://pullanswer.com/questions/ast-types-flow-sets-file-ownership-that-is-not-compatible-with-circle-ci> indicates that the root cause points to <https://github.com/kyldvs/ast-types-flow>. However, based on the fact that this repository's last commit was issued in 2019, it might not explain why it worked until version 4.9.7 (released in October 2022).

**Comment by ferrarimarco** [comment]
See this related issue: https://github.com/github/super-linter/issues/3785
