### ISSUE TITLE
Can shellcheck check bash script with suffix .bash together with .sh ? Or allow an alias? 

### ISSUE THREAD

**Issue by jeonghanlee** [github/super-linter#387]
Super-linter shellcheck ignores `.bash` files, and  can check `.sh` file. I tried to create an alias, but it is ignored by superlint also.  Is there any way to tell the super-linter to check `.bash` file, `an alias file` or both?

**Comment by nemchik** [comment]
![image](https://media1.giphy.com/media/l3nSN1sjbR4WXFDjy/giphy.gif)
https://github.com/github/super-linter/pull/388

**Comment by jeonghanlee** [comment]
It works! Thanks!
