### ISSUE TITLE
Scala Support

### ISSUE THREAD

**Issue by chenrui333** [github/super-linter#392]
Scala linter support.

Choices are
- [scalafix](https://github.com/scalacenter/scalafix)
- [scalafmt](https://github.com/scalameta/scalafmt)
- [scalastyle](https://github.com/scalastyle/scalastyle)
- [wartremover](https://github.com/wartremover/wartremover)

**Comment by zkoppert** [comment]
It would be great to see some discussion on which solution to use, preferably from those with Scala experience. No personal opinion myself besides that we want to make sure that we are linting and not fixing automatically to stay consistent with the rest of this project.

Check out https://github.com/github/super-linter/wiki/Adding-new-language-support for anyone that would like to implement one of these solutions.

**Comment by chenrui333** [comment]
checkin

**Comment by HorizonNet** [comment]
Based on the initial discussion I would prefer Scalastyle. For me it's kind of a pendant to Checkstyle in Java.
