### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by chenrui333** [github/super-linter#393]
bazel linter

- [buildifier](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md)

**Comment by zkoppert** [comment]
I suggest implementing this using the `- warn` flag instead of the `-fix` flag. Ready to work on. Check out https://github.com/github/super-linter/wiki/Adding-new-language-support for anyone who wants to start work on this.

**Comment by chenrui333** [comment]
checkin
