### ISSUE TITLE
Add Helm linter

### ISSUE THREAD

**Issue by sparta15** [github/super-linter#3946]
**Is your feature request related to a problem? Please describe.**
No, this feature request is related to a new addition to the service.

We have been using the super-linter for a while and it's super useful. However, we struggle a lot when we need to lint `Helm` files. I would be more than happy to build this feature if you finally think that it could be a good addition to the project.

**Describe the solution you'd like**
I'd like that the super-linter would be able to lint `Helm` files. To do it, the user set up a new variable `VALIDATE_HELM` to `true` and a `HELM_CONFIG_FILE` (default `.helm-lint.yml`) where they set up the Charts' directory and other Helm configurations. Then, when the user or the GH Action runs the super-linter, it will run the `helm lint` command. Finally, the super-linter prints the output in the standard format.

Also, I think that the main changes would be in the [LINTER_COMMANDS_ARRAY](https://github.com/github/super-linter/blob/main/lib/linter.sh#L890) and in the [Dockerfile](https://github.com/github/super-linter/blob/main/Dockerfile)

**Describe alternatives you've considered**
Currently, we have another step in our GH Actions that runs the `helm lint` command out of the box.

**Comment by neilime** [comment]
Why this issue has not been taken into account? Helm lint will be really useful. Moreover superlinter is throwing issues on validating Kubernetes helm charts because of kubeconform that does not handle helm out of the box.

By the way kubeconform recommends a way to validate helm charts: https://github.com/yannh/kubeconform?tab=readme-ov-file#helm-charts

**Comment by ferrarimarco** [comment]
@neilime thanks for following up! Feel free to send a PR to address these two requests, I'll happily reopen this issue and review them.
