### ISSUE TITLE
Editorconfig should not check `.git/` folder

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#395]
**Describe the bug**
Currently, it will check any single file in the repo.

Also for reference #391 

**To Reproduce**
Just lint any repo with editor config enabled.

**Expected behavior**
We should exclude this folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/1425500/86794347-056abb00-c032-11ea-9206-925bbbd068ce.png)

**Additional context**
There may be also others folders worth excluding.

**Comment by admiralAwkbar** [comment]
@GaboFDC would this be as simple as adding the check in the `worker.sh`?


```bash
#####################################################
      # Make sure we dont lint node modules or test cases #
      #####################################################
      if [[ $FILE == *"node_modules"* ]]; then
        # This is a node modules file
        continue
      elif [[ $FILE == *"$TEST_CASE_FOLDER"* ]]; then
        # This is the test cases, we should always skip
        continue
      fi
      elif [[ $FILE == *".git"* ]]; then
        # No to .git
        continue
      fi
```

We are already excluding the tests folder and node modules... just want to make sure I'm not off base

**Comment by nemchik** [comment]
```bash
      if [[ $FILE == *"node_modules"* ]] || [[ $FILE == *"$TEST_CASE_FOLDER"* ]] || [[ $FILE == *".git"* ]]; then
        # Skip these
        continue
      fi
```
Little more compact if you're interested.
