### ISSUE TITLE
ESLint config extending and plugins

### ISSUE THREAD

**Issue by sergey-muntyanu** [github/super-linter#399]
I use my own ESLint configuration file and have some configs and plugins (arbnb, prettier, etc.) which are installed via npm.
It was copied to `.github/linters/`.
I have an error:
![Screenshot from 2020-07-09 11-40-12](https://user-images.githubusercontent.com/63044975/87017832-28839f00-c1d9-11ea-8004-f98d781cc47c.png)
Is it possible to use extending configs and plugins configuration? If "yes", could you give more information or some tutorianl (documentation)?

**Comment by jhomarolo** [comment]
Hi @sergey-muntyanu , yes it is possible.

You need to add the plugins in the devdependencies and run npm i before running.

I have an example repository using prettier: https://github.com/herbsjs/suma

**Comment by davidjbradshaw** [comment]
@jhomarolo you config only works because you only include plugins that come with super-linter. It is not a solution to the question of how to install other plugins and configs.

**Comment by sergey-muntyanu** [comment]
@jhomarolo I'll try your solution and add feedback here.

**Comment by sergey-muntyanu** [comment]
@jhomarolo sorry for answering for so long? your solution working. Thank you!
