### ISSUE TITLE
"VALIDATE_ALL_CODEBASE: false" not having an effect

### ISSUE THREAD

**Issue by KatarzynaUlichnowska** [github/super-linter#400]
Hello, 
we have followed the instructions from the documentation and created the file in our repository: https://github.com/YetiForceCompany/YetiForceCRM/blob/developer/.github/workflows/linter.yml
 
The value VALIDATE_ALL_CODEBASE was set to "false" in order to check only new and edited files, instead of verifying the entire project. However, each time it is launched, the entire project is being checked and it takes a lot of time https://github.com/YetiForceCompany/YetiForceCRM/runs/853260284

Could you please have a look and advise if we did something wrong?

**Comment by admiralAwkbar** [comment]
@KatarzynaUlichnowska can you try to run it with the flag: `ACTIONS_RUNNER_DEBUG: true`
From the log output, it seems to be honoring the fact that the `VALIDATE_ALL_CODEBASE: true` as you see the output `Files that have been modified in the commit(s)`

But when it generates the diff, it seems to pull the whole codebase... also, can you try to go from `github/super-linter:v3` and then try `github/super-linter:latest` and see if you get the same result? maybe a bug in v3...

**Comment by mariuszkrzaczkowski** [comment]
ACTIONS_RUNNER_DEBUG: true
https://github.com/YetiForceCompany/YetiForceCRM/runs/854048614?check_suite_focus=true

super-linter:latest
https://github.com/YetiForceCompany/YetiForceCRM/runs/854051969?check_suite_focus=true

**Comment by admiralAwkbar** [comment]
Its ineterestin i see the command:
```bash
git diff --name-only 'master..f7005eac5f6b3e8efda27b146182a926c142f0dd' --diff-filter=d
```

## Reproduce
- git clone repo
- `git checkout master`
- `git diff --name-only 'master..f7005eac5f6b3e8efda27b146182a926c142f0dd' --diff-filter=d`

This will show you the exact same files that are being checked.

I ran and also see a huge diff in the files... 

Is your development that much different that your master??

**Comment by mariuszkrzaczkowski** [comment]
> Is your development that much different that your master??

Yes,
it's working now
`DEFAULT_BRANCH: developer`

**Comment by zkoppert** [comment]
@KatarzynaUlichnowska Is it accurate that your problem is resolved? It wasn't clear to me if @mariuszkrzaczkowski is working on the same repo as you or not. Thanks!

**Comment by KatarzynaUlichnowska** [comment]
Hello, 
yes, it is resolved - thanks a lot for your help. Mariusz is the Director of Product Development in YetiForce, so he is my colleague. That's why he also participated in this issue.
