### ISSUE TITLE
Make Raku Install better

### ISSUE THREAD

**Issue by admiralAwkbar** [github/super-linter#401]
@nbrown As you can see from the updated **Dockerfile**, we have moved to a more elegant way of installing some of the dependancies.

example:
```
COPY --from=mstruebing/editorconfig-checker:2.1.0 /usr/bin/ec /usr/bin/editorconfig-checker
```

Could we utilize something similar to install Raku?
Possibly from `https://hub.docker.com/_/rakudo-star`?
Or does it not have all the binaries we need?

I have just noticed the build and compile times have gone up, and the Raku step is a bit long

thanks!

**Comment by GaboFDC** [comment]
I noticed the same but wasn't able to find a quick solution. But do agree would be great if there was a binary we could use instead of having to build it from scratch.
