### ISSUE TITLE
Provide an arm64 docker image 

### ISSUE THREAD

**Issue by denisa** [github/super-linter#4028]
The docker image is build for amd64.
When I try to run super-linter locally on my new mac (M1), docker fails to execute all the linters and fails.

Docker supports multi-architecture images and the same image can be build to excute natively on multiple processors.

Please add support for arm61 to enable running on M1/M2/… based macs

Here is the kind of error that running an arm64 image on amd64 produces:
```
------
2023-03-30 03:30:11 [ERROR]   Found errors in [textlint] linter!
2023-03-30 03:30:11 [ERROR]   Error code: 133. Command output:
------
assertion failed [result.value != EEXIST]: VmTracker attempted to allocate existing mapping
(ThreadContextVm.cpp:47 mmap)
```

**Comment by denisa** [comment]
This was discussed in https://github.com/github/super-linter/discussions/1956

**Comment by BretFisher** [comment]
I've updated that comment https://github.com/github/super-linter/discussions/1956 with more details on what we're up against.

**Comment by denisa** [comment]
the issue has not been resolved, v5 is still an amd64 only image.

Can we please re-open this issue, as the need is still there.
