### ISSUE TITLE
Docker hub v3 tag incorrect

### ISSUE THREAD

**Issue by leviem1** [github/super-linter#404]
**Describe the bug**
The v3 Docker image tag points to v3.2.0. Clears up _a lot_ of confusion of comments in #368 (see below for more).

**Expected behavior**
Should point to v3.3.0 image.

**Additional context**
I'm a bad developer; this means that #359 _did_ successfully solve #356 making #368 and my #384 PR duplicates.

I assumed the issue was still present in v3.3.0 as my action used the v3 tag when it failed and I didn't compare the two. I didn't notice that my test run on master failed due to the introduction of HTML linting which checked files that I hadn't anticipated.

I'm gonna go be embarrassed and pretend this never happened, feel free to join! 😞

**Comment by admiralAwkbar** [comment]
@leviem1 I just pushed `3.3.1` can you verify looks good?

**Comment by admiralAwkbar** [comment]
Publishing `3.3.1` kicked the job https://github.com/github/super-linter/actions/runs/164595477

**Comment by admiralAwkbar** [comment]
Also... 404... lol

**Comment by leviem1** [comment]
The GitHub Action tag looks great. However, the [Docker Hub](https://hub.docker.com/r/github/super-linter/tags) tags aren't being updated. The README and Marketplace page both instruct users to use the Docker images, which is probably confusing for new users.

**Comment by leviem1** [comment]
Also, new image using GitHub actions is taking 10+ minutes to run. We should probably open a new issue to discuss that, but I don't think it's realistic to use super-linter for small projects anymore.

**Comment by admiralAwkbar** [comment]
@leviem1 As long as users are using the docker image and not the source, they get decent time... but agree, we need to look at options to speed up the full process

**Comment by admiralAwkbar** [comment]
I think the issue stems from an action not triggering when another action triggers. So we use an action to trigger a release creation, which we want to trigger another action to start and upload to docker hub... and it's not firing it

**Comment by leviem1** [comment]
Well, did we _create_ a release or _publish_ it? I think the "Deploy Docker Image - Release" only runs on release creation, which might not be triggered when you don't save as a draft first. Consider running only on "published" instead.

**Comment by past-due** [comment]
Another possibility (I haven't looked at the workflows involved yet):

> The GITHUB_TOKEN that is provided as a part of GitHub Actions doesn’t have authorization to create any successive events, such as GitHub Pages builds. [...] You’ll need to create a personal access token and supply it to your GitHub Action as a secret.

Source: https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096/2

(This applies to all successive events - not just GitHub Pages builds, although that's a common case where this crops up. The Personal Access Token workaround should work here to trigger successive events + workflows.)
