### ISSUE TITLE
Docker major version no longer correct

### ISSUE THREAD

**Issue by William-Luo0** [github/super-linter#4080]
## Describe the bug

With the release of major version 5.0.0, it appears that the docker image for the latest `v4` version was overwritten to also point to `v5.0.0`. Slim versions are also affected.

## Expected behavior

- A new `v5` image tag to be produced that points to the latest `v5.x.x` version.
- The existing `v4` image tag to point to the latest `v4.x.x` version

## Steps to Reproduce

See docker image digest for `v5.0.0` and `v4` on dockerhub
`v5.0.0`: https://hub.docker.com/layers/github/super-linter/v5.0.0/images/sha256-2119e8534e9a9e86a18bc5ae398b59c80c1906640a9c8537308a58fe111f07a9?context=explore
`v4`: https://hub.docker.com/layers/github/super-linter/v4/images/sha256-2119e8534e9a9e86a18bc5ae398b59c80c1906640a9c8537308a58fe111f07a9?context=explore

Both have the same image digest of `sha256:2119e8534e9a9e86a18bc5ae398b59c80c1906640a9c8537308a58fe111f07a9`

## Logs

N/A

## Additional context

N/A

**Comment by lindluni** [comment]
Thank you for the report, we will get that fixed on Docker Hub immediately.

**Comment by William-Luo0** [comment]
Looks like it's fixed now. Dockerhub image digests look right and there is now a `v5` tag.

I've verified:
* pulling `slim-v4` points to the same image as `slim-v4.10.1`
* pulling `slim-v5` points to the same image as `slim-v5.0.0`

If anyone else could also confirm, I think we should be good to close this bug.

**Comment by BretFisher** [comment]
Confirmed both v4/v5 full and slims on Docker Hub. Thanks for the quick fix @lindluni

**Comment by William-Luo0** [comment]
Cheers @BretFisher, I'll close this
