### ISSUE TITLE
Failed to switch to main branch to get files changed

### ISSUE THREAD

**Issue by krowlandson** [github/super-linter#409]
**Describe the bug**
Have provided feedback where I believe the source of the problem lies, but do not want to update without understanding why this was removed:
https://github.com/github/super-linter/commit/2f3011059a56a1d294f0b2ecef36f725007106b4

To summarise, we have started to get the following error when running a partial scan against changes only:

```shell
Gathering user validation information...
- Only validating [new], or [edited] files in code base...
Failed to switch to main branch to get files changed!
ERROR:[error: pathspec 'main' did not match any file(s) known to git]
```
This has started to appear on our pipelines (as of the time of the PR which introduced the change implemented above) when setting `VALIDATE_ALL_CODEBASE: false` and `DEFAULT_BRANCH: main` in a forked repository.

**To Reproduce**
1. Create a fork of a repository using Super-Linter to lint code base on push requests
2. Create a new branch
3. Start making changes to the code, and committing to GitHub
4. Watch the Super-Linter logs to see the error appear

An example of where this is happening:
https://github.com/krowlandson/AzOps/actions?query=workflow%3A%22Code+Review+%28Changes+Only%29%22

Please note how this was running fine, and then started to generate the above error over the weekend.

We plan to pin to a version now that arm-ttk is on the latest release, but are still running "latest" which is why we caught this.

**Expected behavior**
Super-Linter should be able to run all tests when initiated in a forked repository with `VALIDATE_ALL_CODEBASE: false` and `DEFAULT_BRANCH: main` vairables set.

**Screenshots**
none

**Additional context**
none

**Comment by nemchik** [comment]
https://github.com/github/super-linter/pull/408 resolved this. Should be in the next release.

**Comment by krowlandson** [comment]
👯 Working again now, thank you #408 !
