### ISSUE TITLE
Super-linter reports "Run failed" when no files are modified.

### ISSUE THREAD

**Issue by KineticTheory** [github/super-linter#422]
Hi,

I added super-linter as an extra CI for my C++ project and it is an excellent linter for our script files.  However, some PRs don't touch any script files.  For these PRs, the super-linter CI reports "Run failed".  

![super-linter-failed](https://user-images.githubusercontent.com/17579601/87601404-45751200-c6b2-11ea-9d5b-03014e2ce4a6.jpg)

Is there a way to disable the check when no applicable files are touched?  Is there a way to have it report `pass`, in this case?

Thanks!

**Comment by admiralAwkbar** [comment]
@KineticTheory Can you show me the lines in the `Lint Code Base` that are showing an error?

It should look for all file types it can validate, then base an error counter on those failures... So it shouldn't have failed.

Also, I see your using 2.1.0, can you try to bump to `3.3.1` or `latest` and see if the error goes away?

**Comment by KineticTheory** [comment]
@admiralAwkbar I copied `linter.yml` from an example I found somewhere on the internet (it is different that what is in your README.md).  Indeed, I was using 2.1.0.  I will update to 3.3.1 and see if that fixes my problem.  Thanks for the quick feedback.

**Comment by admiralAwkbar** [comment]
@KineticTheory Did this solve your issue? i wasn't able to reproduce on newer versions

**Comment by KineticTheory** [comment]
@admiralAwkbar Yes. It is fixed.  Sorry, I got distracted by another issue and just got back to checking on the report.
