### ISSUE TITLE
Getting file type broken+

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#456]
I think this broke the command, can you check?
This also shows that we don't have test for when `VALIDATE_ALL_CODEBASE` is false.
Kind of poetic that @admiralAwkbar broke the awk 😂

_Originally posted by @GaboFDC in https://github.com/github/super-linter/pull/449#discussion_r458477215_

**Comment by admiralAwkbar** [comment]
@GaboFDC I let y'all down lol my bad
