### ISSUE TITLE
Create test for validate all code base

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#475]
**Is your feature request related to a problem? Please describe.**
There has been a lot of bugs and errors not caught because the test only run each linter individually.

**Describe the solution you'd like**
There should be a test that runs the linter as a whole, and validate all code base, to test this case.

**Describe alternatives you've considered**
Running latest image against my repos

**Additional context**
I was thinking we may add a workflow that runs the built container against the `.automation/test` folder, and checks the output, it should lint all languages, and fail on the bad ones. But not really sure about the way to do this, maybe save the run output to a file, and compare it with an expected file? this was just my first thought but doesn't seem too maintainable, or maybe we could just grep the output for specific contents? 

I'm really looking forward for other thougths on this.

**Comment by GaboFDC** [comment]
Hey, @admiralawkbar @jwiebalk @zkoppert @IAmHughes @nemchik @Hanse00 I'll like some feedback and your thoughts on this, I'm willing to give it a shot, but would like to see other ideas and see how we could best solve this.

**Comment by jthelin** [comment]
It seems like it is particularly important that this should get run before EVERY official new release too, because for quite a few recent releases each X.Y.0 release drop gets followed almost immediately (sometimes within 1 hour!) by another X.Y.1 release to fix a bug in the last release drop. For example, 3.5.0/3.5.1 yesterday. 😢

**Comment by zkoppert** [comment]
Yes! I hear your point and agree with you @jthelin and @GaboFDC. It would be wonderful to catch these issues before the merge and release with some automated test. If you have some time that you are able to work on this I am happy to support as needed.
