### ISSUE TITLE
[](url)

### ISSUE THREAD

**Issue by santipg382s** [github/super-linter#479]
[](url)

_Originally posted by @santipg382s in https://github.com/github/super-linter/pull/478#issuecomment-664048338_

**Comment by santipg382s** [comment]
https://github.com/github/super-linter/issues/479#issue-665872335

**Comment by apur95** [comment]
H

**Comment by santipg382s** [comment]
> _Originally posted by @santipg382s in [#478 (comment)](https://github.com/github/super-linter/pull/478#issuecomment-664048338)_

**Comment by santipg382s** [comment]
> _Originally posted by @santipg382s in [#478 (comment)](https://github.com/github/super-linter/pull/478#issuecomment-664048338)_

**Comment by GaboFDC** [comment]
This seems like spam
