### ISSUE TITLE
Run shfmt in dry-run/check mode

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#492]
**Is your feature request related to a problem? Please describe.**
I don't like having shell code (POSIX, Bash, mksh) that doesn't follow the formatting standard that our team established.

**Describe the solution you'd like**
It would be great to run [shfmt](https://github.com/mvdan/sh) in dry-run mode, as part of the linting process. The dry-run mode returns a non-zero exit code (and a diff on stdout) when a file doesn't match the established formatting rules.

**Describe alternatives you've considered**
I currently run shfmt as a separate step in my CI pipeline. Here's an example `Make` target:

```make
.PHONY: shfmt
shfmt: ## Run shfmt tests
	@echo Running shfmt
	for file in $(shell find $(CURDIR) -type f -not -path "*/\.git/*" -not -name "*.md"  -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -print); do \
		f=$$(echo $$file | sed "s|^\$(CURDIR)/||"); \
		echo "Linting $$f"; \
		shfmt -d "$$f" || exit 1 ; \
	done;
```

**Additional context**
- shfmt supports [EditorConfig](https://editorconfig.org/) configuration files.
- shfmt can be installed as a Go module: `GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt`

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by admiralAwkbar** [comment]
@ferrarimarco that sounds like it could be super cool... Any chance you could try to make a PR with the ideas?

**Comment by ferrarimarco** [comment]
I can have a look!
