### ISSUE TITLE
How can I remove the mouse?

### ISSUE THREAD

**Issue by IlanCosman** [github/super-linter#503]
```
--------------------------------------------------------------------------------

                              /@@#///////@@/(@//@%/(@.@(       @@
                          @@//////////////////////////////#*  @@@
                        @////@//(///////////@@@@@///@//@/@**//@@(
                      @///////@///////////////@@@@    (           @,
                     @/(&/@////////////////////                     @
                    @////////////////////////@@                      @
                  @%////////(//////////%/////&@            @@       *,@
             @@@@@/@/#/////(&//////////////////                       .@
        *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%
      @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@
    @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @
@@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.
                                          @@@/@(  (@@@@% @/\      %
                                           @@@@(    .     .@@/\   #
                                             @                  %@%

--------------------------------------------------------------------------------
```

The mouse is very cute don't get me wrong, but it's just another thing to scroll past while getting to the actual information. Is there a way to disable it?

**Comment by nemchik** [comment]
It is a possum. It's digging through your garbage.

I suppose a flag to skip it could be reasonable.

**Comment by IAmHughes** [comment]
I don’t think we’ll be removing it, it’s kind of like any ASCII logo output you’d get in many CLI tools.

I’m going to close as `won’t fix` but I’ll let @admiralAwkbar and @zkoppert review in case we want to add a flag/option for this.

**Comment by bcdady** [comment]
I'd like to petition (presumably to) @admiralAwkbar and @zkoppert to reconsider offering flag to suppress the possum 'logo' from the head of each super-linter output. Perhaps a simpler "Super-Linter" header could be printed whenever `script: [ "true" ]`.

I get that the possum is "core logo", but I don't need to see it - at least not at the current "full" scale" - every time I review the pipeline output.

**Comment by admiralAwkbar** [comment]
@bcdady Hey! 
We love that possum but I understand your concerns...
I will look at adding a `SUPPRESS_POSSUM: true` that would hide the most glorious ASCII logo...
