### ISSUE TITLE
Dockerfile formatter choice

### ISSUE THREAD

**Issue by Matt-Gleich** [github/super-linter#515]
Is there a reason that super-linter uses dockerfilelint instead of hadolint? It seems like hadolint is more popular and more feature-rich. Thanks!

**Comment by admiralAwkbar** [comment]
@Matt-Gleich Hey!
When we first started setting up linters, `dockerfilelint` was the default use case.
With other languages, we are starting to support multiple tools. If you would like, you could make a PR for adding this and help get it supported 

thanks!

**Comment by Matt-Gleich** [comment]
Wow, thank you so much for the quick add @admiralAwkbar!
