### ISSUE TITLE
Explain the GITHUB_TOKEN more

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#533]
Just noticed an error in my workflow as wasn't setting the GITHUB_TOKEN. It's a silent error that's ignored, and the linting still works fine, so never noticed I hadn't configured my workflow correctly.

Which got me thinking - what's it needed for?

The [README.md](https://github.com/github/super-linter/blob/master/README.md) has the following to say:

> NOTE: You will need the Environment variable GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} set in your workflow file to be able to use the multiple status API returns. There is no need to set the GitHub Secret, it only needs to be passed.

Which doesn't explain very much to be honest and a search of the repo didn't explain it any more.

Testing it, it appears that when GITHUB_TOKEN is passed, it lists each Linter that is run for a Pull Request:

![Pull Request Test Results showing which linters were run](https://user-images.githubusercontent.com/10931297/89634119-c207a480-d89c-11ea-9de0-2a838ad29f41.png)

Without passing the `GITHUB_TOKEN`, only the first line is shown. A nice little extra feature that I didn't realise I was missing out on, so will add it to my workflow.

Is that the reason for the GITHUB_TOKEN? Does it do anything else?

Should we update the text to explain this better? Something like:

> NOTE: If you set the Environment variable `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` in your workflow file, then the GitHub Super-Linter will mark the status of each linter run in the Checks section of a pull request. There is no need to set the GitHub Secret as GitHub Actions does that automatically, it only needs to be passed.

Happy for me to submit a PR for this if you agree.

**Comment by ibnesayeed** [comment]
Well, essentially it elevates the permission the linter has on the repository. I don't see anything wrong in supplying this.

**Comment by bazzadp** [comment]
> Well, essentially it elevates the permission the linter has on the repository. I don't see anything wrong in supplying this.

No problem supplying it, but don't think the current text explains clearly why it's needed or that it can be run without it if someone doesn't want to supply it.

**Comment by ibnesayeed** [comment]
Yes, the wording could have been better.

**Comment by admiralAwkbar** [comment]
@ibnesayeed @bazzadp Hey all!

I agree the language could be more clear.

Can you make a small PR with the updated text?

Again, its only used to help make the additional status API updates and make visually parsing easier :)

Thanks for all the great feedback as well!
