### ISSUE TITLE
Example workflow configuration excludes linting of all filetypes

### ISSUE THREAD

**Issue by boonwj** [github/super-linter#536]
**Describe the bug**
Super-linter is excluding all languages when configured with the provided [example](https://github.com/github/super-linter#example-connecting-github-action-workflow).

**To Reproduce**

1. Create a workflow using the same example
2. Trigger a run

**Expected behavior**
Edited or new supported files should be linted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3538312/89661760-abe1fe80-d905-11ea-8be6-224e00a37ad3.png)
![image](https://user-images.githubusercontent.com/3538312/89661831-c2885580-d905-11ea-8782-9fd1b856e6fb.png)
![image](https://user-images.githubusercontent.com/3538312/89661863-d2a03500-d905-11ea-9ded-8aea942b32c8.png)

**Additional context**
- I added `ACTIONS_RUNNER_DEBUG` to obtain the debug information.
- Explicitly passing in `VALIDATE_[Language]` options will enable linting of those filetypes.

**Comment by admiralAwkbar** [comment]
@boonwj That's really odd behavior... it should by default do all languages it can find
ill see if I can try to reproduce and find it

**Comment by admiralAwkbar** [comment]
@boonwj Reproduced in `v3` but not with the latest, pushed new released with fixes and such...

It should work now? give it a shot :)
