### ISSUE TITLE
Support multiple Dockerfile definitions for dockerlinter

### ISSUE THREAD

**Issue by marghidanu** [github/super-linter#558]
I see that the check is performed only on the "Dockerfile" name, there are cases in which multiple users define multiple Dockerfile definitions like Dockerfile.dev, Dockerfile.prod, etc. 

Maybe the `(Dockefile|Dockefile\.*) rule makes more sense.

**Comment by admiralAwkbar** [comment]
@marghidanu Great feedback!

Please open a PR with the filename updates and we can get this added :)
