### ISSUE TITLE
Update CODEOWNERS with new feature

### ISSUE THREAD

**Issue by edulocFr** [github/super-linter#559]
**Feature description :**
I want to be notified when a file with a specific pattern is modified by someone.
For example, I want the DevOps team to be notified for each YML files which contains "NetworkPolicy".

**Describe the solution you'd like**
In CODEOWNERS file, I would like to be able to put regex and be notified when changed concerns the following files or the following keywords.

`
*.yml [/class.*?NetworkPolicy/] @DevOps
`

> Notified the `DevOps` team when a YML file which contains `NetworkPolicy` is modified.

Thanks,

**Comment by admiralAwkbar** [comment]
@edulocFr closing this as this is not a `Super-Linter` feature but more of an ask for **GitHub** Product to allow for more granular CODEOWNERS.

I'm sure someone could build an opensource version of this utilizing Probot, but not in the feature set of what the **Super-Linter** is.

I will follow up on this internally with Product feedback

**Comment by edulocFr** [comment]
Hi @admiralAwkbar,
Thanks for your response.

Yes I didn't know where to ask this feature. Feel free to keep me informed or link the right place to ask this new feature.
