### ISSUE TITLE
How to check version of each lint for the latest super-linter

### ISSUE THREAD

**Issue by ken5scal** [github/super-linter#564]
Sorry, but I could not find the file specifying the version of each linter

**Comment by GaboFDC** [comment]
You could check the dependencies folder and the dockerfile, but that's is a bit too picky, also you can run with ACTIONS_RUNNER_DEBUG=true and it will print each version of the linters used.

**Comment by admiralAwkbar** [comment]
@ken5scal that's the way we had it implemented was to hit the `ACTIONS_RUNNER_DEBUG=true ` if you needed to see versions

**Comment by ken5scal** [comment]
ic Thanks!
