### ISSUE TITLE
BuildFileList related bug

### ISSUE THREAD

**Issue by SeanTAllen** [github/super-linter#599]
When running with `VALIDATE_ALL_CODEBASE: false` then instead of shellchecking some of our bash scripts, we instead get the following warning:

`2020-08-22 18:01:47 [WARN  ]   Failed to get filetype for:[.ci-scripts/x86-64-nightly.bash]!`

It should be noted that with `VALIDATE_ALL_CODEBASE: true` the file(s) in question are correctly run through shellcheck.

Here is one of the files in question: 

https://github.com/ponylang/ponyc/blob/master/.ci-scripts/x86-64-nightly.bash

Here's the log from a run with VALIDATE_ALL_CODEBASE: false

https://github.com/ponylang/ponyc/runs/1016520529?check_suite_focus=true

and the exact same code only with VALIDATE_ALL_CODEBASE: true

https://github.com/ponylang/ponyc/runs/1016527976?check_suite_focus=true

**Comment by admiralAwkbar** [comment]
@SeanTAllen thanks for catching this one...
Can you try again with `latest` or `v3.8.3`
I think i caught this one earlier

**Comment by SeanTAllen** [comment]
It works with v3.8.3

Is it reasonable to update the documentation to use v3.8.3 rather than v3 as the "default" version?

**Comment by admiralAwkbar** [comment]
@SeanTAllen the tagging of v3 should always pull the latest 3.y.z so it should be good from now on

Someone had removed a lib and caused the parse to fail.... but should be all better now
