### ISSUE TITLE
Editorconfig linting - Stronger file filter ?

### ISSUE THREAD

**Issue by siwon** [github/super-linter#600]
Hi, 

I hope I understood correctly the code but it seems that editorconfig linting filter is very light. 
It looks like it takes all the files `"^.*$"`: 
https://github.com/github/super-linter/blob/0e075ccba96327a6d5dec6cc264ad7c06862e352/lib/linter.sh#L1450

Shouldn't it look like that : `.*\(editorconfig\)\$`?

PS: Thanks a lot for this repo :+1:

Edit: I tried to add a quick fix for this issue if it's relevent to you (#601 )

**Comment by ferrarimarco** [comment]
Editorconfig-checker doesn't lint the `.editorconfig` file (only). It checks the given file list (produced by the `^.*$` regex) against the rules specified in `.editorconfig`.

I guess this, and the related PR should be closed :)

**Comment by siwon** [comment]
Ok ! My bad ;)
