### ISSUE TITLE
Ignoring file paths from super-linter search

### ISSUE THREAD

**Issue by migolfi** [github/super-linter#614]
Hi, first off, thank you for the great work!

I've noticed when running super-linter in a codebase where I have an embedded dependencies folder that it will find and lint all of the subdirectories.

For examples, I download all of my Python packages to a folder in my workspace called .venv and that contains my entire virtual environment (similar to node_modules anyways). In those cases, it looks like options include disabling linters or digging into specific linters and disabling on a case-by-case basis.

I came across #395 already, is there a way to generally ignore certain file paths being included in the super-linter search?

Thank you!

**Comment by admiralAwkbar** [comment]
@migolfi Hey thanks!
There is not but i need to add `.venv` and `.rbenv` to the ignored folders as we should likely never lint them as well :)

**Comment by migolfi** [comment]
Thanks @admiralAwkbar!

Adding `obj/` and `bin/` folders could be helpful as well, for C# codebases.
Otherwise, are there plans to allow a flexible exclusion pattern?

**Comment by admiralAwkbar** [comment]
@migolfi Its something we have looked at but haven't come to a consensus on how we achieve it... There are a few ways to take the issue and all lead to a lot of customization and not what I want to do yet...

Hope this helps you get going for now and thanks for the input!

**Comment by migolfi** [comment]
@admiralAwkbar Thanks for the explanation. This has all been extremely helpful!

When is the next release planned (containing the .venv change)?

**Comment by admiralAwkbar** [comment]
@migolfi Hey im going to try to cut a release later today! Mondays are always work...
