### ISSUE TITLE
Why bash-exec reports a warning and not an error?

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#643]
The `bash-exec` linter emits a warning when a shell script is not executable, and not an error like any other linter. Moreover, this behavior is not configurable. Is it possible to make `bash-exec` behave like the other linters that super-linter runs?

**Comment by admiralAwkbar** [comment]
@ferrarimarco 
This was an interesting one...

I agree for most files they should be exec, but then I thought about library code, that gets imported and does not need to be exec. So it was a weird one... We decided to start on warning, but I don't have a more elegant plan and could be persuaded both ways on this one...

**Comment by ferrarimarco** [comment]
What if we always warn, and error if VALIDATE_BASH_EXEC is true?

Or an additional environment variable to set this behavior?

**Comment by ferrarimarco** [comment]
If we choose a behaviour here, I can provide a PR :) @admiralAwkbar
