### ISSUE TITLE
Latest version is not deployed on Docker Hub, nor on GitHub registry

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#655]
**Describe the bug**
Due to issues when publishing the latest image (v3.9.2), it doesn't get published on Docker Hub or on GitHub Registry.

**To Reproduce**

1. See build logs for latest commits

**Expected behavior**
Updated Docker images to be published.

**Screenshots**
See build logs.

**Additional context**
Maybe those commits are related?

https://github.com/github/super-linter/commit/9f808022ba24e6359195c696e401cdff7b2f6469
https://github.com/github/super-linter/commit/3490d97bb1b12b9979c7fa2b958ab14152867534

/cc @admiralAwkbar

**Comment by admiralAwkbar** [comment]
@ferrarimarco this was a fun bug to hunt down. sorry for the issue but we have been published to both locations now.

thanks for catching this and keeping an eye on us :)

**Comment by ferrarimarco** [comment]
The hero we deserve :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco 
![](https://media.giphy.com/media/joV1k1sNOT5xC/giphy.gif)

**Comment by ferrarimarco** [comment]
I think there's still something off :(

See the log (for both Docker Hub and GitHub reg):

```
awk: cmd. line:1: {print ${1}}
awk: cmd. line:1:         ^ syntax error
awk: cmd. line:1: {print ${1}}
awk: cmd. line:1:            ^ syntax error
awk: cmd. line:1: {print ${2}}
awk: cmd. line:1:         ^ syntax error
awk: cmd. line:1: {print ${2}}
awk: cmd. line:1:            ^ syntax error
awk: cmd. line:1: {print ${3}}
awk: cmd. line:1:         ^ syntax error
awk: cmd. line:1: {print ${3}}
awk: cmd. line:1:            ^ syntax error
```

**Comment by ferrarimarco** [comment]
@admiralAwkbar

**Comment by ferrarimarco** [comment]
And no images are pushed

**Comment by gfeun** [comment]
Hey,
Came from the Github Container Registry [blog post](https://github.blog/2020-09-01-introducing-github-container-registry/) and can't find the public image. This may be related to this issue.

**Comment by admiralAwkbar** [comment]
Docker Hub: https://hub.docker.com/layers/github/super-linter/v3.9.2/images/sha256-af121534c758925e241ecdc57d4ee960f1ee16e9ea0675ece5a8116a2279dde8?context=repo

Github Container Registry:
https://github.com/orgs/github/packages/container/super-linter%2Fsuper-linter/26504

**Comment by gfeun** [comment]
Thanks for the link. 
There's a typo in your GCR url: https://github.com/orgs/github/packages/container/super-linter/26504

It may be useful to update the blog post to point to this image as it can't be found on the super-linter repo

**Comment by admiralAwkbar** [comment]
@gfeun 
thats super odd...
https://github.com/orgs/github/packages/container/super-linter/27083

**Comment by admiralAwkbar** [comment]
i think they are moving things around on me 👍

**Comment by ferrarimarco** [comment]
I was able to pull from GCR! :)

**Comment by ferrarimarco** [comment]
@admiralAwkbar the link to packages in the home page of the repo points to a stale repository (the latest package there is 3.6.0).

Stale repo link: https://github.com/github/super-linter/packages
