### ISSUE TITLE
Super-linter analyzes more files than was changed in a feature branch

### ISSUE THREAD

**Issue by dec5e** [github/super-linter#671]
**Describe the bug**
Super-linter analyzes more files than expected: not only files changed in a feature branch but also files changed in a default branch after feature branched was actually branched. 

This is a follow up to a bug described in #544. it was closed with a fix but I still see an unexpected behaviour, so extracting here my comment to have an open issue (feel free to reopen old one and close this if preferred).

**To Reproduce**
I've created a test repo to show it, check this PR https://github.com/dec5e/super-linter-test/pull/2 and linter results. I've confirmed that correct version of the linter is used: image hash is `11ec9aa31cdc` which matches v3.8.3, the fix was released under v3.7.0. 

_I copied description from that PR below_:

In my example only one file was changed in a branch: `TEST.md`. Super-linter though shows more than this:
```
2020-08-28 11:43:15 [INFO  ]   Files that have been modified in the commit(s):
2020-08-28 11:43:15 [INFO  ]   File:[README.md], File_type:[md], Base_file:[readme.md]
2020-08-28 11:43:15 [INFO  ]   File:[TEST.md], File_type:[md], Base_file:[test.md]
```
And because there is an invalid content in `README.md` file, changed in `master` after this branch was created, `super-linter` is showing errors.

`git diff` used to get the list of files for checks inside `super-linter` shows files list as expected:
```bash
$ git checkout branched-from-old-master
Already on 'branched-from-old-master'
$ git log --oneline --abbrev-commit --all --graph --decorate
* 7f923f5 (HEAD -> branched-from-old-master, origin/branched-from-old-master) Add random changes in a different file
| * e45e3c0 (origin/master, origin/HEAD, master) Merge pull request #1 from dec5e/invalid-content
|/| 
| * 2e0b438 (origin/invalid-content, invalid-content) Add invalid content
|/  
* 3dc00f5 Add description
* 0055836 Add super-linter workflow
* f9d0371 Initial commit

$ git diff --name-only 'master...7f923f5' --diff-filter=d
TEST.md
```

**Expected behavior**
Only files changed in a feature branch are linted. In my example - only `TEST.md`

**Comment by admiralAwkbar** [comment]
@dec5e Hey, we have seen this before.

## Problem
In order to get an exact match of the files changed in the PR, we would need to call the GitHub API to get the list, this would  need an additional call to GitHub to gather the information, and would strictly limit using the super-linter from GitHub and Actions.

We would like to keep this git agnostic so that others can take advantage of it, but i have not come up with a better solution to how to get an exact list of files changed in a PR...

If you have any insights it would greatly be appreciated

**Comment by dec5e** [comment]
Could you point to the code used right now to determine a list of changed files? Originally I thought the list of files is determined only by `git diff <default_branch>...<commit_id>`, by this code block: https://github.com/github/super-linter/blob/v3.9.4/lib/buildFileList.sh#L48-L53. For me locally it gives a correct list. So it seems that's not the only place used to get the list?

**Comment by Clint-Chester** [comment]
Just experienced this same problem 😢 this article is a good explanation of the problem - https://blog.developer.atlassian.com/a-better-pull-request/

**Comment by dec5e** [comment]
@Clint-Chester actually, problem I'm facing is different. My struggle is that `git diff ...` doesn't work here as expected, the article goes beyond this discussing next steps to improve PRs.

**Comment by dec5e** [comment]
The solution which fixed the issue for me was an update to `actions/checkout@v2` config in workflow yaml file:
```yaml
- name: Checkout Code
  uses: actions/checkout@v2
  with:
    # Next configuration fixed the described behaviour for me
    fetch-depth: 0
```

For the explanation please see the sample PR I created https://github.com/dec5e/super-linter-test/pull/4. Quoting important part:

> The problems seems to be in the way the code is fetched by `actions/checkout@v2` which fetches only 1 last commit by default. When I do the same locally and then do `git diff master...feature-branch` (as `super-linter` does) the command fails for me completely. Not sure why `super-linter` is not failing but it doesn't work correct either. Fetching entire git history with `actions/checkout@v2` fixes the issue.
