### ISSUE TITLE
Make Checkstyle style configuration configurable for Java

### ISSUE THREAD

**Issue by HorizonNet** [github/super-linter#680]
**Is your feature request related to a problem? Please describe.**
Currently the Java linter via Checkstyle only allows Sun's style due to hardcoding it to `sun_checks.xml`. It would be great to make it configurable to also allow [Google's style](https://checkstyle.org/google_style.html) (or make own configuration files available).

**Describe the solution you'd like**
Making Google's Style available could happen by exposing a configuration called `JAVA_ENABLE_GOOGLE_STYLE`, which can be either set to `true` or `false` (`false` as the default).

**Describe alternatives you've considered**
An alternative could be to allow any kind of (custom) Checkstyle configuration similar on how it is done for Yamllint configuration via `YAML_CONFIG_FILE`. With that existing, customized Checkstyle configurations can be used outside of Sun's or Google's style.

**Additional context**
- [Checkstyle style configurations](https://checkstyle.org/style_configs.html)
- [Custom Checkstyle configuration](https://checkstyle.org/config.html)

**Comment by HorizonNet** [comment]
Comment to remove the stale label from this one for now. Need to find some time to look into it on my own.

**Comment by Grahame-student** [comment]
Is this still valid? I added a copy of sun_checks.xml to .github/linters in my repo, made a few changes to the configuration and triggered the action. The results from the linting showed that the changes had made a difference.

Or was this more about being able to have greater control over the linting rules from the workflow configuration?

**Comment by HorizonNet** [comment]
@Grahame-student Probably yes. But before going deeper into it, the name of the file needed to be `sun_checks.xml` within the `.github/linters` directory, correct? Usually the Checkstyle definition is located at a different location within a project. Also, the filename `sun_checks.xml` would be misleading if a different definition was actually used, such as the Google style. My initial suggestion describes the easiest way where no customization of the rulesets is done. The more flexible solution would be what I described in the alternative approach.

**Comment by sindrenm** [comment]
This should probably be approached similarly as it has been for other linters, right? Just like there's an `CSS_FILE_NAME` environment variable for reading a stylelint configuration, one could have a `JAVA_FILE_NAME` pointing to a checkstyle config?
