### ISSUE TITLE
Support Oracle PL/SQL

### ISSUE THREAD

**Issue by felipecrs** [github/super-linter#682]
It would be very good if we could add support to PL/SQL (Oracle).

Sadly, [sql-lint does not support PL/SQL](https://github.com/joereynolds/sql-lint/issues/166). I found some tools though:

https://github.com/pmd/pmd
https://github.com/Trivadis/plsql-cop-cli
https://github.com/alanmcruickshank/sqlfluff

But I don't know what would be better.

**Comment by admiralAwkbar** [comment]
@felipecrs Hey that would be great if someone could take a stab at it... I looked at pmd and was able to get it up and running, but my lack of knowledge on pl/sql made it tough to test :)

**Comment by felipecrs** [comment]
@admiralAwkbar it may be funny but I also have almost zero knowledge about pl/sql. If I discover something useful I will keep this issue updated. :)

**Comment by felipecrs** [comment]
There is a set of PL/SQL sample files suitable for testing in the following folder:

https://github.com/utPLSQL/utPLSQL/tree/develop/test

And I found a tool other than the ones presented earlier:

https://github.com/felipebz/zpa-cli

In my test, it's the most reliable one. Usage:

[![asciicast](https://asciinema.org/a/G7j48cAuuWwXe9WYBuwAcDLoX.svg)](https://asciinema.org/a/G7j48cAuuWwXe9WYBuwAcDLoX)
