### ISSUE TITLE
Super-Linter has started linting node_modules as part of v3.10.0

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#704]
**Describe the bug**
Just got a dependenabot note about v3.10.0 being released. Linting failed in that pull request due to Super-linter now linting the `node_modules` folders and many npm developers not following our HTML conventions.

Note we do not check in `node_modules`to our repo, however we do generate HTML as part of our build process (which requires `npm install` to have run), so run an HTML Lint on that (see [our workflow here](https://github.com/HTTPArchive/almanac.httparchive.org/actions/runs/247486234/workflow)) and this threw the error, which did not happen on v3.9.4

**To Reproduce**

1. Use a repo that uses node
2. Kick off a full HTML linting (not just changed files) using v3.10.0 but also running `npm install` in the action before.
3. Notice from the log files that all `node_module` HTML files are linted - and many probably failed.

**Expected behavior**
I would expect only my source code to lint - like they did prior to v3.10.0

**Screenshots**
See example log file here: https://github.com/HTTPArchive/almanac.httparchive.org/pull/1282/checks?check_run_id=1094735802

**Additional context**
I presume this is due to #696 and could be fixed with the recently merged #684 ? If so can we have a v3.10.1 or v3.11.0 release with that?

**Comment by ferrarimarco** [comment]
#696 is for rules files, not to select files to lint :)

**Comment by ferrarimarco** [comment]
@bazzadp can you check if #707 fixes this?

**Comment by bazzadp** [comment]
Not sure how to build and test the linter locally. Is there an easy way to call this from an Action?

Presume I can't do it as simply as this?:
```
      uses: ferrarimarco/super-linter@fix-node-modules
```

**Comment by ferrarimarco** [comment]
Nope :)

1. Clone https://github.com/ferrarimarco/super-linter
1. Switch to the `fix-node-modules` branch
1. Build the Docker image
1. Try linting your codebase by running a Docker container as you would in your CI pipeline :).

Example (running the container, from the directory where the code to lint is), that you can adapt to your needs:

```shell
	docker run --rm -it \
		-v "$(pwd)":/workspace \
		-w="/workspace" \
		-e ACTIONS_RUNNER_DEBUG=true \
		-e DEFAULT_WORKSPACE=/workspace \
		-e DISABLE_ERRORS=false \
		-e LINTER_RULES_PATH=/workspace \
		-e MULTI_STATUS=false \
		-e RUN_LOCAL=true \
		-e VALIDATE_ALL_CODEBASE=true \
		ghcr.io/github/super-linter:v3.9.2
```

**Comment by bazzadp** [comment]
Gto that working (took a while to build!) but still seeing it linting the `node_modules` folder and so throwing up lots of errors.

**Comment by bazzadp** [comment]
Reverting the changes in this commit fixes it: https://github.com/github/super-linter/commit/0e5f996c3c68727d21824ff25bf80ebcbeb04477#diff-409b55ad463cfac3e14fdaa2a919cfeb

**Comment by bazzadp** [comment]
OK added some debugging.

The `$FILE` is set to: `/workspace/node_modules`, this means `$DIR_NAME` is set to `/workspace` by this line:

https://github.com/github/super-linter/blob/767a39e10703f8754501d4a94cb26232513fa4df/lib/worker.sh#L178

This means this clause is never fired (nor any of the following ones):

https://github.com/github/super-linter/blob/767a39e10703f8754501d4a94cb26232513fa4df/lib/worker.sh#L183-L186

We could strip off workspace and look at the next folder, but that would mean it only ignores top-level `node_modules` (and similar) rather than nested ones where as prior to that bad commit it ignored all `node_modules` folder.
