### ISSUE TITLE
Python linters: Flake8 incompatibility with Black / E203

### ISSUE THREAD

**Issue by madietlx** [github/super-linter#709]
**Describe the bug**
When both Flake8 and Black are used to lint python code, there are some rare cases that cause incompatibilities between the two, i.e., without disabling one of the linters (or at least the line that causes the warning) the linting/checks will fail.

**To Reproduce**
As described in the Black docs: https://github.com/psf/black/blob/master/docs/compatible_configs.md#flake8
Flake8 might raise an `E203 whitespace before ':'` warning,
which is caused by Black adding a whitespace before the colon (`:`) in some cases.

See this issue: https://github.com/psf/black/issues/315
which states that the line `tup = nsamples, nalleless[i : i + size], i, size` causes the error.

This line is very similar to my code and is meant as an example to illustrate the case.

**Expected behavior**
It would be desirable that both Flake8 and Black can be used to lint the same code base
-- without the need to disable one of them or the line in question.

Following the Black docs (see above), this should be fixed by adding
```
extend-ignore = E203
```
to the `.flake8` configuration file.

**Comment by GaboFDC** [comment]
Different linters have diferent rule set and different defaults. Trying to lint with multiple linter for the same languages can have some benefits but also some challenges like this.
Changing the one whole linter default to be compatible with other linter does not seems like the proper solution, and also could affect the users already using it.
I think this is more of a personalized config, so you can add it to your own `.flake8` config file, and use that one instead of the template.

**Comment by madietlx** [comment]
I would not want to disagree with what you said in general, but please consider that
- this change should be more PEP 8 compliant, not less (*supposing Black is right here?*)
- this change extends what is ignored so that the effects should be minimal (*but noticeable, of course!*)
- the Flake8 config files `TEMPLATES/.flake8` and `.github/linters/.flake8` already contain

```
[flake8]
max-line-length = 120
```

which looks like some upper-bound chosen to silence the linter (which is fine with me, just wanted to point this out).

That said, I would be perfectly fine with using a personalized `.flake8` config. Reading the super-linter docs ([https://github.com/github/super-linter#template-rules-files](https://github.com/github/super-linter#template-rules-files)), I can see that I am supposed to put my `.flake8` config into `.github/linters/`. I'm sure that this works server-side, running the workflow as a GitHub Action. 

**But how do I load my personalized Flake8 config file locally?**

What I want to achieve is: Run the linter locally via `docker run -e RUN_LOCAL=true`. If it runs through without errors, push changes, otherwise fix, commit and test again. For this to work flawlessly, the config on GitHub should match the local one.

**Comment by GaboFDC** [comment]
About running it locally:
1) you can also put the linter file in the root and use `LINTER_RULES_PATH` which is more standard.
2) when running locally, and having the linter file under `.github/linters/` it should pick it up, and run exactly as it runs on the actions. If you use the `LINTER_RULES_PATH` you can also pass it to the container, and should also work

About the change in the defaults, i'll wait for other collaborators to comment, maybe I'm a bit biased.

**Comment by madietlx** [comment]
@GaboFDC Just tested it out. Having the `.flake8` linter file under `.github/linters/` did not work locally. With or without `LINTER_RULES_PATH`, made no difference.

What did work: Running the docker image `github/super-linter:v3` with

`-v '$(shell git rev-parse --show-toplevel)/.github/linters/.flake8':/action/lib/.automation/.flake8:ro`

Looks a bit overcomplicated. Not like it is supposed to be done that way (but at least it works.)
