### ISSUE TITLE
Support linting of Kubernetes descriptors with Kubeval

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#730]
**Describe the solution you'd like**
Kubernetes descriptors could be validated with https://github.com/instrumenta/kubeval

**Describe alternatives you've considered**
N/A

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by admiralAwkbar** [comment]
@ferrarimarco I like it, lets get it in
