### ISSUE TITLE
Move Images to GHCR?

### ISSUE THREAD

**Issue by assignUser** [github/super-linter#735]
Hey!

I contributed the R and LaTeX linters and use images currently hosted on docker hub. Should I publish/pull these on/from ghcr specifically in view of the new pull limits on docker hub?

**Comment by admiralAwkbar** [comment]
Hey, @assignUser We push to both locations with the same binaries/containers when built. So whatever works for you is fine. Where trying to make this as easy to use for all platforms and if there is anything we can do, please let me know

thanks!

**Comment by assignUser** [comment]
Ah, I think I might have not phrased that very clearly. I maintain these images:
https://github.com/github/super-linter/blob/58d3d191b823648aeb2610568a29b31ee86e895d/Dockerfile#L19-L20

And I was wondering if I should make them available via ghcr instead of docker hub (free accounts have a 100pulls/6h limit now, which wasn't reached yet but as this is a growing project I wanted to be proactive :) )

**Comment by admiralAwkbar** [comment]
@assignUser I understand now... that makes a lot more sense :)
I think that would be great and would be very much appreciated.
