### ISSUE TITLE
Grab snakefmt and black from their container images instead if installing them

### ISSUE THREAD

**Issue by montyly** [github/super-linter#762]
Hi,

Similar to https://github.com/github/super-linter/issues/722, black was downgraded to `19.10b0` again with https://github.com/github/super-linter/pull/713. `19.10b0` does not follow the exact same rules as `20.8b1`, as a result, some workflows are not passing anymore (ex: https://github.com/crytic/slither/pull/643).

Do you know if there is a specific version conflict between `black` and `Snakemake`? 
Otherwise I can reproduce https://github.com/github/super-linter/pull/725 to fix the issue.

**Comment by ferrarimarco** [comment]
I have to reopen this :(

Building the latest master says:

```shell
2020-11-13 14:03:09 [DEBUG]   Linter version for black: black, version 19.10b0. Error code: 0
2020-11-13 14:03:09 [INFO]   Successfully found version for [black]: black, version 19.10b0
```

**Comment by ferrarimarco** [comment]
From Pipfile.lock:

```json
        "black": {
            "hashes": [
                "sha256:1b30e59be925fafc1ee4565e5e08abef6b03fe455102883820fe5ee2e4734e0b",
                "sha256:c2edb73a08e9e0e6f65a0e6af18b059b8b1cdd5bef997d7a0b181df93dc81539"
            ],
            "index": "pypi",
            "version": "==19.10b0"
        },
```

**Comment by montyly** [comment]
It seems to be needed because of `stakefmt` requirements. See the related discussion: https://github.com/github/super-linter/issues/807

**Comment by ferrarimarco** [comment]
I see. Thanks @montyly

**Comment by ferrarimarco** [comment]
[snakefmt](https://github.com/snakemake/snakefmt#containers) is also containerized already. I'm wondering if we can use this to our advantage somehow, instead of installing it in our image...

**Comment by ferrarimarco** [comment]
What we're currently doing is:

```dockerfile
RUN pipenv install --system
```

I guess we can solve this issue by avoiding a system installation, and use pipenv to manage virtual environments. We might adopt this approach in general, or only with tools that cause conflicts, such as `snakefmt`.

Maybe a generalized solution is easier to implement?

**Comment by ferrarimarco** [comment]
Another option: seems that Black now [publishes self-contained binaries](https://github.com/psf/black/pull/1743). No releases to evaluate yet...

**Comment by GaboFDC** [comment]
Managing a venv for each py dependencies inside the containers seems like a pain, if now binaries and containers are available, we can move from installing with pip, to copy the binary from the container or downloading it.

**Comment by ferrarimarco** [comment]
Ok. Changing the issue title to reflect this stance.
