### ISSUE TITLE
- name: Super-Linter   uses: github/super-linter@v3.11.0

### ISSUE THREAD

**Issue by Yunus259** [github/super-linter#763]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by admiralAwkbar** [comment]
@Yunus259 Not sure what the issue is?

**Comment by prabhakarreddy1234** [comment]
docker pull github/super-linter:3.11.0
Error response from daemon: manifest for github/super-linter:3.11.0 not found: manifest unknown: manifest unknown
