### ISSUE TITLE
multiple Regex exclude folder

### ISSUE THREAD

**Issue by catborise** [github/super-linter#768]
hi,
i want to exclude more than 1 folder. How can it be done? There is no clue on docs.

there are two folders: static, dev/scss

".*static/.*" ".*dev/scss/.*"
FILTER_REGEX_EXCLUDE:  .... ?

**Comment by nvuillam** [comment]
You can build a regex with multiple matching strings

Example :  **(/static/|/dev/scss)**

You can play with an online regex editor to build your appropriate RegEx
https://regex101.com/r/YemT0T/2
