### ISSUE TITLE
Support ignore experience similar to .gitignore

### ISSUE THREAD

**Issue by migolfi** [github/super-linter#786]
**Is your feature request related to a problem? Please describe.**

I love that I can integrate "One linter to rule them all", and with that comes the file ignoring challenge.
Recently we've seen generated code added to our repo and the lint errors which come with it.
The generated code is absolutely needed for our tests, and so it needs to be maintained in the repo.
I added the `FILTER_REGEX_EXCLUDE` variable to ignore the files under that path,
although it leaves a lot to be desired to match the experience in ignoring files which is supported
by Git and several other tools.

**Describe the solution you'd like**

I would like have an experience similar to having a `.superlinterignore` file, which can be at
any directory level and allow that to determine which files are added or removed from the list
of files needing to be linted.

**Describe alternatives you've considered**

Currently, the `FILTER_REGEX_EXCLUDE` will work for single paths, and I can see it becoming very
hard to read and even maintain if several paths need to be ignored.

**Comment by ferrarimarco** [comment]
And you might just symlink your `.gitignore` to point to `.superlinterignore` (much like we're doing with the `.dockerignore` in this repo), and fallback reading the `.gitignore` file directly...
