### ISSUE TITLE
tag 3.11.0 is not available

### ISSUE THREAD

**Issue by prabhakarreddy1234** [github/super-linter#812]
# docker pull github/super-linter:3.11.0
Error response from daemon: manifest for github/super-linter:3.11.0 not found: manifest unknown: manifest unknown

**Comment by admiralAwkbar** [comment]
![Screen Shot 2020-10-07 at 11 52 03 AM](https://user-images.githubusercontent.com/29484535/95362319-89337e00-0893-11eb-88c9-e3b320bf568e.png)

Hey @prabhakarreddy1234 
Seems maybe a bad connection?
