### ISSUE TITLE
Possible typo in markdownlint template

### ISSUE THREAD

**Issue by theodore-s-beers** [github/super-linter#816]
**Describe the bug**
In `TEMPLATES/.markdown-lint.yml`, at line 25, the `line_length` value—i.e., the maximum number of characters allowed per line (with certain exceptions)—is set to `808`. To me it seems like a typo, with `80` being the intended (and commonly used) value. But I didn't want to presume, so I figured I would ask here rather than making a one-character PR. Please close the issue if `line_length: 808` has in fact been set deliberately.

**To reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
Here's the documentation for the relevant rule in markdownlint:
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013

**Comment by admiralAwkbar** [comment]
@theodore-s-beers I think you might have found a fun typo that was likely set to make the error go away lol...

Feel free to open a pr :)

**Comment by theodore-s-beers** [comment]
Ok. You're right… I'm almost reluctant to deprive myself and others of the 728 characters of leeway…
