### ISSUE TITLE
Upgrade to 3.12.0 automatically checks .editorconfig

### ISSUE THREAD

**Issue by HorizonNet** [github/super-linter#825]
**Describe the bug**
When upgrading to 3.12.0 an `.editorconfig` in the repository gets analyzed automatically, even with `VALIDATE_ALL_CODEBASE` is set to `false`.

**To Reproduce**

1. Update the `super-linter` action in a repository with an existing `.editorconfig` to 3.12.0.
2. Linting workflow will automatically check the `.editorconfig` even when it wasn't changed.

**Expected behavior**
When `VALIDATE_ALL_CODEBASE` is set to `false` no unchanged files should be checked.

**Screenshots**
Editorconfig error in workflow
![Screen Shot 2020-10-08 at 10 31 51 PM](https://user-images.githubusercontent.com/1908271/95510410-24247900-09b6-11eb-9ec9-8bc2095cd539.png)

Changes from the pull request
![Screen Shot 2020-10-08 at 10 32 13 PM](https://user-images.githubusercontent.com/1908271/95510437-2f77a480-09b6-11eb-98c7-be4fa0386321.png)

**Additional context**
A similar behavior appears when adding the super-linter to an existing repository with `VALIDATE_ALL_CODEBASE` set `false`. The expected behavior when just adding the linter workflow is that actually no files get checked.

After the release of 3.12.0 the version 3.11.0 behaves in the same way, which it did not do before. Feels related to #490 and #708. As seen below, the image version `v3` is used, even with 3.12.0 defined for the super-linter.

![Screen Shot 2020-10-08 at 10 38 28 PM](https://user-images.githubusercontent.com/1908271/95510937-03a8ee80-09b7-11eb-8508-21ce11f8c661.png)

**Comment by ferrarimarco** [comment]
@HorizonNet can you try with `3.13.0` that @admiralAwkbar just released? We fixed some issues we had when building the file list, and others related to include/exclude linters.

Please, let us know if this issue is still there. Thanks!

**Comment by HorizonNet** [comment]
@ferrarimarco The same behavior still happens. The following screenshot show part of the linter log from a Dependabot PR trying to bump from 3.11.0 to 3.13.0. Dependabot is actually only touching the workflow definition, not the Editorconfig file.

![Screen Shot 2020-10-14 at 9 26 58 AM](https://user-images.githubusercontent.com/1908271/95957227-bafe9480-0dff-11eb-8a1c-6b28a09ce60a.png)

**Comment by ferrarimarco** [comment]
This is working as expected. [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) (the linter that's complaining) doesn't lint `.editorconfig` files for correctness, but it checks text files **against** an `.editorconfig` file. In other words, if a text file doesn't follow the rules you set in your `.editorconfig`, `editorconfig-checker` is going to flag it as an error.

In the example, as you can see, you're missing a new line at the end of `.github/workflows/linter.yml`.

**Comment by HorizonNet** [comment]
@ferrarimarco Thanks for the pointer. I completely oversee this one. Yes, then it's working as expected.
