### ISSUE TITLE
Terragrunt Linter should automatically ignore .terragrunt-cache folders

### ISSUE THREAD

**Issue by troyfontaine** [github/super-linter#830]
**Is your feature request related to a problem? Please describe.**
When trying to use the new Terragrunt linter, the time to scan a repo is drastically longer (when performed locally) due to the fact that super-linter has to slog through the source repos pulled in by Terragrunt.

**Describe the solution you'd like**
The Terragrunt linter should automatically add an exclude files filter to avoid linting non-Terragrunt files by identifying .terragrunt-cache directories and skipping them.

**Describe alternatives you've considered**
I have attempted to modify the FILTER_REGEX_EXCLUDE and have been unable to find a regex that will even match (regex may not be my strong suit-but testing using online regex testers has found syntax that should work but does not).

**Additional context**
None

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by admiralAwkbar** [comment]
@troyfontaine 
Hey thanks for the input!

Is there a default `.terragrunt-cache` folder?
If so we could have that set to ignore... Sorry I'm not an expert on terragrunt :)

**Comment by troyfontaine** [comment]
HI @admiralAwkbar they can be nested anywhere inside of the repository-so it isn't a matter of directory depth unfortunately.  With the structure my org uses:

```
└── Account
     └── Region
         └── Purpose
             ├── App
             │   ├── terragrunt.hcl
             │   ├── stuff.tf
             │   └── .terragrunt-cache
             ├── App2
             │   ├── terragrunt.hcl
             │   ├── stuff.tf
             │   └── .terragrunt-cache
             └── App3
                 ├── terragrunt.hcl
                 ├── stuff.tf
                 └── .terragrunt-cache
```

Here is the example from the Terragrunt website:
```
└── live
    ├── prod
    │   ├── app
    │       ├── .terragrunt-cache
    │   │   └── terragrunt.hcl
    │   ├── mysql
    │       ├── .terragrunt-cache
    │   │   └── terragrunt.hcl
    │   └── vpc
    │       ├── .terragrunt-cache
    │       └── terragrunt.hcl
    ├── qa
    │   ├── app
    │       ├── .terragrunt-cache
    │   │   └── terragrunt.hcl
    │   ├── mysql
    │       ├── .terragrunt-cache
    │   │   └── terragrunt.hcl
    │   └── vpc
    │       ├── .terragrunt-cache
    │       └── terragrunt.hcl
    └── stage
        ├── app
        │   └── terragrunt.hcl
        ├── mysql
        │   └── terragrunt.hcl
        └── vpc
            └── terragrunt.hcl
````

**Comment by admiralAwkbar** [comment]
Hey no worries at all! it does look like it always follows that naming so I can make it to where it'll always look for it

**Comment by troyfontaine** [comment]
> Hey no worries at all! it does look like it always follows that naming so I can make it to where it'll always look for it

The folder name is always the same!  Thank you!
