### ISSUE TITLE
Upgrade Dockerfilelint to allow linting Dockerfiles with HEALTHCHECK

### ISSUE THREAD

**Issue by a16bitsysop** [github/super-linter#832]
**Describe the bug**

Any dockerfile with healthcheck fails as dockerfilelinter has its own error

**To Reproduce**

1. Add a healthcheck to a dockerfile
1. Run  super-linter on it

**Expected behavior**

Fails if problem with syntax or pass if ok

**Screenshots**

```
2020-10-10 15:36:30 [ERROR ]   Found errors in [dockerfilelint] linter!
2020-10-10 15:36:30 [ERROR ]   [/node_modules/dockerfilelint/lib/checks.js:185
      if (!options.reduce((valid, item) => valid &&
                   ^

TypeError: Cannot read property 'reduce' of null
    at Object.is_valid_healthcheck (/node_modules/dockerfilelint/lib/checks.js:185:20)
    at runLine (/node_modules/dockerfilelint/lib/index.js:274:16)
    at Object.module.exports.run (/node_modules/dockerfilelint/lib/index.js:62:18)
    at processContent (/node_modules/dockerfilelint/bin/dockerfilelint:92:50)
    at /node_modules/dockerfilelint/bin/dockerfilelint:86:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/node_modules/dockerfilelint/bin/dockerfilelint:65:8)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)]
2020-10-10 15:36:30 [ERROR ]   Linter CMD:[dockerfilelint -c 
```

**Additional context**

Run via GitHub actions

**Comment by ferrarimarco** [comment]
This shouldn't happen, you're right. Can you run super-linter again after setting `ACTIONS_RUNNER_DEBUG=true`? Thanks!

**Comment by ferrarimarco** [comment]
And, can you also show us the Dockerfile that's causing the issue?

**Comment by ferrarimarco** [comment]
Apparently, this is an upstream issue: https://github.com/replicatedhq/dockerfilelint/issues/156

I'll leave this open as a reminder to update dockerfilelint when they fix the issue.

**Comment by a16bitsysop** [comment]
Yes I found the upstream one after posting this [here](https://github.com/replicatedhq/dockerfilelint/issues/156#issuecomment-707827305) and commented on it as well.  Do you still want the debug info?

**Comment by ferrarimarco** [comment]
Not needed anymore :)

**Comment by a16bitsysop** [comment]
I can get a Dockerfile to pass with the current dockerfilelint using the command:
`docker run -v `pwd`/Dockerfile:/Dockerfile replicated/dockerfilelint /Dockerfile`

But the same Dockerfile with a healthcheck will fail with this version.

The healthcheck has to have an option before the command to stop this error, and must end in ` || exit 1`

**Comment by a16bitsysop** [comment]
.

**Comment by a16bitsysop** [comment]
.

**Comment by GaboFDC** [comment]
This is not a super-linter issue, and when/if/until the issue is resolved on dockerfilelint there is nothing to do on our side.

**Comment by a16bitsysop** [comment]
@ferrarimarco commented earlier he was leaving this open as a reminder to update dockefile-lint when they fix it

**Comment by GaboFDC** [comment]
I'm ok with leaving it open, but the dependabot should update the dockerfilelint js dependency as soon as is released.

**Comment by a16bitsysop** [comment]
Okay I will let the stale bot mark this then dockerfile-lint does not seem very active.

**Comment by HANZSOLO-CU** [comment]
Noted.. as u wish.
