### ISSUE TITLE
Markdown linter not honoring rules in default config

### ISSUE THREAD

**Issue by LogicNinja** [github/super-linter#844]
**Describe the bug**
The markdown linter does not appear to be honoring the rules defined in the default .markdown-lint.yml config file.
There is a rule to trigger MD013 only on lines over 808 characters however, this now triggers when lines are over 80 characters. This is the default behaviour in the markdown linter but the config file should be overriding this.
Specifying your own config also doesn't work.

This only started happening in the past week.

**To Reproduce**
1. Write some markdown that contains a line over 80 characters in length.
2. Run the linter in docker locally with default values.

**Expected behavior**
The validation should pass on not trigger an MD013 violation

**Screenshots**
![image](https://user-images.githubusercontent.com/25649379/95803539-1707e100-0d4c-11eb-9d3f-7b4dc3fc67d6.png)

For now we have disabled markdown linting but this is sub-optimal

**Comment by FlyingEagles** [comment]
{{End Mackdown linter}}

**Comment by ferrarimarco** [comment]
See #816

**Comment by admiralAwkbar** [comment]
@ferrarimarco @LogicNinja I think making this a more user friendly number is the right answer.

- `80` chars seems a little low these days
- `808` seems a bit high...
- `404` sounds about right...
