### ISSUE TITLE
import-error with same config

### ISSUE THREAD

**Issue by JuliusJacobitz** [github/super-linter#861]
Hi there, 
my issue looks like this: 
I recieve the following error even when my pylintrc-file is exactly like the basic pylint-lint file.
`E0401: Unable to import 'pandas' (import-error)`.
When i disable the  PYTHON_PYLINT_CONFIG_FILE env var in my linter.yml I recieve no errors, but the file should have the same content ? 

What am I missing ? 
Thanks for any help !

**Comment by ferrarimarco** [comment]
Can you post the full output, after setting `ACTIONS_RUNNER_DEBUG=true`?

**Comment by GaboFDC** [comment]
Also see #157
