### ISSUE TITLE
Push to branch: No files were found in the GITHUB_WORKSPACE

### ISSUE THREAD

**Issue by IvanKuchin** [github/super-linter#900]
Hello, 

Below command will find 0 differences between HEAD and last commit id if push commit to DEFAULT_BRANCH
 
https://github.com/github/super-linter/blob/b058f4ac1e4dbd77f3b75dcdece5d879f082ae19/lib/buildFileList.sh#L65

In case of PUSH to branch it is better use 

`git diff-tree --no-commit-id --name-only -r ${GITHUB_SHA}`

or 

`git show --pretty="" --name-only ${GITHUB_SHA}`

Warning message:
![image](https://user-images.githubusercontent.com/26530162/97027330-92297e00-1528-11eb-9b44-c38a541f20c0.png)

**Comment by ferrarimarco** [comment]
Feel free to open a PR in THIS repo. I think you've opened one in your own fork :)
