### ISSUE TITLE
Disable specific folders in file lists

### ISSUE THREAD

**Issue by Joannazhx** [github/super-linter#907]
I noticed even I set FILTER_REGEX_EXCLUDE to exclude some folders, it only worked at the check code stage. In the gathered list of files...The super-linter will still scan the files inside the exclude folders and put them into file lists. I'm dealing with a large and complicated folder, the super-linter scan to get file lists took 20 mins locally. Is there any way I could use to set ignore some folders?

**Comment by TomerFi** [comment]
Same here, it slows down the linter in projects with a lot of files excluded.

**Comment by GaboFDC** [comment]
Where you running against all the code base?
Maybe for these cases would be better to check only changed files with `VALIDATE_ALL_CODEBASE=false`
Also, could you provide some debug logs to see what kind of files are and why the find takes so long?

**Comment by TomerFi** [comment]
This is still an issue for me.
When running the super-linter locally, too much time is wasted by scanning excluded folders and file types.

When running:

```shell
docker run --rm -e RUN_LOCAL=true -e OUTPUT_FORMAT=tap -e OUTPUT_DETAILS=detailed `
-e LINTER_RULES_PATH=. -e VALIDATE_EDITORCONFIG=true -e VALIDATE_DOCKERFILE_HADOLINT=true `
-e VALIDATE_GROOVY=true -e VALIDATE_JAVA=true -e VALIDATE_JSON=true -e VALIDATE_MARKDOWN=true `
-e VALIDATE_XML=true -e VALIDATE_YAML=true `
-e FILTER_REGEX_EXCLUDE="(.git|.*.tap|.flattened-pom.xml|/lib/|/target/)" `
-v ${PWD}:/tmp/lint ghcr.io/github/super-linter:v3
```

The linter scans the excluded `lib` and `target` folders as well.
It's important to emphasize, it just scans them - it doesn't perform any linting operations on the file found.
The scanning itself takes to much time, and as these folders contains mostly file types unknown to the linter,
My screen gets loaded with `Failed to get filetype for:` warnings.

**Comment by TomerFi** [comment]
@GaboFDC 
I remember reading somewhere that when setting specific linters manually as I did,
`VALIDATE_ALL_CODEBASE` is implicitly set to `false`.
Nevertheless, I've just tried it, but `VALIDATE_ALL_CODEBASE=false` doesn't change anything for me.
