### ISSUE TITLE
Score is obtained after the test is completed

### ISSUE THREAD

**Issue by DreamPWJ** [github/super-linter#914]
We hope to automate the code quality test in Jenkins' CI/CD. If the score is greater than 90, the test will continue and if the score is less than 90, the test will be terminated

**Comment by GaboFDC** [comment]
This is an interesting idea, but could you elaborate more on how do u think this will work? how will the score be calculated?

**Comment by DreamPWJ** [comment]
can reference    https://www.codefactor.io/
