### ISSUE TITLE
Update .eslintrc.yml to accept jsonc files

### ISSUE THREAD

**Issue by WSLUser** [github/super-linter#921]
**Is your feature request related to a problem? Please describe.**

If you use jsonc files, the linter will complain about comments. But if you use https://www.npmjs.com/package/eslint-plugin-json-format, you will find the support is there to simply ignore the comments. VSCode uses this to lint jsonc files. 

**Describe the solution you'd like**

Super-Linter should match VSCode and update the plugin field, along with anything else needed. Also use regular ESLint for json linting. Typescript is useless in projects that use other languages that read in the json files such as C++.

**Describe alternatives you've considered**

Disable the json linter or create your own linter rules and ensure it actually ignore the comments.

**Additional context**

Prevents Windows Terminal from utilizing the json linter which is one of the primary purposes of Super Linter for that project since there's no C++ linter yet to use.

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by nhojt** [comment]
This would be a great improvement.

**Comment by Joannazhx** [comment]
We have the same issue here. Our project uses JSONC and JSON. Jason lint always treat comments in JSON as errors.

**Comment by nhojt** [comment]
bump :)

**Comment by GaboFDC** [comment]
Could you provide some example files that fail when run by super-linter. And how do you run eslint with the eslint-plugin-json-format plugin locally for it to lint properly?
This would be a great help to get it implemented.

**Comment by nhojt** [comment]
Hi, I'm not familiar with the ESlint plugin OP mentions, but the error in Super-Linter can be recreated easily e.g. 
``` json
{
    // a comment
    "key": "value"  
}
```
throws:
```
2021-01-04 10:31:23 [ERROR]   Found errors in [jsonlint] linter!
2021-01-04 10:31:23 [ERROR]   Error code: 1. Command output:[Error: Parse error on line 1:
{    // a comment    "ke
-----^
Expecting 'STRING', '}', got 'undefined'
    at Object.parseError (/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at parse (/node_modules/jsonlint/lib/cli.js:82:14)
    at main (/node_modules/jsonlint/lib/cli.js:135:14)
    at Object.<anonymous> (/node_modules/jsonlint/lib/cli.js:179:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)]
```

I also stumbled over this plugin https://www.npmjs.com/package/jsonc-eslint-parser which might be another option.

**Comment by nvuillam** [comment]
@GaboFDC @nhojt  the recipe is the following :) 

- in dockerfile: npm install eslint-plugin-jsonc
- create a default `.eslintrc-json.json` in TEMPLATES (i tried to use default eslintrc.json but it does some mess when you use eslint for js/ts and json)
- in runtime; call eslint with json files and [force .eslintrc-json.json as configuration](https://nvuillam.github.io/mega-linter/descriptors/json_eslint_plugin_jsonc/#example-calls)

More info here -> https://nvuillam.github.io/mega-linter/descriptors/json_eslint_plugin_jsonc/ :)

**Comment by nvuillam** [comment]
Mmmm actually it was more complicated than that...

What I said in the message below is still valid, but when you have files with extensions .jsonc and .json5 , you need to specify the parser in eslintrc-json.config file for each extension

```json
{
    "overrides": [
        {
            "files": ["*.json"],
            "extends": [
                "plugin:jsonc/recommended-with-json"
            ],
            "parser": "jsonc-eslint-parser",
                "parserOptions": {
                    "jsonSyntax": "JSON"
            }
        },
        {
            "files": ["*.jsonc"],
            "extends": [
                "plugin:jsonc/recommended-with-jsonc"
            ],
            "parser": "jsonc-eslint-parser",
                "parserOptions": {
                    "jsonSyntax": "JSONC"
            }
        },
        {
            "files": ["*.json5"],
            "extends": [
                "plugin:jsonc/recommended-with-json5"
            ],
            "parser": "jsonc-eslint-parser",
                "parserOptions": {
                    "jsonSyntax": "JSON5"
            }
        }
    ]
}
```

**Comment by nhojt** [comment]
not stale

**Comment by WSLUser** [comment]
not stale

**Comment by nhojt** [comment]
bump

**Comment by gmacario** [comment]
Not stale

**Comment by admiralAwkbar** [comment]
Looking tro see about chaning from `jsonlint` to eslint` for all json to help solve this....
We shall see...
