### ISSUE TITLE
v3.13.3 is not in Docker Hub, nor GitHub Container Registry 

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#925]
**Describe the bug**

Version 3.13.3 was not deployed to any artifact repository because the [build failed](https://github.com/github/super-linter/runs/1294033734). I've seen the build failing many times because of this exact issue. Time to fix it? :)

**To Reproduce**

1. `docker run ghcr.io/github/super-linter:v3.13.2`

**Expected behavior**

Run `ghcr.io/github/super-linter:v3.13.2`.

**Logs**

```shell
"super-linter": Error response from daemon: name unknown
```

**Additional context**

Complete build log: https://github.com/github/super-linter/runs/1294033734

Relevant extract:

```shell
Step 41/76 : RUN wget --tries=5 -O phive.phar https://phar.io/releases/phive.phar     && wget --tries=5 -O phive.phar.asc https://phar.io/releases/phive.phar.asc     && gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79     && gpg --verify phive.phar.asc phive.phar     && chmod +x phive.phar     && mv phive.phar /usr/local/bin/phive     && rm phive.phar.asc     && phive install --trust-gpg-keys 31C7E470E2138192,CF1A108D0E7AE720,8A03EA3B385DBAA1
 ---> Running in 29bc54cc3eed
Connecting to phar.io (188.94.27.6:443)
Connecting to github.com (140.82.114.4:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.102.91:443)
saving to 'phive.phar'
phive.phar           100% |********************************|  187k  0:00:00 ETA
'phive.phar' saved
Connecting to phar.io (188.94.27.6:443)
Connecting to github.com (140.82.112.3:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (54.231.120.219:443)
saving to 'phive.phar.asc'
phive.phar.asc       100% |********************************|   854  0:00:00 ETA
'phive.phar.asc' saved
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Address not available
The command '/bin/sh -c wget --tries=5 -O phive.phar https://phar.io/releases/phive.phar     && wget --tries=5 -O phive.phar.asc https://phar.io/releases/phive.phar.asc     && gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79     && gpg --verify phive.phar.asc phive.phar     && chmod +x phive.phar     && mv phive.phar /usr/local/bin/phive     && rm phive.phar.asc     && phive install --trust-gpg-keys 31C7E470E2138192,CF1A108D0E7AE720,8A03EA3B385DBAA1' returned a non-zero code: 2
2020-10-22 17:38:46 [FATAL ]   failed to [build] Dockerfile!
Error: Process completed with exit code 1.
```

Possible workaround, as discussed in https://github.com/nodejs/docker-node/issues/380#issuecomment-348464695

Instead of just running:

```shell
gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
```

use something like:

```shell
( gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEYS" \
  || gpg --keyserver pgp.mit.edu --recv-keys "$GPG_KEYS" \
  || gpg --keyserver keyserver.pgp.com --recv-keys "$GPG_KEYS" )
```

Thoughts?

**Comment by ferrarimarco** [comment]
I think it's safe to re-run the job that failed so that the version is finally pushed to the registries, but I've proposed a fix in #926

**Comment by ferrarimarco** [comment]
@admiralAwkbar I've reopened this as a reminder that we still have to publish the missing version. Is it safe to just re-run the build job that failed? I think so, but wanted to have a confirmation before acting.

**Comment by admiralAwkbar** [comment]
@ferrarimarco Im not sure what happened here... will try to cut it again

**Comment by GaboFDC** [comment]
This happens because we merge a failing PR #926 there is no point on doing dev build if we push them anyways when they fail. We should re run and debug them to only push working build. Anyone pullint latest image will have this same error. Are you guys checking this out? I'm not totalyl sure why that pr made the error, but i'm giving it a look asap

**Comment by GaboFDC** [comment]
Seems like the problem is that PowerShellGallery gallery is down (https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md), so the build couldn't install the modules. But for some reason, the build didn't fail when the command to install PSScriptAnalyzer failed.

**Comment by GaboFDC** [comment]
The #929 fixes so the run doesn't fail if the module doesn't exist, but we are not using it. No need to fail the build if we are not going to lint Powershell.

But still, we have to give a look, to fail the docker build when the command to install PSScriptAnalyzer fails

**Comment by ferrarimarco** [comment]
Thanks @GaboFDC .

The build I'm referring to (https://github.com/github/super-linter/runs/1294033734) failed because of the error downloading the GPG key that I mentioned above. But still #929 is a welcome fix!

Let's remember to publish the 3.13.3 somehow. I suppose re-running the failing job should do it.

**Comment by ferrarimarco** [comment]
@admiralAwkbar I don't know if we care, but `v3.13.3` is still not in any registry, even if we fixed (mitigated?) the root issue.

**Comment by admiralAwkbar** [comment]
@ferrarimarco Going to redeploy it
