### ISSUE TITLE
When we do Run the container Locally ，Check to see if the web page is available

### ISSUE THREAD

**Issue by DreamPWJ** [github/super-linter#931]
Super Linter is great but for most companies to go private and deploy detection, we need a view page to see the detection results, and it's best to distinguish between the project and the detection per Git commit

**Comment by admiralAwkbar** [comment]
@DreamPWJ The Actions results show the files and what issues were detected per commit, so I'm not sure what else we could do to help?
Are you asking for a separate page to be made when issues are reported?
