### ISSUE TITLE
Add more pre-release testing

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#949]
**Is your feature request related to a problem? Please describe.**
The GitHub super-linter has published a number of bad releases since go-live which have been left in place for hours and days. This is particularly a problem as this project does not follow versioning (see #708 ) so this affects even those repos that do not upgrade, and also affects all forks and branches meaning even if we try to [work around a bad release](https://github.com/github/super-linter/issues/938#issuecomment-720977157) it requires all those forks and branches to pick up the latest workaround. This is a big problem when all linting workflows across many projects suddenly break.

The latest example is #938. While that issue can be dedicated to fixing that immediate problem I would like to raise this separate issue to track how this was able to get through to a release. Consider this almost the RCA and follow up actions to try to prevent #938 happening again.

**Describe the solution you'd like**
Add test cases to prevent the cause of issues like #938.

**Describe alternatives you've considered**
The super-linter should also:
- Fix versioning - #708 
- Add post release checks to immediately identify issues on a bad release - #948

**Additional context**
Issues that have broken the linter (not an exhaustive list):
- #704
- #938

**Comment by admiralAwkbar** [comment]
@bazzadp i agree... I take full responsibility for some of these releases and some of the lack of testing.
As this is more widely adopted, we need to make sure `master/main` is always hyper stable.
I will look into this week to see if we can create some additional safeguards to help resolve this

**Comment by ferrarimarco** [comment]
One idea here might be to fail with a fatal error if the TAP file is missing, instead of raising a warning (that no one is going to fix). Thoughts?

**Comment by admiralAwkbar** [comment]
@ferrarimarco I agree
