### ISSUE TITLE
super-linter includes .git directory in the list of files to lint

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#954]
**Describe the bug**

```shell
Step #0 - "super-linter": 2020-11-04 10:04:35 [DEBUG]   File:[/workspace/.git], File_type:[git], Base_file:[.git]
Step #0 - "super-linter": 2020-11-04 10:04:35 [WARN]   Failed to get filetype for:[/workspace/.git]!
```

Affects v3.13.5, maybe others.

**To Reproduce**

1. Run super-linter in a Git repository.

**Expected behavior**
super-linter should ignore the `.git` directory [as expected](https://github.com/github/super-linter/blob/master/lib/buildFileList.sh#L98).

**Comment by ferrarimarco** [comment]
Reopening, because the PR didn't fix it. We should use this kind of syntax to exclude dotdirs: `find . -path */.git -prune -o -print`

**Comment by ferrarimarco** [comment]
Btw, we didn't notice because `editorconfig-checker` is the only linter we don't run, because we don't have a `.editorconfig` file in this repo. Maybe it's time to add one?

**Comment by admiralAwkbar** [comment]
@ferrarimarco The `-print` causes the list to contain the folders now in the list.. so not a great fix for this...

**Comment by admiralAwkbar** [comment]
Example:
```bash
find "/Users/admiralawkbar/github/super-linter" \
-path "*/node_modules" -prune -o \
-path "*/.venv" -prune -o \
-path '*/.git' -prune -o -print \
-path "*/.rbenv" -prune -o \
-path "*/.terragrunt-cache" -prune -o \
-type f 2>&1 | sort

/Users/admiralawkbar/github/super-linter/lib
/Users/admiralawkbar/github/super-linter/lib/README.md
/Users/admiralawkbar/github/super-linter/lib/buildFileList.sh
/Users/admiralawkbar/github/super-linter/lib/linter.sh
/Users/admiralawkbar/github/super-linter/lib/linterVersions.sh
/Users/admiralawkbar/github/super-linter/lib/log.sh
/Users/admiralawkbar/github/super-linter/lib/possum.sh
/Users/admiralawkbar/github/super-linter/lib/validate-docker.sh
/Users/admiralawkbar/github/super-linter/lib/validation.sh
/Users/admiralawkbar/github/super-linter/lib/worker.sh
```

**Comment by ferrarimarco** [comment]
that was an example :)

**Comment by ferrarimarco** [comment]
We don't need print. Wait a sec, I'll prepare a quick PR

**Comment by ferrarimarco** [comment]
Can you have a look at #964?

**Comment by mpeteuil** [comment]
👋 Hi there! I wasn't sure where to ask, but I was wondering when we should expect a new release with #964 and #965?
