### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [github/super-linter#958]
## Describe the bug

The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://phpstan.org/n

## Expected behavior

Link should work

## Steps to Reproduce
Click the link for "PHPStan"

## Additional context

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by josephmarino** [comment]
Thanks, @MrCull! This should be fixed by PR #960 😸
