### ISSUE TITLE
Add an .editorconfig file?

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#965]
As we've seen in #954, by not including an `.editorconfig` file, we're not able to run `editorconfig-checker` on the whole code base. (the tests work tho!)

Including one has the benefit of being able to spot more issues, and helps us maintaining a consistent style.

Thoughts?

@admiralAwkbar

**Comment by admiralAwkbar** [comment]
@ferrarimarco I thought we had a template at some point... we need to add it back 👍 
Make it so :)
