### ISSUE TITLE
Support custom file extension for existing linters

### ISSUE THREAD

**Issue by mcm-ham** [github/super-linter#967]
Our project uses Microsoft files like app.config or web.config that are XML files.

We would like the ability to indicate that .config should be linted using the XML linter.

An alternative approach is to add support for plugins to allow devs more control e.g. it registers what file extensions it can handle, and then provide plugin with a list of matching files to lint, which can then return results in a format super linter specifies.

**Comment by ferrarimarco** [comment]
One thing we might do (as we did with other linters), is to add an exception to detect if a `.config` file is also an `XML` file.

How does one of those config files looks like?

**Comment by mcm-ham** [comment]
Sure it looks like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="custom" type="ConfigurationSample.CustomConfigurationSection, ConfigurationSample"/>
  </configSections>
  <connectionStrings>
    <add name="sampleDatabase" connectionString="Data Source=localhost\SQLExpress;Initial Catalog=SampleDatabase;Integrated Security=True"/>
  </connectionStrings>
  <appSettings>
    <add key="sampleApplication" value="Configuration Sample"/>
  </appSettings>
  <custom>
    <customConfigurations>
      <add key="customSample" name="Mickey Mouse" age="83"/>
    </customConfigurations>
  </custom>
</configuration>
```

**Comment by ferrarimarco** [comment]
@mcm-ham can you run super-linter locally setting `ACTIONS_RUNNER_DEBUG=true` ?

Something like:

```shell
docker run \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=. \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -v $(pwd):/tmp/lint \
  ghcr.io/github/super-linter:latest
```

We do have a fallback for when super-linter is not able to decide how to lint a file, but I suppose it's not working for this kind of file, and it should.
