### ISSUE TITLE
Why do we have the disable-linters document?

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#969]
Having the `disable-linters.md` document (which might contain stale information) is a maintenance chore for us.

What if we get rid of that, and just refer to each linter docs?

For example, in that file we state about `klint`: `There is no top level _configuration file_ available at this time`, which is not true as we discovered in #966 (and then by reading klint docs).

Shall we just get rid of that, and update the README and the PR templates accordingly?

**Comment by admiralAwkbar** [comment]
@ferrarimarco I think when we only had a few languages it was easy, but now as more and more join, we should likely just point to their configurations or homepages so users can see the documentation hosted by the source... I would be good for that direction
