### ISSUE TITLE
SQL Server Lint Support

### ISSUE THREAD

**Issue by Joannazhx** [github/super-linter#972]
**Is your feature request related to a problem? Please describe.**
Hi, 

We use SQL Server in our codebase, the current sql-lint only supports MySQL and PostgreSQL. It will be really useful if you could add another SQL lint which could check the SQL server.

**Describe the solution you'd like**
This one tsqllint works well for SQL Server. 
https://github.com/tsqllint/tsqllint
I'll really appreciate if you could add this lint into Super Lint

Thanks a lot!

**Comment by LowlyDBA** [comment]
@admiralAwkbar Thanks for taking a stab at this - the repo is indeed active (24 days ago last commit) and I've had it running for quite some time as a discrete [Github Action](https://github.com/LowlyDBA/dba-multitool/blob/master/.github/actions/tsqllint-action/Dockerfile) so it should work on Alpine.
