### ISSUE TITLE
How to increase memory limit for PHP/PHPStan linter?

### ISSUE THREAD

**Issue by foodev** [github/super-linter#986]
I configured the [PHPStan](https://phpstan.org/) linter for a big project but it often crashes due to not enough memory:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate ... bytes)

If I use PHPStan locally and pass e.g. `--memory-limit 1GB` as parameter it works fine. But there's no option to specify this memory limit in the PHPStan config file (which has nothing to do with the super-linter).

I understand that there're always [7 GB of RAM for each GitHub Action](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources). Is there a way to increase the memory limit for PHP/PHP linters?

**Comment by admiralAwkbar** [comment]
@foodev Added the flag for 1GB
Hopefully, this can help!

**Comment by foodev** [comment]
Thanks for the quick fix! This should definitely help, though it would be good to set this limit manually (as described in https://github.com/github/super-linter/issues/987).
